### ISSUE TITLE
1.1 "organizational construct"

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#108]
in the second sentence of article 1.1 the words `organizational construct` are used. For a lot of folks not daily involved in designing organizations the word organization construct is too theoretical and complex. Suggest to use something like "roles are the building blocks of the organization" instead.

**Comment by brianjrobertson** [comment]
I think we need something more concrete/descriptive than the colloquial "building blocks" phrase; anyone have suggestions for what we can say a role is, other than an "organizational construct"?

**Comment by pscheuerer** [comment]
I usually talk about "structural elements” for roles/circles and “process
elements” for the meetings. To make building blocks more concrete,
“structural building block” would be an option, but it’s pretty heavy.


On 28 June 2016 at 15:48:24, KoenVeltman (notifications@github.com) wrote:

in the second sentence of article 1.1 the words organizational construct
are used. For a lot of folks not daily involved in designing organizations
the word organization construct is too theoretical and complex. Suggest to
use something like "roles are the building blocks of the organization"
instead.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/holacracyone/Holacracy-Constitution/issues/108>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAtdnOGbD6IUhG_q1myF-cXgV0zbHvIvks5qQSYogaJpZM4JAHkz>
.

**Comment by julianeroell** [comment]
I quite like "structural element" AND ;-) I am wondering if any conceptual word is needed there at all: Would 

>The Organization’s Partners will typically perform work for the Organization by acting in an explicitly defined Role. A “Role” has a descriptive name and one or more of the following:

possibly suffice there?

**Comment by brianjrobertson** [comment]
I think that does work - thanks!
