### ISSUE TITLE
Simplify Organizational purpose definition

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#131]
articles 1.1a and 5.2.3 both describe what a purpose is but use slightly different language.
recognizing that for the purpose of an organization you should also consider as described the constraints to the organization `given all of the constraints acting upon it and everything available to it. That includes its history, current capacities, available resources, Partners, character, culture, business structure, brand, market awareness, and all other relevant resources or factors.`

but the definition of what purpose is for an organization does not have to be different from that of a role.

suggest to either use the same language in the two articles. or refer in 5.2.3 to the definition in 1.1a.

**Comment by brianjrobertson** [comment]
I'm not sure if this is possible without losing some important clarity to the organization's purpose, or overcomplicating/over-constraining the role's purpose.  But maybe there is a path; any suggestions?

**Comment by MiekeByerley** [comment]
I feel that they are two different things, same nature but different
expression. Put it this way the Purpose of a body and how that is defined
is different to that of the purpose of a Cell within the said body and how
that is defined. In the case of the cell, the relationship towards the body
is the primary nucleus of its Purpose whereas the primary nucleus of the
Body's Purpose is the expression of its essence (Self). Hope that made
sense. :)

**Comment by KoenVeltman** [comment]
There is a different "order of magnitude" when comparing the purpose of an organization with that of a circle or a role.  

Holacracy is based on the principle of a "Holon". With a signature of a holon that it looks identical when you zoom in. Following that reasoning I would argument for a similar definition of purpose for an organization/circle/role. 

not sure about this yet. maybe my thought is too simplistic. open to new ideas here!
My intention is to align our language in practice with that in the constitution. And in practice I see in many organizations the same language when adressing purpose on the different structures in their Holacracy run organization

**Comment by MiekeByerley** [comment]
Ah, I understand where you are coming from. I guess I see a Holon more in the traditional sense of its meaning :) https://en.wikipedia.org/wiki/Holon_(philosophy).

**Comment by KoenVeltman** [comment]
I don't actually have a very personal opinion about this. except for that I am seeking simplicity and alignment.

When I currently look in Glassfrog then the purpose definition of the Anchor/General circle, that of another circle and that of a role are identical. 

So whatever way we go: I would love to see alignment in what we define in the (future) constitution and what our active tools tell us what it actually is.

**Comment by Roflcopterpaul** [comment]
I'm with Koen in that having both descriptions be identical would be more simple and beneficial. Perhaps change them to:

Role:
**"the deepest creative potential or unrealizable goal it can sustainably pursue or express in the Organization, given all of the constraints acting upon it and everything available to it."**
(The italicized part is optional - just pondering if it needed to be specific that a Role's purpose may be slightly more specific

Organization:
**"the deepest creative potential or unrealizable goal it can sustainably pursue or express in the world, given all of the constraints acting upon it and everything available to it."**

My two main thoughts on this are that them being close to the same helps a lot in terms of explanation and understanding. Also, I don't think the organization one needs all those examples, because examples aren't listed for most other things in the Constitution where examples could absolutely be justified.

**Comment by brianjrobertson** [comment]
Nice integration!  I’ll review & consider further, though this looks really promising...

**Comment by KoenVeltman** [comment]
nice @Roflcopterpaul ! great integration.
if I would try to find the common factor in "in the world" and "in the organization" in your two statements I would suggest to replace both with "in the ecosystem it is part of".  I am not sure if I actually am a fan of this myself. sounds a bit technical... But there might be a similar statement.
