### ISSUE TITLE
Clarify objection validity criterion d)

### ISSUE THREAD

**Issue by diederickjanse** [holacracyone/Holacracy-Constitution#14]
Objection validity criterion d) in article 3.2.4 currently references the _proposal_ validity criteria in article 3.2.2, which requires some mental gymnastics to understand.

I would propose to reproduce those criteria in the language of an _objector_ (not a proposer), so that the objection validity criterion d) can stand on its own and be understood (more) clearly.

**Comment by julianeroell** [comment]
Basically, d) means: "The Tension comes from one of your roles; or one that you have been granted permission to represent", right?  Would it be too simple to write it in in this way? ("comes from" probably is too vague.)

**Comment by brianjrobertson** [comment]
I've changed it to:  "(d) The Tension limits the Objector's capacity to express the Purpose or an Accountability of one of the Objector’s Roles in the Circle; or, if it limits another Role, the Objector has permission to represent that Role from a Circle Member who normally fills the Role."

That's not actually quite the same thing as the effect of v4.0 language, as there's another criteria that would allow a proposal to be valid under 3.2.2 that could be used to meet this objection criteria ("a Proposal is always valid regardless of the preceding criteria if it is made solely to help evolve the Circle’s Governance to more clearly reflect activity that is already happening")...  That said, I've never seen that nuance actually matter, and it's much simpler to ignore that potential and assume it'll be caught by other arguments until proven otherwise, so I'm going to ignore this and make the change suggested...

Thanks!
- Brian
