### ISSUE TITLE
A little tweak at Section 3.2

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#141]
I would suggest to mention _in this Article_ instead of _in this Section_ at the end of the second sentence of Section 3.2, as the criteria are not defined in this Section but later at Section 3.2.4 in the same Article.

**_3.2 Changing Governance**

Any Core Circle Member of a Circle may propose changing its Governance, thus making a “Proposal” as a“Proposer”.

Before a Proposal is adopted, all Core Circle Members must have the opportunity to raise Tensions about adopting the Proposal. Each Tension so raised is considered an “Objection” if it meets the criteria defined **in this section**, and the person who raised it becomes the “Objector”._

**Comment by brianjrobertson** [comment]
In this case, I think §3.2.4 is within §3.2, since it's a sub-section, so it works better as-is.  Just to verify my thinking: does anyone else find this confusing?

**Comment by bernardmariechiquet** [comment]
Brian, I get your way of thinking. But, in all the document, what you call a _sub-section_ is referred as a _Section_. If you would change all reference to §x.y.z as _Sub-Section x.y.z_, then it works.
§x = Article
§x.y = Section
§x.y.z = Sub-Section

**Comment by brianjrobertson** [comment]
Yes, I know, and I wouldn't call it a sub-section in the document - that would feel weird, as it's only a sub-section in relationship to its containing section (like how a circle can also be a sub-circle in relationship to another, but it's still a circle by itself, and calling it a sub-circle everywhere just because it happens to not be the anchor circle would be confusing)...

**Comment by MiekeByerley** [comment]
I think it is better practice to be explicit in referencing. So instead of stating: 
- "Before  a Proposal is adopted, all Core Circle Members must have the opportunity to raise Tensions about adopting the Proposal. Each Tension so raised is considered an “Objection” if it meets the criteria defined in **this section**, and the person who raised it becomes the “Objector”
- Before a Proposal is adopted, all Core Circle Members must have the opportunity to raise Tensions about adopting the Proposal. Each Tension so raised is considered an “Objection” if it meets the criteria defined in **Sub-Section 3.2.4**, and the person who raised it becomes the “Objector”

This consistency removes ambiguity and aids in locating relevant information (increasing comprehension) without causing undue confusion or searching.

So I agree with @bernardmariechiquet here, and would add the explicit numerical location (like geographical co-ordinates) of the reference, so as described below:

§x = Article  e.g. Article I
§x.y = Section e.g. Section 1.2
§x.y.z = Sub-Section e.g. Sub-Section 1.2.2 
§x.y.z(a) = Clause e.g. Clause 1.2.2 (a) and Clause 1.1 (b)

**Comment by brianjrobertson** [comment]
I'm trying to remove all references to specific section numbers, as that dramatically decreases the usability and readability of the document, and ups its perceived complexity.  In many cases "in this Section" is harmless ambiguity or has an obvious interpretation; where it's not, I'm attempting a broader refactoring to remove the need for more clarity in lieu of adding section references.  I've got another issue queued up for that, so I'm dropping this one.
