### ISSUE TITLE
Add default mechanism for spending authorization beyond Lead Link approval

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#142]
I'm consider adding the following as a default mechanism for getting spending authorization of a circle's resources/budget, so that "Lead Link decides" isn't the only default answer anymore.  We've tested this app in H1 for awhile, and I'd say the results have been excellent.  Thoughts/concerns?

Here's the text (in Policy/app form at this point):

> As a Partner, you may spend money or other fungible resources controlled by a Circle as follows:
> 
> Before you commit to the expense, you must explicitly announce your intent to spend by stating "As [Role], I intend to spend [amount] on [good/service/purpose]".  You must post this in written form to a standard communication channel accessible by all Circle Members of the Circle and any Sub-Circles.  You must then allow a reasonable timeframe for others to consider the potential expense before proceeding.  During that time, you must answer any clarifying questions and consider any reactions shared about the potential expense, and any Partner may block your ability to proceed with the spending by escalating the expense for additional consideration.  Once escalated, you may get spending authorization directly from the Circle's Lead Link, or via any process defined by the Circle for assessing escalated spending intents.
> 
> To use this process, the spending must clearly support the Purpose or Accountabilities of a Role you fill in the Circle, or in any of its Sub-Circles.  You must also make the spending decision without interference from a personal conflict of interest or a blurred boundary between the Role you name and other Roles you fill.  If another Partner might have reasonable doubt about whether such a conflict is present, then you must call out that possibility when announcing your intent to spend, and explain why you believe it's not the case.
> 
> In addition to authorizing specific expenses, you may also use this process to authorize another Circle or Role to control some of this Circle's resources, thus granting it a budget.  It may then control that budget without further authorization from the original Circle, as long as any spending is aligned with the purpose specified in the original authorization.  Any budget so delegated may later be reduced or eliminated entirely using this process in the original Circle, or by a decision of that Circle's Lead Link.
> 
> Another Policy in this Circle may further constrain or expand upon the process defined herein, and any conflicts will overrule this Policy.  A Sub-Circle may also constrain or expand upon this process, however any additional spending powers or relaxed constraints only apply for spending resources controlled by that Sub-Circle and its own Sub-Circles.

**Comment by bernardmariechiquet** [comment]
I like the idea of having per default other than "Lead Link decides".
For me the last paragraph beginning by "in addition..." creates some confusion as written. It refers to kinda delegation authority whereas the first part is about authorization for spending. It look like there are two different things.

**Comment by Roflcopterpaul** [comment]
I think this idea is great. The more default options that support the end-goal (such as level 4 on the maturity map) will help support these practices right from the start. Here is an idea on how to word that in a much simpler way:

**"Any Partner may utilize or allocate resources of the Circle by explicitly announcing his/her intent to spend and all relevant details of the spending to his/her Circle using all the same rules and processes of an asynchronous Governance Proposal, as defined in Section 3.2.1. If this request is escalated, the spending may then only be approved by the Circle's Lead Lead, or using a defined alternate means of enacting this authority over the Circle's resources."**

It's insanely short without many checks and balances built in, but I think any other concerns can be covered elsewhere in the Constitution. Here's my specific thoughts:
1) Duty of Transparency can always be lengthened to be transparent about even more, such as intent, what Role you are making a decision from, answer to any clarifying questions, etc. (I'll throw up this suggestion as a separate topic). This takes care of all the information you need to provide, as anyone can ask and get that information.
2) By linking it with the asynchronous process, it covers all the necessary steps and let's Circles more easily dictate how that process works. As in, if my Circle automatically adopts proposals after 2 days, we would automatically accept resource requests after 2 days as well. Also, there's chances for clarifying questions, objections, escalation, etc.
3) A lot of the wording in here seems like it isn't totally necessary, with the mention that it has to support the Role's/Circle's Purpose/Accountabilities. This is usually going to be the case, and with a more peer-based system, others in the Circle will likely escalate it more regularly if they feel it doesn't have anything to do with the Circle's direction.

**Comment by brianjrobertson** [comment]
Interesting idea Paul, I’ll reflect and consider further - and thanks for the wording suggestion!

**Comment by karilen** [comment]
I like having lead link default for resource allocation because it is simple and requires little to nothing to implement FWIW so I think the option for a more distributed starting point could make sense.

**Comment by brianjrobertson** [comment]
To do:  Expand the part of this policy that allows delegating budgets to also allow granting loans with expected pay-back, so roles/circles can fund each other's initiatives via a loan in addition to a grant.

**Comment by bernardmariechiquet** [comment]
I think we should reverse the default options mechanism. Like @Roflcopterpaul I do think that the more default options that support the end-goal (such as level 4 on the maturity map/self-management) will help support these practices right from the start. If not they may push forward quite the opposite. For example, when encoding the initial structure, I've seen new Lead Links having more authorities they previously had as managers before adoption. And that is because, they struggle with this new kind of structure/concepts and not enough mental energy to embrace both learning the new tool and reflecting at what they really want the organization to be transformed towards. I do think most of the default options embedded into the constitution should support self-management the most accomplished and that it is preferable during initial encoding to consciously reduce self-management capacities already embedded than the reverse. So i wouldn't go for Lead Link default option as it already is, but rather would opt for this new app you're referring to @brianjrobertson which is similar to the one used by several teal organizations i know.

**Comment by brianjrobertson** [comment]
I just submitted one possible solution for this, which shifts spending control away from Circle Lead and to the announcing-intent process.  I'd love to get some more eyes on it though; anyone willing to help?  I’m specifically concerned that “whatever Circle has the right to spend the money or assets you intend to spend” in this new version of §2.1.3 may be confusing; it’s clarified in §4.2 that the Anchor Circle holds this authority, but that’s well after 2.1.3.  Is that clear enough, or should the definition of Anchor Circle get moved to Article 1, or something else?  Any other issues you can find?

**Comment by chrcowan** [comment]
@brianjrobertson What about just including a cross-reference _to_ 4.2 _in_ 2.1.3?

**Comment by brianjrobertson** [comment]
Currently there are no section references anywhere in the dev version of the constitution, and I'd like to avoid adding any back - *especially* forward references.

**Comment by chrcowan** [comment]
@brianjrobertson ^^^ Why?

**Comment by brianjrobertson** [comment]
@chrcowan It makes the document harder to read and more intimidating and complex to an average reader; it's also often a sign something in the organization isn't requisite or simple enough.

**Comment by chrcowan** [comment]
@brianjrobertson Yeah gotcha. Maybe then I'm thinking of another version of the constitution which could or should use cross-references to make it easier to identify the linkages between particular sections. Maybe something for the desk reference. 

I'm thinking of cases in which different people look up the same rule, but for different reasons, and for some of those reasons, it would be really helpful to have a cross-reference. No response needed. Just writing to think.

**Comment by ebabinet** [comment]
I read the section and it seems clear to me except for this sentence "...or wait for other Roles to gain the right to spend from your authorization using this same process." Why is this clause needed? Is this referring to Roles within the sub-circle of my role? If so, it's not clear, and otherwise I'm not sure why roles would be gaining the right to spend from my authorization as opposed to just getting their own authorization to spend from the circle money/assets.

With regards to moving the Anchor Circle description to section 1, I think that's not absolutely necessary for clarify of this section, but would be an overall improvement as its an important part of the organizational structure.

**Comment by LouisChiquet** [comment]
It's wrote “_While energizing your Role, you may not spend any money or dispose of any significant property of the Organization, nor may you significantly limit any rights of the Organization, unless you are explicitly authorized to do so_”, given the way it is redacted, I consider this to be rather clear.

For [Article 4.2](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#42-anchor-circle) however, I'd just add what's in bold maybe to make it more clear? “_Unless otherwise specified by the Ratifiers **or the enacted Governance**, the Anchor Circle automatically controls all Domains that the Organization itself controls, and has all the authority that the Organization itself has, including authorities to dispose of the Organization's property, limit its rights, and spend its money._”, so like this “it's sure”.

**Comment by margauxchiquet** [comment]
Hi, I think it is my first comment on GitHub :)
I was puzzled by that change when you talked about it during your talk at the forum Brian.
I have some concerns..
1/ When I asked you why you did this, I understand you said it was mainly because you did it at H1 and thought it was a good way to remove that from the Lead Link. On our side, we haven't tried it with real organizations, clients with employees that don't have the level of maturity we have. IMO there is a potential danger here because if we take our type of clients, you can't ask someone at the hotline to have the consciousness to take that decision, that's not what it required of them. I like the “go to teal” but is it really the goal of the constitution? I think it is going into a direction that forces the organization to move towards teal instead of being a management system, neutral and organization can then build teal on top of it, or not, their choice.
2/ I like the default process of Lead Link deciding because it is one of the competency of a manager/leader - know what and when to spend, managing the budget of the circle

If it stays as is, we would have to encode a lot of policies and stuff when crafting the initial structure because it is not the way the organization works at first.
I would say they can ask for a spending of autorisation and the Lead Link has to object: saying why it causes harm, that would be a middle solution.
Why they intend to spend that money is also important, not only the amount and role it comes from.

I don't have a concrete solution, for now I am trying to digest this and open to discuss about the philosophy and concerns I have. Is it shared by anyone else?

My fear is that we are trying to replicate stuff we do as organization trying to reach teal but it is not grounded IMO on clients practicing Holacracy and I may be wrong :)

**Comment by brianjrobertson** [comment]
@ebabinet, re:

> I read the section and it seems clear to me except for this sentence "...or wait for other Roles to gain the right to spend from your authorization using this same process." Why is this clause needed?

I just removed it and reworked the text around it a bit; I think it still works.

**Comment by brianjrobertson** [comment]
@margauxchiquet , re:

> I would say they can ask for a spending of autorisation and the Lead Link has to object: saying why it causes harm, that would be a middle solution.

Seems to me that would actually be going a lot further than what I've got in the dev version now, not in the middle.  With the current dev version text, a Lead Link can still completely control spending - they can simply escalate any spending intent to stop it, and need not offer an objection.  The only real new restriction here on Lead Links from v4.1 is that the Lead Link has to also publish their intent to spend or to authorize other roles to.  Beyond that, from a Lead Link perspective, it works exactly like it does in v4.1 if you want it to: you can simply say "escalated" to a spending intent in v5.0, just like you can say "no" to a spending request in v4.1; it just requires others to ask you by publicly stating intent, instead of going to you directly one-on-one.

> Why they intend to spend that money is also important, not only the amount and role it comes from.

Agreed; I'll add that.

**Comment by Lisa09h** [comment]
Hi Brian, our organization is at the moment setting up Holacracy and we are also at the point to ask ourselves how to deal with budgeting. Since your approach sounds really good, would it be possible that we schedule a phone call and you tell me briefly about how you did it exactly? Thank would help us a lot :)
Best,
Lisa

**Comment by chrcowan** [comment]
@Lisa09h 
You can find some information on this by looking at HolacracyOne's Glassfrog (e.g. [the base spending policy is here](https://app.glassfrog.com/policies/1499644)). 

But I'm also working on putting this information together into an "app" which would make it easier to share and I'd be happy to discuss it with you. It may help me improve how I go about packaging the information. You can email me at chris@holacracyone.com
