### ISSUE TITLE
Rename "Core Roles" or "Core Circle Members"

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#149]
The use of "Core" in both "Core Roles" and "Core Circle Members" has confused some people as thinking this is the same/similar concept, when it's really not.  Any ideas for an alternative term for one or the other?

**Comment by bernardmariechiquet** [comment]
What about "Structural Roles" for "Core Roles"? As these roles happen via & for the structure.

**Comment by ebabinet** [comment]
What about "Required Roles" for "Core Roles" as those are the only roles
that are constitutionally required? I would say that all roles are
structural, so I don't like "Structural Roles"

**Comment by bernardmariechiquet** [comment]
I would then suggest Core Structural Roles

**Comment by bnritya** [comment]
Do you like 'Anchor Roles' instead of Core Roles?

These roles anchor the circle 

Beena

**Comment by tylerdanke** [comment]
I found it interesting that Core Roles is not mentioned in the Constitution and was very difficult to find any reference to this.
Core Roles:  What is the biology metaphor word for it? Membrane? makes sense for especially for Lead Link and Rep Link Nucleus? Seems to make sense especially for Facilitator, Secretary and Lead Link. Some from traditional organizations would be Executive. Because core roles are so well defined I believe that it would be appropriate to use Executive obviously in a different sense than in a traditional organization. I would recommend that you not use core here.

for Core Circle Member: I believe that it would be more clear to designate someone as either a Minor Circle Member or Core Circle Member.

**Comment by rebeccabrover** [comment]
Perhaps Constitutional Roles as they are are the roles required by the Constitution. Other Roles are just Roles. This then leave Core Circle Members intact as that certainly makes sense as compared with Other Members (in GlassFrog for example). It seems like it would be easier to explain.

**Comment by julianeroell** [comment]
I like "Required Roles" (quite a bit) and "Constitutional Roles" (a bit less). I have also heard myself say "Holacracy Roles" sometimes (which is ugly :)).

"Core Circle Members" works for me.

**Comment by brianjrobertson** [comment]
"Core Roles" was apparently already removed from the constitution as a defined term, and no replacement is needed...  :-)
