### ISSUE TITLE
Lead Link Permissions: Lead Link may change Roles only by using Governance process

### ISSUE THREAD

**Issue by cristiandodita** [holacracyone/Holacracy-Constitution#153]
During dG Holacracy Training I learned that the Lead Link, like every other member of a circle, is supposed to propose changes to an already existing role by addressing this as a tension in the circle's governance process. This is obviously the way it should be, since everybody including the trainers agreed with it.
The tension I have with it is that in constitution 4.1.4.de and 4.1.en there is no clear mention of this restriction of the Lead Link permissions and accountabilities. Since the Lead Link has the accountability to initially create the circle's roles, this may cause misunderstandings and unproper implementation if not solved.
My proposal is to enlarge/adapt the Lead Link Role definition by adding a clear specification of the way the Lead Link is permitted to change the Roles of the Circle, that is: The Lead Link may change Roles only by using the Governance process, as any other Role of the Circle does.

**Comment by pscheuerer** [comment]
I think the constitution is pretty clear on this.

In 2.1.1 it is clearly stated that:

Each Circle will use the “Governance Process” described in Article III of
this Constitution to define or amend Roles within the Circle or Policies
governing the Circle’s Domain. *No one may define or amend a Circle’s Roles
or Policies outside of its Governance Process, unless explicitly allowed by
another rule of this Constitution.*

The point you are raising about the lead links authority to create the
initial circle structure is also addressed in 5.3:

The Lead Link of the Anchor Circle may define an initial structure and
other Governance for the Organization, outside of the usual Governance
Process required by this Constitution. If that initial structure includes
any other Circles, the Lead Links of those Circles may do the same within
their Circles. *This authority may only be used to define an initial
structure for a Circle to start from, before the Circle has begun
conducting its Governance Process.*




Am 18 February 2017 um 11:12:34, cristiandodita (notifications@github.com)
schrieb:

During dG Holacracy Training I learned that the Lead Link, like every other
member of a circle, is supposed to propose changes to an already existing
role by addressing this as a tension in the circle's governance process.
This is obviously the way it should be, since everybody including the
trainers agreed with it.
The tension I have with it is that in constitution 4.1.4.de and 4.1.en
there is no clear mention of this restriction of the Lead Link permissions
and accountabilities. Since the Lead Link has the accountability to
initially create the circle's roles, this may cause misunderstandings and
unproper implementation if not solved.
My proposal is to enlarge/adapt the Lead Link Role definition by adding a
clear specification of the way the Lead Link is permitted to change the
Roles of the Circle, that is: The Lead Link may change Roles only by using
the Governance process, as any other Role of the Circle does.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/holacracyone/Holacracy-Constitution/issues/153>, or mute
the thread

**Comment by brianjrobertson** [comment]
I see that an update could potentially help avoid this misunderstanding, however the goal of the constitution is minimal sufficiency, not necessarily avoiding every potential misunderstanding, and I agree with Patrick above that this is already clear enough.
