### ISSUE TITLE
Focus objection criteria #4 to exclude objections based on resource constraints

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#174]
I'd like to focus the last objection criteria to something like “Does it limit your ability to express your role’s purpose, even if you had no other roles” or similar, to avoid some objections based on resource constraints from filling multiple roles or being in too many circles.  Alternatively, this could perhaps be achieved by focusing in on just assessing for harm that would be caused “while you’re actively energizing the role” or similar, for the same effect.

Note:  These potential solutions need more consideration and testing...

**Comment by brianjrobertson** [comment]
A good solution for this could also cover the need to more clearly disallow objections like this (at least without further clarity required):  "Because it won't be convenient for me personally to follow these rules, it will affect my performance in the roles I fill. I know that from experience".

**Comment by chrcowan** [comment]
I really like the question, "Does it limit your ability to express your role’s purpose, even if you had no other roles?" but not sure you need to further define the criteria, since it already says it needs to be from one of the Objector's roles. But I suppose further clarification may help.

**Comment by bernardmariechiquet** [comment]
If you go in that direction, I would recommend to not forget after "Does it limit your ability to express your role’s purpose" "... or your roles's accountabilities".

**Comment by LouisChiquet** [comment]
I like, seems like there may be something about testing for the “we don't have the resources/the finances/the energy” (with some exceptions naturally), which for the moment need some coaching to be lifted. Maybe there is a global testing question about resources?

Something totally crude, but in the idea (if there is really concrete needs behind it naturally, and it's far from being mature): “Would this prevent you from doing your work properly or do you think we don't have the energy/finances/resources for that?”

**Comment by brianjrobertson** [comment]
I'm going ahead with this change and submitting it.  And, an important note: I'm also removing the ability for an objector to be representing another role with that role-filler's permission.  My sense is this was a rarely-used clause to begin with, and now it's possible to make someone a Role Supporter and let them then represent a role as a Rep Link, so I believe the rule that you can represent another role with permission (without serving as a Role Supporter) is just extra complexity now and not needed.  Please challenge me if you disagree...

**Comment by chrcowan** [comment]
@brianjrobertson One concern surfacing for me is how to handle being absent from a meeting, especially early on, and I have a sense that being able to tell people, "you can always ask someone to represent your role for that meeting," really helps move their understanding along (even if it's rarely used...which I think might be because that rule works so WELL on the paradigm shift; i.e. taking responsibility for my role, that it's application is rarely needed. (asking my neighbor to clean my kitchen vs. finding him doing it). 

I understand that this might be captured in a new way (the same function just described differently), but I really like the simplicity of it as compared to having to give it a label like role supporter. And to that end, maybe it's actually not extra complexity, or rather, if the goal is to make things simpler, then some technical duplication might actually be called for because, in effect, it actually makes things simpler for the user/reader because relevant terms or constructs are organized thematically. 

Just some spontaneous ill-formed thoughts.

**Comment by brianjrobertson** [comment]
Thanks @chrcowan, I appreciate those thoughts, and resonate with the importance of something easy to say there.  Though, I think we can still find something easy to say and true-enough; like, "you can just assign someone else to represent your role" - which is true enough, even if it lacks some nuance/details.
