### ISSUE TITLE
Clarify how testing proposals works and who can do it

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#193]
The testing proposals section references that Facilitator can test proposals, which is vague/confusing as there isn't a specific testing process, and anyone can ask clarifying questions to effectively test the proposal.  It should also be clear that “unspecified” in answer to such a CQ fails to pass the required threshold.

**Comment by bombino** [comment]
Additionally, under 3.2.3 Testing Proposals, the requirement to give an example of an actual past or present situation in which the Proposal would have reduced that Tension and helped the Circle seems to disallow many actions a Lead Link would take under their Appendix A accountability for "Structuring the Governance of the Circle to enact its Purpose and Accountabilities."

For example, as Lead Link of a circle at Action Verb, there is an accountability on one of the roles in the circle that I would like to remove, because it is clearly counter to the Purpose and Accountabilities of the circle.  However, since I cannot give an actual example of a past or present situation, I have not been able to remove the accountability, and I believe that the circle is harmed by this situation.
