### ISSUE TITLE
Rename Domain to Property?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#196]
I describe "Domains" as "Property" every single time I explain them to Holacracy novices; that makes me wonder whether renaming Domain to Property would help.  Any thoughts?

**Comment by rnicholus** [comment]
I'm not 100% sure that property is the best term (it may be), but I do agree that domain seems overly abstract. So, property is an improvement in my mind. Another option: "possession". But perhaps that is a bit too informal?

**Comment by braincat** [comment]
My encountering difficulty is which should be defined or discovered first in an organization if it wants to practice Holarcracy. Roles or Domains? Many would easily interpret Domains as the functional boundaries of what the people do. Roles are their identities in an organization. It would be greatly helpful to get these two concepts more concrete and easily to be distinguished.

**Comment by bernardmariechiquet** [comment]
I would pitch for "Property" unstead of "Domains" - I describe this concept by using property too

**Comment by KoenVeltman** [comment]
I also prefer property over domain. As the word domain is hardly used in everyday language outside of Holacracy. 

Koen


Koen Veltman
+31620835076

**Comment by gvandegrift** [comment]
I'll be the odd man out.  I prefer domain.  Property is overly concrete.  "Role assignments within the Circle" is hardly a tangible piece of property.  However, domain describes it quite nicely.

**Comment by bombino** [comment]
A Domain can refer to classes of things where some exist now and others will exist in the future.  For example, a domain held by the Corporate Entities role for "Documents Filed with the Secretary of State."

Using the word Property to me potentially loses clarity that this domain refers to not just currently filed documents, but also any document that might get filed in the future.

**Comment by julianeroell** [comment]
I prefer "Domain" over "Property". To me, "domain" has connotations of "stewarding" (I steward a domain), whereas "property" connotates with "holding on to" (I hold on to a property). 

As I think of my Roles' Domains as _the organisation's property_, not mine / my Roles', I would find it very awkward if this was changed.

**Comment by MiekeByerley** [comment]
I have the exact same issue as Martina. One of the major shifts that
Holacracy has been able to achieve is this degree of separation between
what is attributable to the Personhood of the Role energizer, and to the
identity of the Organization. Also for me it seems regressive as
HolacracyOne diligently sought to ensure through its own Operating
Agreement to Shift from Human Ownership to Purpose Ownership, the
constitution made it possible to make this step and make it concrete
through this very foundational element, changing this would have a
challenging flow though implication.

Another interesting perspective to consider is that Property is an
objectification of resources, in other word it sees all resources as
"Things" which are controlled over. Now domain however does not insinuate
this, it is more akin to the concept of Realm and encompasses both animate
and inanimate, as well relational, and collective intelligence, it also
works with influence/sway not control.

In my humble opinion it is a dangerous precedence, to which I would add a
reminder that today's business/corporate language will not suffice for the
Organizations who are Pioneering alternative Organizational Paradigms.
Beware to regress to the language (and its understood forms) of the
preceding Organizational Paradigms, as comfortable and common as it might
be, it will undermine the intent.

Please feel free to reach out and connect, or schedule some time here:* MeetMe
<https://beta.doodle.com/mieke_byerley>*

Mieke Byerley
*Human Centric Organization*

*LinkedIn Profile <https://www.linkedin.com/in/miekebyerley/>*

**Comment by braincat** [comment]
After looking through the entire thread up to the moment, and referring back to the definition of "Domain" in the Holacracy glossary, I would say there are two dimensions of its meaning being implied; 1. to "decompose" the organization from the multiple viewpoints (asset/information, function, process, etc.); 2. to achieve the role ownership/accountability if applied. In that sense, "Property" may be recognized about how an Organization is defined or described. It is the organizational viewpoint. "Domain" is closer to the role's viewpoint about what a role owns or is accountable for. Therefore, I am inspired that I will use either of "them" based on my purposes and audiences.

**Comment by cassus** [comment]
Domain has been problematic for all new people around me.
I'd go even simpler and replace the world with _Guards_ or rather even _Fences off_, that conveys the meaning to new audiences much better than Domain.
Since the language of Holacracy is still quite abstract and legal-ish, I believe the change to _Property_ could be a small step in the right direction.

**Comment by brianjrobertson** [comment]
@braincat:  I'm not sure what you're referring to re your first point there; that's not what Domain is for in Holacracy, it's only the second point.  i.e. Domain is not for breaking down functional focus or accountability, just for fencing off "stuff" that others aren't allowed to impact.

The problem with "Property" I see is that the "stuff" can be very abstract, as @gvandegrift and @bombino point out - that's the main reason I didn't change it in the v4.0 to v4.1 upgrade.  I also resonate with @martinaroell's point.  Yet I've seen so much confusion that I'm second guessing myself on keeping it Domain; it's so easy for people to think that's meant to be used to capture a functional breakdown or the areas a role focuses in, which totally breaks a key aspect of how Holacracy works.  So I'm wondering if the switch to Property, while not ideal, will cause less harm than the current language.  I'm not convinced that's the case (hence framing this Issue just as a Question), but that's what I'm exploring: which harm is worse?

**Comment by cassus** [comment]
When learning it's easier for most people to start at the specific and later go to the abstract, so I'd go with _Property_ and stretch that metaphor when we need to.

I'd choose _easy to learn_ over _logically accurate_ in this case.

**Comment by MiekeByerley** [comment]
Agree that from a training perspective and a formation perspective the
language may not be the easiest, just like the rest of the Constitution.
But then I was under the impression that the Constitution is not intended
as the training material or the Study guidelines, but rather the stake in
the sand of the final destination.

We need to remember the Purpose of the Constitution, also what the function
is of a Codified Constitution. Remembering that in most but not all modern
states/countries the constitution has supremacy over ordinary statutory law
<https://en.wikipedia.org/wiki/Statutory_law>. Hence the Legal language
slant.

What I feel like is happening is that members sense a gaping Tension in the
training, formation, especially language understanding and transmission of
Holacracy. Which is NOT the Purpose of the Constitution to address. This is
not a new challenge nor is it isolated to Holacracy, as I have been seeing
it and working with in the wider ecosystem of the Reinventing Organization
and Future of Work already for the past 3 years.

Instead of trying to get the Constitution to meet a sensed need it is not
designed to to meet. I see this as an opportunity for HolacracyOne and its
Partners to develop a separate solution specifically with the Purpose to
address this very noticeable tension.

It is precisely our prerogative to ensure that Coaches etc. have the
thorough understanding to be the Translator/Transposers in this situation,
that is precisely their function. Nobody ever said it was going to be easy,
ask any kindergarten Teacher about the challenges of teaching Children how
to read, write and comprehend., or ask any Foreign Language Teacher the
challenges of teaching a secondary language to a student.

There has been an extensive concentration in teaching/mentoring/coaching
people in new methods, practices and habits (in the whole ecosystem), but
we have been assuming that everyone understands the New Language that is
necessarily and intrinsically associated with the frontier of pioneering
work. You can't teach Chinese language concepts by reverting back to
English, anymore than you can teach the new concepts by reverting back to
the Old Corporate or mainstream language, in the long run you will create
more, confusion, misunderstanding and risk the integrity of the new
concepts.

We also know from decades of experience that dumbing down education to the
lowest common denominator (to combat failure rates, and foster inclusion
and accessibility) does not work, it simply ends up falling short through
inadequate preparation for the real world, and even increases failure
rates. What is needed is better ways to educate, and transfer the necessary
capabilities for people to succeed and thrive.

I think we need to take a longer term perspective of what is trying to be
accomplished, especially if it means that the Short term payoff is going to
be necessarily painful and challenging. Others can choose to walk away from
this but as coaches etc we can't shy from this discomfort, if we do we have
no hope in convincing others to stick with it.

I am speaking as one who has no access to Holacracy Training, I had to
utilize self-directed study to become a Certified Holacracy Practitioner.
There are no known Organizations running on Holacracy (constitution) and
currently I am not sure how many here hold any form of Certification (there
was at least a handful plus one coach at one point). In other words how is
it even meant to spread here, the bar to to entry is set so high that for
those who are in locations where there are no (physical resources) Licensed
Holacracy Providers, Certified Coaches or Holacracy Organizations it is
nigh impossible.

Please feel free to reach out and connect, or schedule some time here:* MeetMe
<https://beta.doodle.com/mieke_byerley>*

Mieke Byerley
*Human Centric Organization*

*LinkedIn Profile <https://www.linkedin.com/in/miekebyerley/>*

**Comment by julianeroell** [comment]
> I'm second guessing myself on keeping it Domain; it's so easy for people to think that's meant to be used to capture a functional breakdown or the areas a role focuses in

I have met that misunderstanding too, but found it easily coach-able. It sometimes creates quite an "aha" moment when people realise that actually, unless otherwise specified, the whole company is "their domain" (and everybody else's). That they do not _need_ to specify "their domains" of responsibility & control, but can use accountabilities for that, thus making a positive, opening affirmation of "you can expect me to take care of this" rather than a closing statement of "this is _my_ area, not yours". And that, in all that openness, they _can_ specify areas of control if they need to.

At the same time, maybe a different word could be found that makes it clearer. I think I lack the English to find something sharp, but could something like "Area of Control", "Control Sphere", "Protected Sphere", "Preserve", "Control Domain", "Protected Domain", "Protected Area of Influence" (PAOI 😺) or so work? 

(I am just brainstorming here. For me, "Domain" is short and clear and I'd rather have a bit of teaching effort to clarify what "Domain" means _in Holacracy_, rather than have a murkier word. But I'm open to finding something else that also works.)

**Comment by chrcowan** [comment]
I like "Property" better. FWIW. For reasons already mentioned.

**Comment by diederickjanse** [comment]
For outsiders and new adopters, the language of 'domains' gets misinterpreted a lot. They often interpret it in the more usual and general meaning of the word (realm/range/scope), rather than the very specific and distinct meaning in the context of Holacracy (property).

For more mature practitioners, domain works better than property because it's more inclusive not only of objects and assets but also of processes and other more abstract types of domains.

So, which do you want to preference here, outsiders/new adopters or mature practitioners? Not quite sure myself.

I wonder if using 'property right' as opposed to 'property' makes any difference to the feel of it? It does to me, I like it better.

**Comment by brianjrobertson** [comment]
Thanks Diederick, that's a really helpful distillation; anyone have thoughts on "Property Right", as well as whether to privilege new adopters vs. mature practitioners with this word choice?

**Comment by jonioverbosch** [comment]
In my opinion (for what it's worth) Domain is the better choice for the reasons Diederick mentions above for the more mature practitioners (more inclusive). 

When I look at definitions:
Domain: an area of territory owned or controlled by a particular ruler or government. 
Property: a thing or things belonging to someone; possessions collectively

A Domain in Holacracy is something " given to a role or circle in order to give it exclusive control of that resource". So the Control aspect is something I associate with a domain, not with property. 

Besides, the explanation of what a Domain is, is very clear in the Holacracy documentation, and I think new adopters can't expect to understand everything without some reading or study. Btw, I put myself in the class of new adopters.

Please ignore if I don't make any sense.

**Comment by gvandegrift** [comment]
I would favor "correctness" over ease of learning.  Therefore, I would favor the more mature practitioners.

FWIW, not really a fan of Property Right.  That seems more confusing.

**Comment by julianeroell** [comment]
"Domain" is still my favourite (preferring continuity over something new, and being generally comfortable with the word, as I explained above), however "Property Right" would also work for me, and IMO is an excellent improvement over "Property" (which I think is misleading).

**Comment by bombino** [comment]
Building on jonioverbosch's comment, I had this new name idea:  "Controlled Resource."

The role holding the domain can be called the Controlling Role.

The key piece that "Property" or "Property Right" seems to lose for me is the fact that the domain is in many cases still accessed/edited/used by other Roles, it's just that some controlling role has the rights to control that access.

... though after more thought (editing this comment), I think I still prefer "Domain" for brevity.

**Comment by gmitterer** [comment]
I like the thread and ideas and building on @diederickjanse distinction I would argue for a name that is general enough to include not only objects/assets but also processes and other more abstract types of domains. I wonder if not a similar wording now used to define a domain would be easier to understand: "exclusive control" or "exclusive authority" or "exclusive access".

**Comment by diederickjanse** [comment]
I like that we're thinking about this thoroughly, and yet stepping back and re-reading this thread I would probably stick with Domain for now. Since changing the term would itself introduce confusion, I would argue that a new term would have to be significantly more clear to make it worth our while. Not sure that I've seen any options that pass that test (including my own suggestion of 'Property Right').

**Comment by julianeroell** [comment]
"Controlled Resource" is the best I have heard so far. This to me is intuitively clear on first hearing. It is also extra helpful in that by introducing the concept of a "controlled resource", this makes it clear that all other resources are "not controlled" (circle property, available to all).

**Comment by brianjrobertson** [comment]
Interesting...  Controlled Resource is definitely better than any other idea I've had or seen, at least from my perspective, but to Diederick's point I don't know if it's good enough to justify replacing Domain.  I do appreciate @martinaroell's point as well about the implication of other stuff being "not controlled".  I do wonder if the "resource" part could be problematic though and give the wrong idea about what these can be...

**Comment by MiekeByerley** [comment]
Very Interesting String.

A point I would like to highlight from the conversation here. It still
intrigues me that we are referring to these terms (looking at them) through
the perspective of Teaching and Learning.

*What is the PURPOSE of the Constitution?*

Is it for the purpose to educate and teach (which in all HolacracyOne's
statements it is not to be used for), or is it to define the completed
implementation (so the end state) of Holacracy. My difficulty with many of
the recommendations and discussions (not just on this topic) is that they
come from the purpose perspective of Educating and Teaching rather than the
Purpose of Defining the END State (Implemented Purpose = Vision). Remember
Holacracy Constitution adoption is not the first step in the adoption
process but the LAST.

BY confusing the Purpose focus of the document, you are running the risk of
serious misalignment, confusing audiences, and watering down it's impact
and role.

I have mentioned it before in this string but I still don't think this
issue is being addressed, even being skirted.

Please feel free to reach out and connect, or schedule some time here:* MeetMe
<https://beta.doodle.com/mieke_byerley>*

Mieke Byerley
*Human Centric Organization*

*LinkedIn Profile <https://www.linkedin.com/in/miekebyerley/>*

**Comment by brianjrobertson** [comment]
@MiekeByerley While it's true that it's not meant as a stand-alone educational/training document, adopting the constitution actually is the first step in the adoption process, not the last.  The adoption process is really all about learning the rules of the new game contained in the constitution, so having a rulebook that makes for easier referencing while you're learning is really helpful.  So, it really needs to be somewhere between a pure reference for masters and a teaching tool for novices; like any good board game, you adopt the rules the moment you sit down to play, so it helps to have a friendly reference that's usable even for non-experts (even if you're learning to play with more seasoned players vs. just reading the rules)...

**Comment by gmitterer** [comment]
To me the "resource" part is misleading or at least creates again additional need for explanation. There I am with Diederick not to change it.

**Comment by LouisChiquet** [comment]
With the new way of access domain with [article 2.1.2](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#212-dont-violate-domains) “_Instead of asking for permission directly, you may also publish your intent to take a specific action, and see if anyone with a relevant Domain asks you not to within a reasonable timeframe_” which totally change the way to approach domain (and mindset in it in my opinion), leaving it more open to being affected by other roles, I think of an “**[attribute](https://en.oxforddictionaries.com/definition/attribute)**” (_A quality or feature regarded as a characteristic or inherent part of someone or something/A piece of information which determines the properties of a field or tag in a database or a string of characters in a display_) or “**assignment**”. For my part also agree on the fact that domain is more catchy (and I prefer it), however in order to feed the discussion, maybe there is just the need of time to distillate it further and it's not mature yet.

**Comment by tylerdanke** [comment]
In the real estate or automobile business the word "title" or "deed" seem to be what Holacracy currently would use to describe a "domain".

**Comment by brianjrobertson** [comment]
Just re-read this whole thread, and it's a close call for me, but after reflecting on everything shared above, I'm going to stick with Domain.  Thanks everyone who participated here - this was a really cool dialog for me, and it felt awesome to have this level of community support on this issue!
