### ISSUE TITLE
Rename Lead Link

### ISSUE THREAD

**Issue by tylerdanke** [holacracyone/Holacracy-Constitution#198]
As a person trying to suggest / sell/ recommend / teach about Holacracy to organizations that I am a part of or to others interested in at least talking about Holacracy:

I want universally understood role names at least at a basic level. I know that the roles and Holacracy will not be fully understood especially the nuances to it, but when we start using jargon like Rep Link and Lead Link, people have a harder time picturing what we are doing and shy away from wanting to adopt. 

**I propose that we change Lead Link to Leader and Rep Link To Representative.**

I know that every other role in the circle also are leaders as well however the Lead Link "leads" those other roles. I want Holacracy to be different and be better but I believe that we have an obligation to use common words to describe at least the basic concepts. I understand that the concepts of leader and representative are already there however we turn a lot of people away from our system when we use our own unique and specific jargon phrases.

I know that there has already been a lot of debate, thought and practice put into this but I feel compelled to at least make my pitch at least once. :)

**Comment by julianeroell** [comment]
I like the general direction of this. "Leader" is too strong for me (I don't see the Lead Link as "leading other roles" and find the cultural associations that come with calling one person "the Leader" unhelpful). "Circle Lead" would work for me.

"Representative" is very fitting IMO.

**Comment by tylerdanke** [comment]
Honestly even role names of just "Lead" and "Rep" I think would be good.

**Comment by gvandegrift** [comment]
Agree.  Lead Link and Rep Link sound awkward.  Also agree, though, that "Leader" or "Lead" is a little strong.  It really seems like more of a stewardship Role, so, while I don't actually like the sound of it, maybe something like "Steward" or "Circle Steward" is in order.

**Comment by MiekeByerley** [comment]
What about the term *Coordinator *instead of "Lead Link". If you look at
the account-abilities etc, then in essence the Function of a "Lead Link" is
to Coordinate the Circle (it is a form of Conductor-ship and much more
reflective of what the role is about including dealing with constraints,
alignment and linking. :)

Please feel free to reach out and connect, or schedule some time here:* MeetMe
<https://beta.doodle.com/mieke_byerley>*

Mieke Byerley
*Human Centric Organization*

*LinkedIn Profile <https://www.linkedin.com/in/miekebyerley/>*

**Comment by bombino** [comment]
+1 for "Lead" and "Rep" and dropping the word link.  With cross links going away, I think this is a good step in the evolution of avoiding weird jargon.

**Comment by bombino** [comment]
Actually, upon further reflection and providing internal coaching, one of my complaints about "Rep" is that it leads many people to think it means Reputation, not Representative, and therefore that it's somehow about "protecting the Circle's reputation."  So I now lean toward the full word Representative.

**Comment by brianjrobertson** [comment]
I worry that just going with "Lead" will make the power shift harder to achieve.  Anyone else have opinions here?

**Comment by ebabinet** [comment]
I do not think "Lead" is a good choice as it is too generic and hurts the
mindset shift of everyone being a leader of their roles. While having a
distinct term like Lead Link may create some initial awkwardness, it does
help to reinforce that this is something different than what people are
used to.

**Comment by karilen** [comment]
I don't think any of these issues are compelling enough, or ideas compelling enough to change from lead link and rep link. 

I think if Holacracy included more concrete descriptions of how to do lead link and rep link and some way of making explicit how "managerial functions" happen this would solve it. Even experienced Holacracy companies think that resources include people and time for example. If this people fusion could be clarified within Holacracy then it would help.

The only idea have read that seems possibly more neutral would be first link or purpose link and representative link. Not lead. Circle coordinator, circle processor, or Purpose link, or get rid of links and say Purpose Holder and Circle Representative.

**Comment by bernardmariechiquet** [comment]
I would propose Circle's Anchor for replacing LL, because LL is not just a Link. Moreover LL is the Role that anchors sub-circle into a circle. Or Anchor Link...

**Comment by LouisChiquet** [comment]
Upper and Lower Link, like in Parliaments/Houses, there's no particularly a hierarchy, just different roles (but again, Upper/Lower may be seen as a hierarchy symbolism).  I may say I like very much Bernard Marie's suggestion. But I suspect the #220 to also have an impact on the way to see the Lead Link as it's bringing closer to the new concept of Role Representative (which is a mix of the Lead Link and Rep Link role without fully having all the two roles activities).

**Comment by yiqing-he** [comment]
Generally I like the name "Circle Lead" as Bernard proposed, even though I still need to explain the nuances of "leading through influence within a special role" versus "leading by power from a given position".

I would suggest something like Circle Holder or Circle Steward, since LL unlike other links has a special purpose to hold the circle's overall purpose, and also has the accountability to steward the circle to unleash its purpose.  Externally, this role holds the boundaries and identity of the circle within the broader circle, and internally, it holds the clarity between roles within the circle.

**Comment by bernardmariechiquet** [comment]
I like Circle Holder from @yiqing-he 

IMO finding a name for what is called LL is hard because such job is holding so many different and key polarities for a circle to perform well.  Being a Lead(er) is one, but only one into many more.

 1- LL is mentioned mainly from a perspective inside a Circle. When outside such Circle, one would mention preferably the name of the Circle as a Role. So we're mostly looking for a name in such "inside a circle" perspective

2- LL is not (only) a Link, he has got accountabilities and other responsibilities defined per constitution which makes it weird to name it as a Link

3- The word "Lead" is interesting because LL inherits the purpose of the circle and should be able to enact/actualize such purpose kinda like a business culture of entrepreneur which is one the polarity we are looking for finding a good fit for LL role. But with new tools for enacting such business leadership - org. design via governance being one of the key polarities to be held by a LL.

LL has many polarities to embrace/hold, at least 4 : 
• one is the capacity to design the structure of the circle and this is completely new org. design skills formers business leaders may not/never get well enough to have a good fit here
• ability to get the best fit when assigning/re-assigning partners to roles - which is another skill/talent 
• defining relative priorities and allocating resources is the third polarity to be held by a LL
• embodying and holding the purpose of the circle (and sensing tensions from such lieu) being the forth polarity already mentioned above

In my experience, finding people having those 4 skills is hard, maybe find 4 different people to hold all these functions is easier and then create some new roles in lieu et place of some LL's functions. This is where we are with some of our clients having more than 3 years of practice.

I do think to have that in mind could help finding a new name for LL if any. Personally, I would go to what's the new part adding by Holacracy which the blend of business wisdom and culture with organizational design skills grounded in real tensions. The other polarities were already there in conventional ways of running the business should be easier to find.

So what about names like : Circle Link, Circle Root, Circle Anchor, Circle Design, Circle Holder, Circle Steward, ... or may better Anchor Link, Root Link.
Anchor Link is my favorite as it's kinda similar concept than the Anchor Circle established by the Ratifiers, it is the role by which power is granting into a circle, that gives birth to a circle.

**Comment by julianeroell** [comment]
"Circle Anchor" is my favourite fo far. "Link" never made much sense to me as a word/concept/metaphor. (I can see where it is coming from, but I don't find it so helpful, and difficult to explain to newcomers.)

"I am the Circle Anchor for (Circle Name)"
"Let's ask the Circle Anchor for a new Role assignment."
"John, can I make you Circle Anchor for (Subcircle)?"

"Anchor" is more neutral that "Steward" (which still has connotations of "leadership" to me - it would feel like an invitation to give up "stewardship" from the circle's roles to the "Circle Stewart").

"Circle Representative" is the best replacement for "Rep Link" for me.

I would imagine that in practical use, people would start speaking about "Anchor" and "Representative" or "Rep", when they mean "Circle Anchor" and "Circle Representative". I think using "*Circle* Representative" is important though to emphasize that the Role represents the Circle, and not the people of the circle.

**Comment by tylerdanke** [comment]
I like where you are going with the Circle Anchor and Circle Representative. When attempting to refer to the Circle Anchor of the Outreach Circle it would be natural and smooth to refer to Outreach Anchor. Outreach Lead Link is less natural.

**Comment by leodavesne** [comment]
Really happy to see some discussions around that topic that bothers since the first day I learned about Holacracy 😍 

I think the word "lead" (or "leader") is terrible because leadership is vastly misunderstood everywhere 😭 

Circle Anchor is a way better yes but on the other side could make us think that the person having the role is "stuck" with it. 
Why needing a noun to complete the word "Link"? Maybe the new name of the Lead Link is just "Link"?

Rep Link being clarified with "Representative" is already better too 👍

**Comment by brianjrobertson** [comment]
Thanks all for the brainstorming and sharing your thoughts here; super helpful for my role, and delightful for me to see personally too.  After synthesizing all of this and sitting on it for awhile, here's where I am:  There's a whole lot I like about Circle Anchor or Circle Holder (and just slightly less so Circle Steward).  That said, given the introduction in the current Constitution dev version of the concept of a "Role Lead", I'm now thinking "Circle Lead" may be the best bet, all things considered.  I didn't like that before, because of the "Lead" in there, but when it's balanced against the "Role Lead" concept I think it works, and the parallel is quite nice, and it won't raise jargon-alarms with people anywhere near as much as Anchor, Holder, or Steward will.

Open to further pitches if anyone has them, otherwise I'm going with Circle Lead in place of Lead Link.

**Comment by bemorr** [comment]
Something more passive like Circle Host?

**Comment by brianjrobertson** [comment]
I'm submitting the change from Lead Link to Circle Lead; please consider opening a new Issue if you have further thoughts on that, or on a better name for Rep Link (although please review the latest dev version first, as so much has changed around both these roles now, and that will undoubtedly effect the requisite names here).

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I'm coming up on the same - was thinking of "Circle Leader" in place of Lead Link.
Circle Lead is more difficult to translate in french than Circle Leader but we'll find out.
