### ISSUE TITLE
Remove constraint that Rep Link can't be Lead Link

### ISSUE THREAD

**Issue by tylerdanke** [holacracyone/Holacracy-Constitution#199]
Is there proof that the current constitutional constraint against Lead Link being Rep Link is in fact needed? I am unsure and would like to pose the question and make the pitch.

I am the Lead Link of a circle with only myself and one other partner. We need to meet at least weekly for our work, and the structure of being a circle is very beneficial. The other partner has no interest in representing the circle in the super-circle. That partner has been contracted to complete specific tasks and not to represent the circle in the super-circle. 

I believe that in some situations it makes sense for the Lead Link to be able to serve as the elected Rep Link. 

I trust that if any partner in any circle had tension with Rep Link being filled by the same person as Lead Link that they would either call for an election or resign or make a policy stating that it was not allowed.

I believe we should remove the constraint (although of course any given organization or circle could add it back via policy). That said, as part of this, ensure a broader circle can constrain this in sub-circles, in case an org-wide constraint is in fact needed.

If you're reading this and have seen real cases where the current constitutional constraint seems needed, even with the ability to specify an anchor-circle-level constraint that affects sub-circles, please share details.

**Comment by brianjrobertson** [comment]
Anyone have examples of where this seemed like a critical constraint, or other arguments to offer?

**Comment by julianeroell** [comment]
I think this is spot-on. I have not come across situations where the constraint would have been needed. The ability to call for an election at any time provides the safety needed I think.

**Comment by gvandegrift** [comment]
I think this makes sense for mature organizations, but like so many things in Holacracy, having some explicit constraints built-in help get less mature organizations going the right direction.  At times being able to lean on things like 2.2.3 (Amending the Lead Link Role) to help keep the organization from falling back on old hierarchical behaviors is important.

**Comment by bombino** [comment]
I think the scenario Tyler presents seems valid, and I see no reason the constraint is necessary.

**Comment by gmitterer** [comment]
I came across that issue several times during adoptions. Actually I am at the moment supporting a large adoption where we work in several roll-out waves. Until people are trained, circles don't shift to Holacracy and in the meantime the client decided to have elected "playing captains" that are both, Lead and Rep Link for the circles not yet running with Holacracy. What we observed: former leaders often got elected even if they were not the best fit. Hidden power dynamics, anxiety etc still influence this process. Thus I would argue dropping the constraint of LL being RL as well would make it harder in transitions to distribute authority and power. Of course you could say you can re-elect, but I have seen many cases where people subjectively didn't feel the full freedom to call for an election. The constitutional split definitely helps there.

**Comment by brianjrobertson** [comment]
@gmitterer Do you think it would still address the cases you've seen if the rule was that the Facilitator could only propose the Lead Link as Rep Link in an election if there were **_no_** other viable candidates (i.e. no one else was nominated, or anyone else nominated triggered an objection and was thus tossed out as a candidate)?

**Comment by brianjrobertson** [comment]
Or, alternatively, if the current restriction stayed in place, but the super-circle (not the sub-circle) was allowed to waive or change the rule for sub-circles, thus allowing a circle to adopt a policy that would allow its sub-circles to elect the LL as rep link?

**Comment by gmitterer** [comment]
@brianjrobertson The dynamics I have seen typically occurred within established teams or departments that were turned into circles to start. Any rule that is providing an option to intervene into that subsystem is helpful. Although both of your suggestions would work I guess, I would rather prefer the second, otherwise in the first option the LL - objecting against each other candidate - could manipulate getting proposed himself. Hypothetically, but still.

**Comment by margauxchiquet** [comment]
@brianjrobertson Following what @gmitterer said, in our experience when implementing Holacracy, there is a shift happening as soon as Rep Links are attending the Super-Circle's meeting (especially the GCC) because they can bring tensions from the down and process them. They are very useful because they are the one bringing real stuff, elephants that we identified in the Sub-Circle. If the LL can be RL, we lose that diversity and usually at the beginning the LL is the former manager so that doesn't help.
One thing we do as well when we explain LL & RL during trainings is showing that before the middle management had to deal with both the top and the down, trying to reconcile both which is impossible here (they often tend to favorise the top and if they don't, they are in a bad position). With the two links directions, we stop that dichotomy the middle management had and was suffering of, it is both relieving the manager and allowing the employees to process there tensions directly to the top.

**Comment by cosine** [comment]
I do not see the harm in the situation described of leaving the Rep Link position unfilled.  Firstly, in the super-circle, a Lead Link can already blur the lines of how a tension is being felt by the sub-circle in order to have it processed.  Additionally, if the other person that previously refused to be Rep Link later decides he has a tension to process in the super-circle that the Lead Link won't carry up, he can call for an election to fill Rep Link.

**Comment by bernardmariechiquet** [comment]
IMO and from my experience over the last years, this constraint against Lead Link being Rep Link is not a constraint. It is an essential key success factor for triggering the power shift. @tylerdanke I would be interested to understand more about your tension. In fact, I don't understand your argument as I got it being (and I may be wrong) "The other partner has no interest in representing the circle in the super-circle."
For me, representing the circle is not the key job of a Rep Link. I guess that in case your partner filling the Rep Link Role sense some tensions in one of his defined roles, one which requires to be processed into the super-circle, he would show up and process them, no ? And otherwise, your partner don't have to show up into the Super-Circle.
This is a clue for me here to challenge the last accountability of the Rep Link Role "Providing visibility to the Super-Circle into the health of the Sub-Circle, including
reporting on any metrics or checklist items assigned to the whole Sub-Circle".

**Comment by brianjrobertson** [comment]
I'm closing this given that the need is unproven, and the change potentially harmful from what was shared by coaches in this thread.  In the case of the originally provided example, the current development version already allows the Rep Link role to go unfilled (elections are not required until requested by a Circle Member), in addition to Bernard Marie's point above, so it seems covered.
