### ISSUE TITLE
Is there anything that prevents a super-circle Lead Link from making ultimatums?

### ISSUE THREAD

**Issue by edelstone** [holacracyone/Holacracy-Constitution#206]
Should a super-circle Lead Link be able to say to a sub-circle Lead Link that they _must_ remove someone from a role in their sub-circle and install another person, or – if they refuse – they will be removed as Lead Link so the replacement can be successfully initiated with an alternate?

It seems to me that this level of coercion is permitted, but is extremely against the spirit of Holacracy, role autonomy, and common sense trust.

I'm interested to hear practitioners' and leaders' thoughts on if preventing something like this should/could be enshrined in the constitution, or if business owners would feel they don't have enough control without this option.

Perhaps, since Lead Link can assign/replace roles at any time for lack of "fitness", there's no real way to enforce such a standard anyways.

**Comment by edelstone** [comment]
@brianjrobertson I'm particularly wondering if you think there is any issue here.

**Comment by brianjrobertson** [comment]
@edelstone Should anyone in any role be allowed to say to another role-filler that they must do something, lest the person use their own role’s authority (whatever it is) to do something else?  There is nothing unique to lead link role assignment power here; every role has real power, and any role-filler could choose to demand someone else do something specifiic, lest they use their role’s power in some way in response to that.  It would only make sense to prevent it in the lead link case if it would make sense to generically prevent it in all such cases.  And I don’t think that makes sense, mostly because it’s entirely too vague what constraint would even work - I don’t think there’s any clean distinction one could make here of what one is trying to prevent, without preventing desirable behaviors too, or introducing something so muddy that the rule itself risks becoming a weapon of undue control.  Besides, there’s a much simpler solution: if someone is using power (whatever power it is) in ways that hurt the overall system and its purpose, just get them out of the role - so if anything is needed/useful here, it’s probably just a way to make it easier to get anyone out of a role if they’re not using its power effectively, whatever role/power that may be.

**Comment by edelstone** [comment]
Sensible, thank you.
