### ISSUE TITLE
"People" vs "Partners"

### ISSUE THREAD

**Issue by julianeroell** [holacracyone/Holacracy-Constitution#207]
I was working on a partnership system for a new organisation today and noticed that the constitution speaks of "people" in places where I would expect it to speak of "partners":

1.5 "Role Assignment":
>The Lead Link of a Circle may assign **people** to fill the Roles defined by that Circle (...)

1.5.2:
> Multiple **people** may be assigned to simultaneously fill any Role (...)

@brianjrobertson , checking in with you: Is this a bug? Should it be "partners", or am I missing out on some subtlety? For me, it would be clearer if it was explicit that _partners_ are assigned to roles, not "people".

**Comment by klaas1979** [comment]
Good questions: I am using the term "partner" only for the person that files the role, i.e. it is the partner of the role. People are everybody within the organization. Partners only people with roles.

But I already had discussions about the terms as well, so I am curious.

**Comment by brianjrobertson** [comment]
@martinaroell: That is intentional; the constitution allows for non-partners assigned to roles (e.g. we have our external bookkeeper assigned to a role, plus another non-partner contractor); in that case the role-fillers aren’t invited to represent the role in governance (that duty falls instead to the lead link by default).
