### ISSUE TITLE
Sub-Circle Micro-management?

### ISSUE THREAD

**Issue by gvandegrift** [holacracyone/Holacracy-Constitution#210]
Per [2.6.1](https://github.com/holacracyone/Holacracy-Constitution/blob/v4.1/Holacracy-Constitution.md#261-modifying-sub-circles) in v4.1 of the Constitution (same basic stuff in [1.7.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#171-modifying-sub-circles) of master), a Super-Circle is granted the ability to push Roles into a Sub-Circle and pull Roles out (policies too).  Seems like language that could simply be eliminated from the Constitution altogether.

First, it seems like it is breaking encapsulation of the Circle.  Perhaps the Lead Link doesn't want to factor the work in his/her Circle in the way that would be demanded by a Role being pushed into it from the Super-Circle.

Second, the imposed Governance would only last until the next Governance meeting of the Sub-Circle (assuming the Lead Link wanted to eliminate it).

If the Super-Circle wants to impose "new" requirements on the Sub-Circle, doesn't it make more sense to amend the Purpose or Accountabilities and let the Sub-Circle figure out best how to deal with it?

There is another issue discussing this (#80) that seems to be advocating for being able to push governance around, but I would claim that's a software feature not a fundamental tenet of Holacracy.  If all parties involved want to lift and move a chunk of governance, they're free to do that according to the Constitution without this clause being present, right?

**Comment by LouisChiquet** [comment]
Effectively, that makes total sense in 100% self-organisation. However, there is also the practical case which is, we restructure for example an organisation, change the Circles membranes (or role shall we say from that Super-Circle perspective), but sometimes over time capacities have been built by role doing an activity which is moved to a new Circle (like, notes, accountabilities refined), so it would be losing capacities then to not integrate/move those if it makes sense. For your first point, well, then the Lead Link got a tension and process it easily, but we often have the case (have a concrete example) where there are no issues, as also the Lead Link often did participate to that Governance meeting. For the second point, well yes, the sub-Circle would naturally wish to work as they wish, a goal of moving roles isn't to impose a way to work but more to save capacities (which they organise as they wish after). That's what I had in practice, after for the Constitution, how to manage that more easily maybe, well I suppose this need to be clarified with the same issue #80 you give an update on. Maybe, what could be done, is for all policies or roles moved into a sub-circles, to be considered as a Governance out of Governance? Would have to figure that on the platform for GlassFrog, but that's another issue. But I feel like it could be great to just, you propose moving a role to a sub-circle, as it makes sense for restructuring the organisation, and so that role would be proposed in asynchronous Governance of the Sub-Circle once the Super-Circle has finished the Governance meeting, and like that the Circle actually self-organise! And it would solve the issue #80 in my opinion, as GlassFrog prevent you from technically being able to move a role in another sub-Circle, as it wouldn't make sense anyway because it would be for the Sub-Circle to self-organise and update or not the membrane of its sub-circle. It's very interesting topic, and something great can be done about it!

**Comment by LouisChiquet** [comment]
OR, as it's “Alternatively” and so not mandatory for [3.2.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#321-making-proposals), say more like, a point is automatically added to the next agenda of the Governance meeting, or that it is the duty of the Lead Link to bring it (knowing he already have an accountability “_Structuring the Governance of the Circle to enact its Purpose and Accountabilities_” allowing the Circle to truly self-organise while it still include the previous capacities point which I developed in my previous message(which would still ask the question about the roles Notes).

**Comment by gvandegrift** [comment]
Thanks for the perspective.  If I'm understanding you correctly, I think most (all?) of your points are of a practical nature.  All of those things don't have anything to do fundamentally with Holacracy.  Platforms like GlassFrog are free to offer conveniences for moving Circles, Roles, Notes, etc. around; but it seems odd that Holacracy itself would prescribe that ability (per my points above).  I think the Constitution could be simplified by removing that sentence.  Shorter/simpler is always better. ;)

**Comment by LouisChiquet** [comment]
That would create blur (as nothing would be defined from what I've understood from your proposal?), and the point of the Constitution is to be practical (it evolute only with concrete cases and practices), stick to reality, on a metamodel and distilled level (allowing any organisation to use it), that's the purpose, so by amending it through the idea of having more self-organisation (what's the concrete tension? Did a LL had tension about it? Or circle members?) without sticking on the day to day practice... And GlassFrog stick to the Constitution, so I wouldn't like the idea of having platforms like GlassFrog not sticking to the Constitution and offering things which aren't supporting the Holacracy practice (knowing that it's already hard to implement and give new habits to people, so if the software was to not support fully the practice...). After, for sure, there is something that needs to be changed in the Constitution, I made suggestion in my upper posts.

**Comment by gvandegrift** [comment]
I don't think "nothing would be defined" is correct.  I'm not suggesting that the entire section be removed.  At the very least, this would still be in the section, "A Circle may modify the Purpose, Domain, or Accountabilities on a Sub-Circle."

If I'm understanding you correctly, I like the idea of "proposed governance" being passed to the sub-circle for consideration at their next Governance Meeting.  Then it's more of a suggestion than a mandate.  I think platforms like GlassFrog could make that available, but the constitution doesn't have to say anything about it.  (GlassFrog offers other concepts that don't exist in the Constitution:  Notes for example).

**Comment by brianjrobertson** [comment]
For practical purposes, I think it is indeed critical that the constitution allows roles & policies to be moved across circle boundaries.  Yet, just moving them as a way of designing the structure is a terrible practice; they should only be moved when you're also moving an accountability or reshaping a purpose, and merely as a convenience, never as a way of specifying what you expect from a sub-circle.  So, I'll add a limit clarifying when these moves are not allowed - that should at least help with this issue significantly.
