### ISSUE TITLE
Re-order sequence of objection criteria

### ISSUE THREAD

**Issue by chrcowan** [holacracyone/Holacracy-Constitution#213]
**[continuing the conversation from a rejected pull request]** 

Curious to hear others' thoughts on this. I proposed reordering the objection validity criteria in 3.2.4, to assist Facilitators in asking the most helpful test questions earlier. My proposed order is: 

1. The objection is a reason about harm
2. The objection is based on a role the objector fills (previously 4th)
3. The objection is about the proposal (previously 2nd)
4. The objection isn't predictive (previously 3rd)

__Note:_ I totally get that the questions can be asked in any order, regardless of how they are ordered in the constitution, so in a way this is a small point. However, I have a role that designs the meeting cards, and since I plan on re-ordering the questions on the cards, I would like them to mirror how the questions are ordered in the constitution._  

In my experience, it's far more common for an objection to be invalidated because it doesn't fit one of the objector's roles, rather than because it's predictive. It is also a more important learning point ("Is the tension felt in a role you fill?") for early practice. However, the current version of the Constitution sequences the criteria in such a way that many Facilitators ask the third predictive question (and all of its nuanced explanations) when if the Facilitator had just asked the role-based question, it would have likely been invalidated. So, I'm proposing a simple re-ordering of the criteria to make it easier for Facilitators to apply the test questions. That change was rejected, but I'm not yet satisfied with the reasoning, so I wanted to put it out to a larger group. 

**[For context] Brian's first response:** 
@chrcowan I don't think this change makes sense; if someone is going through the questions in order with a new group, it's more powerful to leave the role one to last, even if it's the most likely to identify an invalid objection - there's lots of learning that happens by going through the other questions, and when an objection is not valid because of multiple reasons, it's more powerful to catch it with one of the other questions over the role one.

**My response to that:** 
@brianjrobertson I disagree that the learning is served by going through the other questions first. My reasoning for changing the sequence is the same as used for highlighting, "name the role" as an early habit -- because understanding differentiation makes it easier to understand lots of other things. In my experience (thinking of assessments particularly), asking the questions for the sake of asking the questions doesn't serve the learning because it's divorced from the actual needs of the situation. Being on that side of things as a role-player makes it clear -- ask the most relevant questions as soon as possible. Otherwise, objections/objection testing seems much more like a fun game the facilitator is playing rather than actually helping me process my tension (i.e. objection).

**Brian's last response:** 
@chrcowan - I do see the value you're pointing to and I agree with you, but I prioritize it significantly lower in importance than the value served by the current order, which is that other questions often have the opportunity to invalidate an objection before that question does (when someone goes in order, which novice facilitators often do). When other questions invalidate an objection in early practice, appreciation for Holacracy increases and resistance decreases; when that role-based question does, it's exactly the opposite. If you want to discuss/pitch further, please open an Issue rather than this comment thread on a submission, so others can more easily find it and weigh in.

So, my response to that now is this: 
I can see Brian's point when he is training or working with clients, because his skill level at being able to effectively coach around the paradigm-shifting issues like "sense & respond vs. predict & control" used in criteria 3, or "one tension at a time"/consensus-seeking used in criteria 2, may make those points more helpful (and feel somehow less awkward), but I find that the learning around differentiation (role vs. people) is more requisite for early practice, especially as it is reinforced during early tacticals) and therefor the role-based question should be asked earlier.   

Thoughts? Reactions?

**Comment by brianjrobertson** [comment]
Last call for anyone to share support for or against Chris's proposal, before I close this by default.

**Comment by LouisChiquet** [comment]
I really like in trainings or in clients to end up with the last clarifying question, “_does this limit one of your role (if yes which one, or are you trying to help another role or the circle in general?_” as, at least in France, it's a major teaching point. Chris: “_In my experience, it's far more common for an objection to be invalidated because it doesn't fit one of the objector's roles, rather than because it's predictive._”, totally. And in fact that would be a reason why I'd keep it last, for retaking Brian's point “_which is that other questions often have the opportunity to invalidate an objection before that question does (when someone goes in order, which novice facilitators often do)_”, and it helps people learning, rather then using question 4 always (which would come second following your suggestion), and saying “_anyway, can never object as it don't limit one of my role_”. The current “order” allows people to see the Why and how deep other questions are, and how much efficient they are.

**Comment by chrcowan** [comment]
FWIW - As Support Product Designer in H1, I plan on reordering the test questions on the meeting card to align with my reasoning. I think I failed to include that in my original context.

**Comment by margauxchiquet** [comment]
Great @chrcowan! Please let us know as soon as it is done and I am sure @bernardmariechiquet would love to review your drafts :)

**Comment by margauxchiquet** [comment]
Re @brianjrobertson 's questions: I don't even ask that role question at the beginning because it is already a good thing people are bringing stuff (tensions, objections, etc.) so I don't want to stop them in their movement. I think the first habit, before roles (or at the same time) is sensing and bringing tensions even if they don't understand the mechanics and the first 3 questions helps understand what a tension/objection is so very powerful. Roles come after. They first need to process stuff and see the power of Holacracy.

**Comment by chrcowan** [comment]
I agree about not wanting to convey they shouldn't bring the objection. Or, in some way use that question to stop them from bringing up the objection in the first place. However, I think it DOES make sense to clarify an invalid objection AS SOON AS POSSIBLE. Meaning, as elegantly as possible. Artificially asking questions that, at best are irrelevant, and at worst are confusing, doesn't serve the learning at all. 

I wrote a blog post on 17 of my own coaching principles, and this reminds me of number 6 (see below). 

And I find it so much easier to address the role distinction head-on than to beat around the bush with it. Meaning, I'd rather have the opportunity to coach on things like, "Use your reaction round to equip others with objections if you're not in that role," which helps support the idea, "encourage objections," rather than talk conceptually about issues which are of secondary relevance (assuming that the objection isn't coming a role they hold). 


6. Beware of “Learning for Learning’s Sake”
Asking all of the objection test questions because, “I want to help the group learn the criteria,” is a mistake. Learning often helps process tensions, but that kind of learning is in service of getting things done; not an end in itself. Asking all the objection test questions when you don’t need to and telling yourself, “It’s to help them learn…” is probably masking the fact that you just don’t know which question to ask. That’s OK. But don’t disguise your ignorance by telling yourself it’s for others’ learning. Other examples include failing to raise a NVGO objection “…to see if others will raise it,” or hesitating to provide a solution to your own NVGO objection in Integration, because “I want to see if they can figure out how to fix it.” Role-modeling good practice is much more powerful than trying to manipulate and manufacture learning for someone else. At worst, “learning for learning’s sake,” is a lie. At best, it’s just a really a bad way to facilitate. So, if you find yourself justifying a choice on that basis, be skeptical.
https://blog.holacracy.org/17-holacracy-coaching-principles-e9c35174c372

**Comment by margauxchiquet** [comment]
@chrcowan I agree that your order makes sense if there is any order (should there be an order at all?) but after, I guess it will confuses coaches that are not skilled enough... I don't know...

**Comment by chrcowan** [comment]
@margauxchiquet Agreed. If we could avoid suggesting an order that might be ideal, but I don't think we'll ever know. These things (including Holacracy) can only be _understood_ all together, but they can only be _communicated_ one-at-a-time.

**Comment by oliviercp** [comment]
FWIW, @chrcowan, I agree with @brianjrobertson's last comment that you post in your initial thread. My experience is that _both_ a) going through all questions for the sake of learning, and b) invalidating an objection because of the role criteria, can harm the learning. But I think b) is worst than a) if you have to choose.

**Comment by chrcowan** [comment]
@ocompagne Ah, gotcha. LOL. Then I just completely disagree that B is harmful to the learning. Invalidating an objection based on relevant criteria is never harmful to the learning (unless something else is going on, like being a jerk about it), on the other hand, I would argue that dragging something out artificially "to help the learning" actually could be harmful to the learning (not saying it always is, but it requires a higher level of skill -- one which novice facilitators aren't likely to have). 

My argument is that, sure, there is more to explore with the objector, but that comes in time, as determined by real needs, real situations, real tensions. And if you're an experienced coach, then in any given situation, sure, jump around, do what you want. You're making judgment calls all the time. 

The problem is that for new people the learning is two-sided; what the objector is learning about the criteria, but also what the facilitator is learning about the criteria. And my argument is that learning role differentiation should have a higher priority not necessarily because it's inherently more important than learning the importance of explicit agreements (current criteria 2), or learning about sensing and responding (current criteria 3), but because it's a more appropriate scaffold (i.e. less potentially harmful for the learning) for new facilitators as they wield it about.

**Comment by oliviercp** [comment]
@chrcowan What do you think of @brianjrobertson's following comment?

> When other questions invalidate an objection in early practice, appreciation for Holacracy increases and resistance decreases; when that role-based question does, it's exactly the opposite.

To me that's the piece that sways me, and I can relate to it from experience. Of course for an experienced coach it's an opportunity to explain that criteria, but for a novice facilitator it's a tougher one to explain because it touches at the core of Holacracy's differentiation between roles and people.  And if a novice isn't ready to explain this criteria with enough depth of understanding —which is likely the case— then that's when appreciation for Holacracy can decrease. So I like having this question deprioritized on the card specifically for more novice facilitators. Experienced coaches can be more strategic and choose whichever criteria they want to test against first.

**Comment by julianeroell** [comment]
I am with @chrcowan on this one.

>Invalidating an objection based on relevant criteria is never harmful to the learning (unless something else is going on, like being a jerk about it), on the other hand, I would argue that dragging something out artificially "to help the learning" actually could be harmful to the learning

I find it helpful to invalidate objections quickly when they can be invalidated, and the role-based question often does that efficiently.

My experience re motivation/ appreciation of Holacracy is also the opposite of what was shared here:

>When other questions invalidate an objection in early practice, appreciation for Holacracy increases and resistance decreases; when that role-based question does, it's exactly the opposite.

I find that dragging the process out (by using the other criteria), when it could be efficiently brought to an end (by using the role-based question) is frustrating; and efficiency and role-clarity is motivating.

It is important that Circle Members operate in Governance firmly grounded in their Roles. Therefore I think that assuring that they _are_ (grounded in their Roles in Objection Round) is helpful. I support the suggested change.

**Comment by bernardmariechiquet** [comment]
Thanks @chrcowan Love this thread even being late. Let me add a piece to it. I think this conversation about the best learning experience is just a great one. I also think the discussion about the order at the back of the card should be broadened in order to include the other piece which is the question on the recto of the card (at Objection  Round) that occurs before any testing. Indeed the participant experience of the objection process starts by this question: "Do you see a reason why adopting the proposal causes harm or moves us backwards?"
I'd like to challenge this one and I would rather ask something like: "Do you see a reason why adopting the proposal would limit one or your roles?" which would be more concrete for people at the first place.
I found that the *usual* question is quite abstract even confusing for many people and the latter much more helpful and make easier the individual thought process.

**Comment by chrcowan** [comment]
@bernardmariechiquet oh interesting! I was thinking of that, but I could see the question, "Do you see a reason why adopting the proposal would limit one or your roles?" as a helpful frame. Seems somewhat more situational though. Maybe not, just thinking through it. 

The aspect that would be problematic would be if that question got interpreted (or delivered) as being a high-bar for an objection; i.e. "You know, you shouldn't raise an objection unless it's from one of your roles." Which, of course, is actually true, but I would want the objector to realize that for themselves, not give the facilitator any ammunition to suggest an objector should self-filter.

I know this is getting of the original thread here, but I do wonder if something like, "**Would you like to _try_ an objection?**" could be a better question to start with. In practice, that question works great. And sure people don't know what an objection is, but they don't really know what "harm" is either (i.e. would limit my role's ability to do its thing). And that phrasing would likely make it much easier for both parties (objector and facilitator) which is my goal with the meeting cards. Could be a horrible idea of course. I don't know. 

But it sounds like you are at least in agreement that it would make sense, all variables considered, to ask the role-based question earlier by default, yes?

**Comment by bernardmariechiquet** [comment]
@chrcowan I love that one "Would you like to try an objection?" and I would change it a little bit like **"Do you have a concern about adopting the Proposal and would like to try an objection?"**
This would encourage for objection and now they can dare more easily.

Re your last question, **"But it sounds like you are at least in agreement that it would make sense, all variables considered, to ask the role-based question earlier by default, yes?"** I'm still reflecting on that one. I think one should think about a "new practitioner and new Facilitator" situation because if the Facilitator is experienced he will choose the order "on the fly" that makes the more sense given the context. And with an experienced practitioner, it doesn't care as they should already know the Objection concept.
So IMO the card design order should focus on both new practitioners willing to try an Objection and a new Facilitator. And this is why it's a tricky question. What is the best order both for new practitioner learning but still easily manageable by the new Facilitator.
May be asking the question/issuing a survey on that one would be great? Did you try the COP?

**Comment by chrcowan** [comment]
@bernardmariechiquet yeah that could work! Re: "Do you have a concern about adopting the Proposal and would like to try an objection?" 

Regarding the second part of your post, "Yes! Exactly!" I'm trying to find a question that would work more effectively for a novice objector and a novice facilitator. 

Or said another way, I'm thinking about _the dynamic_ between the two of them (novice facilitator and novice objector) and treating that as a distinct entity (@ocompagne another occasion of the dynamic!), because that is really what testing is all about. And the lack of experience by both parties means it's not only a matter of trying to balance or compromise their distinct needs but it's also considering and integrating the results of the chemical reaction when they're mixed together.

**Comment by bernardmariechiquet** [comment]
@chrcowan Love this focus on a novice objector and a novice facilitator and 'd like to dive in more what you call _the dynamic_

**Comment by brianjrobertson** [comment]
I'm closing this issue given the split opinions of those coaches who chimed in, plus my own sense of it; feel free to reopen @chrcowan if new data/perspectives surface.

**Comment by chrcowan** [comment]
@brianjrobertson Following our conversation with @ocompagne at the retreat, I'd like to reopen the question while preserving the dialogue in this thread, is there a way for me to do that, or do you have to do it?

**Comment by brianjrobertson** [comment]
@chrcowan I'll reopen it.

**Comment by LouisChiquet** [comment]
Eager to hear your thoughts on this @ocompagne @chrcowan. :)

**Comment by chrcowan** [comment]
@LouisChiquet :) Well, my thoughts are basically the same on this issue, i.e. I think it makes sense for my role to reorder them on the card, but maybe I don't need to push too much on changing the order in the constitution. I'm thinking just about the learning and for most facilitators and practitioners and they learn from using the card not by referencing the constitution itself. So, I'm still convinced the reorder would be better (maybe even slightly more so after observing people use the cards in the Austin PT), but less convinced that the cards and the constitution must match.

**Comment by ericdgraham** [comment]
I haven't gone through the full thread here for the sake of time, but I do like Chris' new ordering. I like that it clarifies the harm up front, as before, and grounds it in a role secondly. Those feel like the two key points to establish up front.
The objection is a reason about harm
The objection is based on a role the objector fills (previously 4th)
The objection is about the proposal (previously 2nd)
The objection isn't predictive (previously 3rd)

**Comment by klaas1979** [comment]
While thinking about the criteria orderung, I got one thought:
old 1) + old 2) + old 3) are questions about the objection itself and flow quite naturally.
old 4) is a question, if the harm is grounded in a role the person fills, which brings a different dynamic.

My gut feeling is to order it like:
1) old 1
2) old 2 -> now we know that there is harm and it is caused by the proposal. This two information a quite useful together
3) old 4 -> does it bother your roles, could be a got next question and feel natural
4) old 3

**Comment by rebeccabrover** [comment]
@chrcowan I agree the movement of question four to a new location of question two makes a lot of sense. The primary reason I support it is the possibility it might negate what I think of as the last-minute "gotcha" moment I've experienced with new practitioners (both at trainings and in real meetings).
Picture it...we are mid-objection testing and the novice objector is honestly trying to answer the questions. They see harm, check! It's caused by this proposal, check! It's not safe enough to try, check! It helps another role...whammy! In several cases, participants in meetings have verbally shared the deflation of feeling "tricked" by getting all the way through the other test questions and then learning the objection is invalid after the final question. I also see that reaction in the form of facial expressions, reflections after the meeting or general body language and I feel that pain as facilitator and coach. While a little pain is good, it often has the effect of discouraging future objections to "avoid the hassle".
Moving the question up to number two still allows the objector space to surface the harm but curtails the potential investment in the objection's validity which many novice practitioners consider a zero-sum game with the facilitator while they are learning. If the proposal does limit their role, it's confirmed earlier and the objector has the opportunity to ground deeper into their felt objection and offer reasoned answers to the other two questions (if it is indeed a valid objection). If it does not impact their role, they have still surfaced the possible harm in service of the circle but are less invested having only answered one other question. If I were coaching this interaction, my brief coaching intervention (during a time-out) would be something along the lines of _So what you've just told me is that is not a valid objection as it does not impact your role, but you may have surfaced something useful for another role to consider in the future. Any further objection?_ and then move on.
So many practitioners are so used to worrying about *everything* in their current working environments so the more they are re-conditioned to think critically about whether their role is impacted or if they are slipping back into caring about everything (also a good earlier teachable moment about the authority of a Lead Link) which may no longer be their burden to carry.
Furthermore, with more advanced groups, when questions are more often asked out of order, I find question four naturally moves to the second spot immediately following the reason the proposal causes harm so this seems requisite to me to move it there for everyone.

**Comment by chrcowan** [comment]
@brianjrobertson in response to what do I think about this alternative order: 1, 2, 4, 3: 

Seems pretty equal to what I was proposing since my main concern was 3 being asked before 4. I didn't feel that strongly about which came earlier between 2 and 3 though.

**Comment by brianjrobertson** [comment]
Hmm, interesting - @rebeccabrover may have sold me on this (I've been one of the big opponents of it thus far).  @ocompagne, I'd love to hear from you though - did that argument sway you, or are you still thinking it's better to keep the current order?  And what about the midway-between-the-two option of just swapping the order of Q3 and Q4?

**Comment by oliviercp** [comment]
Yes @rebeccabrover's take makes sense to me (as discussed live)

**Comment by brianjrobertson** [comment]
Okay, thanks all, and especially @chrcowan and @rebeccabrover, who helped change my mind on this one; I'm going with a new order of 1, 4, 2, 3.
