### ISSUE TITLE
Require interpreting Purpose and Accountabilities in holarchic context

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#217]
Add a requirement to always interpret a Role's Purpose or Accountabilities in the context of the containing Circle's Purpose and Accountabilities.  e.g. ensure (a) a Role has no authority to take an action that serves its Purpose/Accountabilities but does not serve the Circle's, and (b) a Role must decline any requested action/project that would fit within its Purpose/Accountabilities but not serve the Circle's.

Note:  This is how I've always interpreted the Purpose/Accountabilities and authorities of my roles, but that's not explicit and required - other interpretations are possible, and should not be allowed.

**Comment by brianjrobertson** [comment]
Note:  Once this is implemented more generically as described here, we should be able to remove the additional "must serve the circle too" clause in 3.2.2 - Criteria for Valid Proposals.

**Comment by karilen** [comment]
I've never seen this as a big issue, so my concern is what language or constraints are you adding. I don't know how to review it or I would.

**Comment by brianjrobertson** [comment]
It's not implemented yet @karilen - if it were, you'd see a note from Github that I referenced this issue in a submission (not just another issue), and the issue would likely be closed, not open.  If you want to see issues already implemented and review them, search for Closed issues; or, go to the constitution file itself (under "Code" in the nav bar) and click History.

**Comment by LouisChiquet** [comment]
Superb, that would address perfectly the [issue](https://github.com/holacracyone/Holacracy-Constitution/commit/9a687916d1d692ebdc141d84ff5488516f5787eb#commitcomment-26363125)! I feel however it's heavy and restricting with the current 2.3.
The issue is that in [2.3](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#23-duties-to-other-role-fillers), following #167 and #182 which resulted in [that](https://github.com/holacracyone/Holacracy-Constitution/commit/9a687916d1d692ebdc141d84ff5488516f5787eb) we now talk of Duties as a Partner of the Organization. Making it delicate to put your two suggestion in the 2.3, except if we pass to something like: “_**When filling a Role in a Circle**, you have the following duties to others in your Organization **as long as it's aligned with your Circle's Purpose/Accountabilities**, but only when they’re acting on behalf of one of their Roles and name that Role in any explicit request._”, the term “others” in that sentence would have, however, to be specified, do we talk about partners or roles? Because as Partner you may well be asked to do individual actions or else to help, but in the opposite role, can you also ask directly to a role as a Partner a project or else? In the case, it makes sense for the organisation and it's in the accountabilities of the said role and makes sense in the Circle's purpose? Maybe I'm just going too mental and that the two suggestions you made are fine?

Or maybe and simply just adding something to the [2.3.2 Duty of Processing](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#232-duty-of-processing), having so “_You have a duty to promptly process messages and requests from your fellow Partners **as long as it enters in the Circle's Purpose/Accountabilities your role is situated in**, as follows:_”. As from what I've understood from the general tension, it's more for [2.3.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#231-duty-of-transparency) and [2.3.3](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#233-duty-of-prioritization) (except maybe 2.3.3 a, that's questionable) that the previous changes have been done?

Also, have you been able to document a few concrete examples?
