### ISSUE TITLE
Merge "Rep Link" and "Role Representative" concepts

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#220]
The current dev version has a concept of a Role Representative, which is confusingly similar to Rep Link in many ways (even beyond just the name).

**Comment by karilen** [comment]
Is role representative intended to address large companies or roles with many people and a default constitutional way of handling that? If we had circle representative and role representative they could function the same except one is for the circle and one is for the role. Also the selection process for role representative may vary from the election process

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I fully agree with your comment - when I read that in the dev. version of the constitution, it felt weird for me - something is off.
Why not eradicating Rep Link and using Role Representative instead as the new and unique concept. Ex-Rep Link being a Representative of a specific role being a circle.
As the concept of a Role Representative is a new one, it will help and make it clearer to delete Rep Link and use Representative instead.

**Comment by bernardmariechiquet** [comment]
And I would also suggest to change the name of Lead Link by Circle Link or Circle Anchor, to avoid the kinda "exclusive leadership" of a LL. As you know, we chose to go for "Premier Lien" when localizing the constitution in french - there are many benefits in it and some concerns - so I'm looking for a new name and Circle Link (Lien Cercle in french) came out.

**Comment by bernardmariechiquet** [comment]
So from another perspective, a role being a circle has got per default 2 Representatives : the Anchor one and another one being elected for all sub-circle'role fillers. This opens for having more than 2 Representatives for a Circle.

**Comment by brianjrobertson** [comment]
The trouble there is that the two aren't the same; in a change I'm working on now, I realized the Role Representative concept falls into that issue and gets confusing: only one of the Role Representatives actually holds the responsibilities of the role and duties to others because of the Role.  But, I think I've fixed it by going a different direction: I'll submit the changes I'm working on soon and then explain further and ask for input.

**Comment by seriousplay** [comment]
I would also suggest to change the name of LL to something else. First off,
LL is not so much of a link role, as it is not selected like the rest of
links.  I also have the same problem in translating it into Chinese -
direct translation would indeed make it no difference to traditional
leadership structure.  Perhaps something like Circle Holder、Circle Steward、
Circle Keeper might be better?

**Comment by LouisChiquet** [comment]
Knowing also that Brian submitted many changes to the role of the [Lead Link](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Appendix-A.md), this may help in the choice of a new name.

Also, there would be this gap between Rep Link and Role Representative “_A Circle may adopt a Policy to invite an external Role to participate in its Governance Process_” in [Article 1.6.2](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#162-inviting-outsiders-into-circles)? And why not specified also tactical as it often concerns tactical meeting, in order for example to have visibility on projects in the case of a Role Representative. After naturally, everything that isn't prohibited is allowed to be done I suppose? This would be another gap from the Rep Link role, knowing that it's the Lead Link holding the responsibilities in the Upper-Circle ([1.6.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#161-representing-sub-circles) “_However, only the Lead Link actually fills the Sub-Circle Role and thus holds the associated responsibilities._”) as effectively, in many cases of inviting external role is to have visibility on that other role projects for instance.

I suppose we may redraw the way it is designed, by for example re-taking the modelling of the Role Representative over Lead Link/Rep Link, like there would be two partners filling the Role (which is a Circle), the Lead Link would be the Role Representative, while the Rep Link would just be filling that role and invited to meetings (opening a disclosure on that per default as there is [2.5.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#251-attendance) and [3.3.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#331-attendance) inviting only Role Representative) and making per default the election by the sub-circle of the second role filler. Most likely not a good idea, as the goal isn't to naturally forcing the two to stick together, but just opening something in order to not remain stuck in the today's pattern. The hardest is to turn complexity simple.

Because, on your point Brian, “_only one of the Role Representatives actually holds the responsibilities of the role and duties to others because of the Role_”, it's basically also the Lead Link doing so (by holding responsibilities from the point of view of the Circle he/she's in), so the changes you're working on may, I suppose, also have an impact on that Lead Link role.

**Comment by brianjrobertson** [comment]
If anyone has suggestions above about renaming Lead Link, consider posting them over in the relevant issue (#198) so we don't lose your input once this issue is closed.

**Comment by yiqing-he** [comment]
I think it is a good move to merge "Rep Link" and "Role Representative".  And I even suggest that we merge "Cross Link" as well.  I understand the link concept serves a purpose to invite people to think differently on the paradigm of organizations as networks, but it is a bit techie for the majority of business world.  Role representative/Circle Representative/Cross circle representative would make it much easier to understand.
