### ISSUE TITLE
Help Wanted:  Review Recent Changes

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#234]
Hi Folks - I'd love to get some of you super-serious Holacracy practitioners to review my recent massive refactor to merge the treatment of sub-circles and multi-filled roles.  To help you understand what's changed and why at a high level, I've recorded this [30 minute video](https://www.useloom.com/share/9727880b6a7e4c23aa4a07f0bc0a5f98) explaining the changes.

Note:  I thought the video was recording my screen, which had the constitution text on it (I was highlighting passages as I spoke), but it turns out it wasn't.  So, that's why I seem to be referencing something you can't see in the video.  Rather than re-record the whole thing, I'm going to hope you can follow well-enough on your own by pausing the video as-needed to go look at the latest text.

Thanks in advance for any support anyone can offer!

**Comment by gvandegrift** [comment]
First question/corner case that comes to mind:

Given that Circle Membership is now decided by the Super-Circle Lead Link, consider a case where I'm a Lead Link for a Circle nested 5 levels deep.  If there is someone in the organization that I would like to assign to a Role in my Circle that is not already a Circle Member, is it correct that I basically have to walk up the chain until I arrive at a Circle that the person is a Member of and then ask all the Lead Links in that chain to make that person a Circle Member all the way back down the chain?

**Comment by brianjrobertson** [comment]
Yes, that’s correct… but only if those circles have all intentionally controlled their partner-to-circle-member allocations that way.  It’s also possible that every circle simply allows any role/sub-circle within to pull from their own circle member pool to assign to roles, in which case it would work exactly like it does in v4.1.  The big change here is just giving circles the option to not allow a sub-circle to assign anyone they want to their own roles; so the scenario you describe is possible, but it’s not necessarily a requirement - it’s just that now circles would have the option to limit partner availability to sub-circles now.

**Comment by tylerdanke** [comment]
So in an organization of 10,000 partners a board anchor circle would manually say that a GCC subcircle can have all 10,000 partners in it?

**Comment by brianjrobertson** [comment]
No, it would simply authorize the sub-circle to pull from its own available Circle Member pool for the sub-circle's role assignment.

**Comment by gvandegrift** [comment]
Is there a default behavior?  If I'm reading it right, it seems the default is that membership is constrained (i.e., you can't pull from the Super-Circle's pool).

**Comment by brianjrobertson** [comment]
There is no need for a constitutional default or lack thereof - that's entirely a question for the tool supporting Holacracy practice (e.g. GlassFrog)...

**Comment by gvandegrift** [comment]
Oh, okay.  I was assuming it was a constitutional thing based on this from 1.5.1:  "Whoever controls assignments into the Role in the Super-Circle may later add or remove Circle Members of the Sub-Circle instead of Role Supporters, or may delegate this authority to the Sub-Circle itself."  Doesn't that mean there would need to be governance to delegate Circle Member assignment to the Sub-Circle itself?  Or maybe thats talking about something else altogether?

**Comment by brianjrobertson** [comment]
That's saying whoever controls it may delegate it - i.e. directly, without governance needed.

**Comment by gvandegrift** [comment]
Okay thanks for clarifying.  Not sure if there's any way to make that more clear in the wording of the constitution.

I have a couple of other observations/questions.  Is this the best place to put them, or will it turn this thread into a huge mess?

**Comment by brianjrobertson** [comment]
This seems a good place to me; go for it!

**Comment by gvandegrift** [comment]
My understanding from watching your video was that a Role supporter can act with full authority of the Role (aka Circle) but a Role filler within the Circle (similar in concept to a Role Supporter) cannot.  He can only act with full authority of his Role, right?

**Comment by brianjrobertson** [comment]
Yes, that's right.  Once the Role becomes a Sub-Circle, its Role Supporters become Circle Members, and lose the ability to act for the overall Role (except via IA) now that there's instead an opportunity to differentiate authority/responsibility further.  Something about that approach feels just a bit off to me, but I couldn't find a more cohesive approach so I went with it, at least for now.

**Comment by gvandegrift** [comment]
Exactly.  I was just going to point out that it feels odd.  It's almost like a Role Supporter gets a "demotion" when the Role becomes a Circle.  Unfortunately, I don't have an alternative suggestion ready to go.  Something to noodle on...

**Comment by gvandegrift** [comment]
Final question/observation for the moment.  In v4.1, a Multi-filled Role might just have one person in governance.  In 5.0, there would always be at least two, right?  Role Lead and Rep Link.  If that's true, it seems a little burdensome (rather than being able to have just one), but perhaps the simplicity/consistency it brings to the constitution is worth it?

**Comment by brianjrobertson** [comment]
Generally, yes, that's right.  However, note Issue #226 and #227 will give more flexibility and should remove that burden...

**Comment by yiqing-he** [comment]
I have been trying to understand what are pros and cons regarding this massive refactor in 5.0.  

The major benefits I can see is that this type of structure better reflects a holarchic pattern, by merging the concept of multi-filled roles and sub-circles.  It makes a lot sense to me, both logically and aesthetically.  

I have several concerns/suggestions if relevant here. 

First, I really like the concept of Role Lead, so it makes a lot more easier to explain distributed leadership and power shift in a HPO.  I have a suggestion here. Since a circle is also a role, why don't we rename LL to Circle Lead?  My argument is that LL is essentially an operational role, so it is not a link, such as Rep Link or Cross Link.  By juxtaposing role leads and circle leads, people can instantly get that these two roles have almost identical function which is to hold the overall purpose of the entity it represents.  

Second, I wonder if it is possible to defunct the use of focus assignment by up-scaling Role Supporters. I appreciate what role focus can do, but at the same time I sense that having both mechanisms might lead to convoluted issues.  Say we have a multi-filled role called Client Representative, with focus on different contexts such as industries.  Then if one Client Representative with focus on telecom needs to have several role supporters doing executive assistant job.  In this case, if we need to have a governance meeting, would it be too confusing to have rep links from both role supporters and multi-filled roles? I haven't seen this in reality, but just a thought experiment. 

Third, I think it might not be a good idea to constrain sub-circle's role assignment authority.  Partners are valuable assets of the organization, but they are more than just resources.  I think a major contribution from Holacracy is it differentiates roles and souls.  Roles are the structure of the organization, but people are the blood and energy that nurture and nourish these roles.  It seems weird to me that restrict the authority for sub-circles to assign roles to members that are only within the circle pool.  The best way to keep our body healthy is to maximize free flow of blood and energy.  In addition, relying on LL of super circle to set the option for circles that are nested deep down also seems to be problematic.  How can we trust the super-circle LL to make wise enough decision, if he/she has never been part of the governance meeting of lower level sub-circles?  Just questions for now, but would like to hear more people's thoughts on this.

**Comment by brianjrobertson** [comment]
Hi @yiqing-he - Apologies for the delay here, and thanks for the feedback; very helpful!

Re your first point:  I resonate with your comment on Circle Lead, and have just added a comment to #198 accordingly.

Re the second:  In your example, there would only be a rep from the Role Supporters there, because the Focus makes it behave like an entirely different role than the other foci.  In general, I share your concern about the added complexity of this, but I don't see a better way to meet the need, and I'm hopeful the complexity will just take a little getting used to, plus some good tool support to make tolerable...

Re the third:  I have many thoughts on that, but more than I can convey adequately in writing at the moment.  I'll consider recording a video to convey some of the nuances around this issue; it may indeed be that something else is needed or that the current approach is problematic, but going back to the open assignment is also problematic and breaks the parallel/holarchic construction of circle and role.  So, maybe we need to find a third solution entirely...

**Comment by brianjrobertson** [comment]
Actually, I think I did find the third way for that third issue, which will let me remove the constraint on role assignment while still avoiding those other issues I alluded to.  Working on it now...

**Comment by brianjrobertson** [comment]
Just submitted a major iteration on the functionality discussed in this issue, so I'm closing this issue so no one watches that old video or continues commenting based on the prior version - it's quite different now.  That said, for anyone that followed this thread, I'd love a review of this new iteration - please open new issues as-needed, or submit comments on the commit referenced above directly.
