### ISSUE TITLE
Remove Initial Structure section

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#235]
The special rules around Initial Structure seem unneeded; a Lead Link can already define whatever initial governance they want before they assign anyone else to roles, as they're the only Core Circle Member until someone else fills a role anyway.  Is there any use in calling this out explicitly in this section, or can this section simply be dropped entirely?

**Comment by Nick-Osborne** [comment]
One consideration I’ve noticed regarding issues like this is seeking  balance between the brevity/explicitness polarity: 

- there’s benefit in choosing not to explicitly articulate something to keep the constitution brief and avoid duplication; so this would be a reason for not including it, since as you say it’s an implicit consequence of other rules in the constitution. 

- the downside of this is that it may not be obvious to everyone, so may cause confusion and questions. So wanting to avoid this could be a reason to include it. 

Thinking about it like this, I’d want to manage this polarity to avoid duplication, keep it short and clear while avoiding confusion and questions by having too much implicit; and there could be multiple ways to do this. I expect you have your own heuristic to help you do this throughout the constitution. 

One possible way to integrate the meaning of what’s in 5.3 elsewhere, so that 5.3 could be dropped, could be to add ‘_and until_’ to 2.2.1 so that the last sentence of this article reads: 

‘However, this only applies to the extent that, _and until_, those Accountabilities and Domains have not been placed upon a role within the circle, or otherwise delegated.'

**Comment by leword** [comment]
If you're leaning toward brevity side of polarity Nick mentions, one possibility could be to leverage the plain-english version/"translation" to make some of the implicit things explicit.   (If v5 is enough shorter/terser/plainer than v4 then the original function of the "plain english" translation while still valuable isn't _as_ crucial, maybe it could be overloaded to provide some additional explanations, examples, and spell out implications.

**Comment by karilen** [comment]
I like having Article 5/somewhere that says something about the initial structure. I know that initial structure even after adoption can be created by lead link of any circle using any process they want. I wonder if something like initial structure capturing roles and existing actual operations would be helpful guidance. I would leave something in somewhere about pre-adoption and initial structure.

**Comment by oliviercp** [comment]
Without looking into the specific articles, I lean toward brevity over explicitness for the constitution. Especially if you make it explicit that LL can create roles as needed before there are other circle members. The work of explaining it in context can come from somewhere else -- like a "plain english" version or something else.

**Comment by brianjrobertson** [comment]
Decided to keep the one key sentence of this section that wasn't clearly covered by Lead Link authority and cut the rest; then integrated that one retained sentence into another section.
