### ISSUE TITLE
Allow forming circles that cross-cut the holarchy

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#236]
As the Lead Link of a Circle that has some processes and property to govern that are also highly intertwined with an external party (perhaps a circle within my organization, or one in another organization), I'd like to be able to form a new sub-circle in collaboration with that other entity and cede some control from each founding circle into it, yet without the new sub-circle needing to be fully "owned by" or contained within either founding circle, so that we can form joint ventures of various sorts to govern shared interests via a cross-cutting circle, without having to create a new entity and adopt the constitution separately for it.

(Note: This was originally discussed in Issue #61.)

**Comment by julianeroell** [comment]
Yesyesyes. :) (And then I'd like a feature in Glassfrog that supports this, and the possibility to be part of multiple organisations, and to interlink organisations on the glassfrog platform, and inter-operability with other organisational-structure-tools and... oh, out-of-scope for _this_ discussion! ;-))

**Comment by pscheuerer** [comment]
I really like this! Kind of like a Cross Link on steroids. This would allow
for a really elegant and effective structure for organizations that are
mainly project-based. I can absolutely see a compelling case for using a
Governance structure as you describe it for our own client projects.

This would be even more powerful if it were supported by GlassFrog. I could
imagine this as a circle that “lives” in two organizations at once and this
circle would show up in each organizations Governance.

Have to think some more on this. Might raise some interesting questions
down the road.

-- 

Patrick Scheuerer, Partner


Xpreneurs is operating under Holacracy
<https://en.wikipedia.org/wiki/Holacracy> // See my roles
<https://app.holaspirit.com/public/xpreneurs/member/patrick-scheuerer/governance>
// See our public governance records
<https://app.holaspirit.com/public/xpreneurs>


XPRENEURS GMBH - enabling neXt level organizations

Gundeldingerfeld, Halle 8 // Dornacherstrasse 192 // 4053 Basel //
Switzerland


mobile: +41 79 674 82 97 <//+41 79 674 82 97> // web: <http://xpreneurs.co/>
xpreneurs.co // skype: patrick.scheuerer


Connect with us on: Facebook <https://www.facebook.com/wearexpreneurs/> //
Twitter <https://twitter.com/xpreneurs> // Google+
<https://plus.google.com/+XpreneursCo> // LinkedIn
<https://www.linkedin.com/company/3365337>

On 17 February 2018 at 17:58:04, brianjrobertson (notifications@github.com)
wrote:

As the Lead Link of a Circle that has some processes and property to govern
that are also highly intertwined with an external party (perhaps a circle
within my organization, or one in another organization), I'd like to be
able to form a new sub-circle in collaboration with that other entity and
cede some control from each founding circle into it, yet without the new
sub-circle needing to be fully "owned by" or contained within either
founding circle, so that we can form joint ventures of various sorts to
govern shared interests via a cross-cutting circle, without having to
create a new entity and adopt the constitution separately for it.

(Note: This was originally discussed in Issue #61
<https://github.com/holacracyone/Holacracy-Constitution/issues/61>.)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/holacracyone/Holacracy-Constitution/issues/236>, or mute
the thread

**Comment by LouisChiquet** [comment]
When you talk about this, you're talking about two (or more) Organisations? As you say “without having to create a new entity and adopt the constitution separately for it.”.

If it's within 1 same company, I don't see why if you “I'd like to be able to form a new sub-circle in collaboration with that other entity and cede some control from each founding circle into it” not to further clarify the domains of the two Circles to create a new one? Like instead of “Wine” domain, you clarify the domain by proposing “Provence, Bordeaux, Gascogne Wine” and the other would be “Bourgogne Wine”? Or I'm totally out of subject? A concrete case would be enjoyable, so for example the Eco-System Circle, currently in HolacracyOne's Holarchy, you would like it to be “out” of the Holarchy, or be “integrated” in multiples Holarchies? Thanks in advance for the clarifications.

**Comment by brianjrobertson** [comment]
@LouisChiquet I suspect the main use-case will still be within one company, although across two is also possible.  There are certainly many cases where just clarifying the boundary between two sub-circles would meet a need, but this feature is for cases where that doesn't meet the need, such as where those two circles aren't under the same single circle, or where there's no need to bother a broader circle because it's an implementation detail of how a role wants to self-organize.  For example, four roles in four totally different circles that all participate in one overarching process together might want to group together in a circle to govern that shared process, while still retaining their autonomy and the rest of their function in the main holarchy.  For example, in H1, we have a regular need for our Marketing Maven role to work closely with a few GlassFrog roles, but Marketing Maven is in a different circle (for good reason - there's a lot of connection points for it in that circle too).  So, that Marketing Maven role and those GlassFrog roles may want to voluntarily come together to govern something together, such as the process for releasing new features to our user base, so feature releases and marketing communications about them can be better coordinated.  While those roles can certainly just meet together operationally and make whatever decisions they want, it's possible they may want more than this - they may want to voluntarily subject themselves to a governance process with the other roles, in exchange for the other roles doing the same, for the mutual benefit of the parties.

**Comment by brianjrobertson** [comment]
My current thinking for implementing this:  Allow a group of roles to form a Circle (with no Super-Circle and no Circle Leads) by mutual agreement of the roles (no governance required for this part); each of the roles is then automatically invited to show up in the new circle.  The agreement to form it needs to clarify the purpose of the circle and any domains on what it can govern, from among what the founding roles already control.  Then, the new circle can govern those domains for that purpose, and govern the founding roles linked in via policies (not by editing them), or create its own new roles.  Any of the founding roles can withdraw from the agreement that formed the circle at any point, at which point anything they delegated to that new circle to control is automatically and immediately undelegated, and any policies of that new circle no longer apply to them; and the new circle can't limit this right (although a Policy in the role's originating circle can).

Thoughts?  What am I missing or not thinking of here?

**Comment by LouisChiquet** [comment]
The fact of being able to do tactical meetings with any role of the org and on the regular basis you want doesn't solve this? Knowing that the [1.5](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#15-circle-members) allows to invite external roles to Governance meetings, so that would allow for instance automatically invite the said roles you want to specific Governance meetings you organise to impact both Circles in both ways?

I'm just questioning as you referred this morning to Cross-Link to be “super-complicated” for little value.

**Comment by brianjrobertson** [comment]
Okay, I'm about to submit a really major change to enact this, with substantial implications.  I'd really love extra eyes on this to find edge-cases I haven't considered, and to generally help ensure I haven't accidentally broken something.

**Comment by oliviercp** [comment]
Now referring to this committed change: https://github.com/holacracyone/Holacracy-Constitution/commit/b6c099617cefc4633b62e7b0af55bc340beb59a7

 @brianjrobertson line 93 of the new version, the first part of the sentence seems convoluted: 

> Any Circle Member of a Circle inside a Role may call for the selection of a **"Rep Link"** ...

You mean a circle member of a circle may call for the selection of a Rep Link, same as v4.1, right? If I understand correctly, then I don't understand the value of adding "inside a Role" — it makes the sentence overly complicated IMO, I had to read it several times to get it. Why not just say "Any Circle Member of a Circle may call for..."?

**Comment by oliviercp** [comment]
Other than that, more general feedback: 

- The role linking process defined in article 1.3.3 seems similar to Cross Links in v4.1, right? I'm curious why you try not to call them Cross Link. Is it because a role linked into another circle is not a new role, and therefore you don't want a separate construct for it? I could see that. On the flip side, it makes the text of the article more difficult to follow, and I'm wondering how a circle is supposed to keep track of which roles within it are defined by the circle itself and which ones are linked roles. For that the concept of Cross Link was useful to make that differentiation. Unless you're simply renaming "Cross Link" into "Linked Role"? Either way, a construct seems useful to differentiate roles that are linked from elsewhere and roles that are 'native' to the circle.
 
- it looks like a Circle created by two roles doesn't have any position in the holarchy, correct? If so, it introduces complexities, not the least of which being how it's going to be represented in GlassFrog, but I understand it's an implementation issue that doesn't need to be solved here. However, it's such a major change compared to how circles have been used so far, and compared to how the holarchical circles are going to work, that I wonder if we shouldn't be more explicit on the non-holarchical nature of these circles. Not sure the best way to do that; it could be by introducing a new construct for them and giving them a name, or simply by explaining how they don't hang from anywhere in the holarchical tree, or both... But it seems to me that something would be useful

Lastly, thinking out loud here... I've seen organizations create circles made of cross links from other circles, which would seem to be good candidates for these new Lead-less circles

For example, a company has several consulting circles pretty much all doing similar consulting work but in a specific market. The company has consulting branches in various US cities, each having their own circle. They're all sub-circles of a broader "Consulting" circle that can maintain some consistency across the consulting branches through governance at the Consulting circle level. In that Consulting circle, they also created new sub-circles that are made of Cross Links from all the branches, and focused on specific aspects of the business, e.g. the sales process. Their goal is to implement standard processes across branches and to learn from each other. That's the context. 

Thinking how it would work with the Lead-less circles now: all branches (sub-circles) could decide to create a Lead-less circle with a purpose focused on specific processes (e.g. sales process), essentially achieving the same thing as what they're doing with Cross Links now. But since the goal of that circle — let's call it the "Sales Process" lead-less circle — is to keep consistency across branches, they need to be able to impact the branches sub-circles in how they handle their sales process. So they would need each branch to delegate their sales process domain to that Sales Process circle. But what if one branch refuses to do so?  The Consulting circle needs to expect all branches to follow the process defined by the Sales Process circle, but how can they mandate subcircles to delegate their domain accordingly? They could create a policy at the Consulting level mandating all branches to follow it, and branches subcircles would have the choice to link into the Sales Process circle or not, but either way would be bound by its governance. But Consulting would also want to ensure that a Sales Process circle exists so this policy can be enacted, so it wouldn't want to leave it to the branches subcircles to create this lead-less circle - it would want to mandate it through governance, right?  But in that case, the only difference between a Sales Process lead-less circle described above, and their current circle made of Cross Links, is that the lead-less circle would have no Lead and would not technically be a Consulting circle subcircle. Is there any advantage to that? It seems just more complicated for little added value (if any?). It looks like it's a case where a lead-less circle doesn't really make sense here, and they'd be better off simply creating a sub-circle to the Consulting circle, and having Cross Links like they have now... which is fine. Thanks for rubber-ducking.

**Comment by brianjrobertson** [comment]
@ocompagne See my submit linked just above; do you think that adequately addressed your first comment above?

**Comment by brianjrobertson** [comment]
@ocompagne, re:

> The role linking process defined in article 1.3.3 seems similar to Cross Links in v4.1, right? I'm curious why you try not to call them Cross Link. Is it because a role linked into another circle is not a new role, and therefore you don't want a separate construct for it? I could see that.

Right, and that is indeed why - it's not a separate role, just a role invited into another circle.

> I'm wondering how a circle is supposed to keep track of which roles within it are defined by the circle itself and which ones are linked roles. For that the concept of Cross Link was useful to make that differentiation.

I figure we'll just mark them as "Linked Roles" or something in GlassFrog; this seems like a support tool issue to me, rather than something requiring a definition in the constitution.  Please do debate if that seems off to you.

> it looks like a Circle created by two roles doesn't have any position in the holarchy, correct? If so, it introduces complexities, not the least of which being how it's going to be represented in GlassFrog, but I understand it's an implementation issue that doesn't need to be solved here.

Yes, that's right, and it definitely does introduce a new challenge for GlassFrog UX & visualization.

> However, it's such a major change compared to how circles have been used so far, and compared to how the holarchical circles are going to work, that I wonder if we shouldn't be more explicit on the non-holarchical nature of these circles. Not sure the best way to do that; it could be by introducing a new construct for them and giving them a name, or simply by explaining how they don't hang from anywhere in the holarchical tree, or both... But it seems to me that something would be useful

I was wondering about this as well, but adding a defined term would be weird, since the Constitution doesn't actually need to reference it anywhere - it behaves just the same as a circle within the holarchy, with no special treatment other than what's already captured in the short text of §1.3.4.  We could instead explicitly call out something more about how it doesn't fit in the holarchy, but what would we say, beyond what's already said (that it has no Super-Circle and gets dissolved immediately if it has no Roles linked into it)?

**Comment by chrcowan** [comment]
@brianjrobertson I'm having trouble following all of the threads here, but I'd like to at least share more slightly uninformed opinion by saying that I generally agree with what @ocompagne said here, "the only difference between a Sales Process lead-less circle described above, and their current circle made of Cross Links, is that the lead-less circle would have no Lead and would not technically be a Consulting circle subcircle. Is there any advantage to that? It seems just more complicated for little added value (if any?). It looks like it's a case where a lead-less circle doesn't really make sense here, and they'd be better off simply creating a sub-circle to the Consulting circle, and having Cross Links like they have now... which is fine." 

Overall though, I'd be able to contribute more from a live discussion.

**Comment by brianjrobertson** [comment]
@chrcowan Yeah, I spoke with Olivier about that real-time; yes, in that example, it's not much different and there's no value add from this new capacity; but in other examples there are - it's just not a good one for illustrating where this new capacity would be useful.

My big question now Chris is the last part in my message above to Olivier; any thoughts on that?

**Comment by rebeccabrover** [comment]
@brianjrobertson I'd like to check my understanding here before I comment.

1. If I have role and you have a role and Chris has a role and we each own a domain in our role and they are all in different circles but there is value to us forming a circle to cross-work more easily, and there is no standing Policy in any of our original circles prohibiting it, we can form a circle, yes? (I think the answer is yes.)

2. Structurally, on what boundary does it sit? Would it be like a three way Ven diagram with our cross-circle team in the middle and the three original circles on the edges? (I do not envy GlassFrog right now)

3. You, me and Chris could make additions and subsequent changes to those additions through our own cross-circle governance but can't change anything built by the original circles? (I think the answer is yes.)

4. Could we grant access to the domains of our roles to each other in the cross-circle? (I think the answer is yes because if I have a domain, I can already do that).

If my understanding is correct, and the visual and UI challenges are totally for someone else to figure out, I love this in concept and think it solves an issue of formalizing (likely temporary but maybe permanent) cross-circle work which happens often but I think the language of the article still needs some tweaking. I'm a pretty smart cookie (and long-time practitioner) and I still had to read this about a dozen times to even get to where I could ask the questions. I imagine translation to any other language would be even more nightmare-ish.

I think I might need a RT conversation to offer grounded suggestions about language changes but it's the first big change I've ready that did not seem to make things more clear even though I really like the idea.

**Comment by brianjrobertson** [comment]
@rebeccabrover:

> If I have role and you have a role and Chris has a role and we each own a domain in our role and they are all in different circles but there is value to us forming a circle to cross-work more easily, and there is no standing Policy in any of our original circles prohibiting it, we can form a circle, yes?

Yes.

> Structurally, on what boundary does it sit? Would it be like a three way Ven diagram with our cross-circle team in the middle and the three original circles on the edges?

It doesn't really sit on any boundary - you'd almost need an extra dimension to graph it.  It's more like the circle is just a new entity, like a new company, and then the roles are linked into it and thus in two places at once, like a wormhole or something.

> You, me and Chris could make additions and subsequent changes to those additions through our own cross-circle governance but can't change anything built by the original circles?

Yes.

> Could we grant access to the domains of our roles to each other in the cross-circle?

Yes.

> I love this in concept and think it solves an issue of formalizing (likely temporary but maybe permanent) cross-circle work which happens often but I think the language of the article still needs some tweaking.

I'd love any language suggestions!  I'll queue up an agenda item for a real-time convo.

**Comment by LouisChiquet** [comment]
This means that from now on, there are 3 definitions of Circles: Anchor Circle, Circle issued from a role, and now “Circle across roles” (which isn't a role so) which seems to create more complexity for not a simpler cause.

Lots of our clients have meetings between “circles/roles”, for instance the Sales Circle and the Supply Circle, to just synchronise and manage actions, which is now even more possible and easier given the new definition on how a tactical meeting can be called (knowing that his mean, GlassFrog will have to support the possibility of giving actions to roles which are in various circles). I don't see why, with 5.0, this wouldn't become a cross Circle? Like the many many work meetings that exist generally in companies, and in the end basically have cross Circles throughout the organisations in many direction, which are just in the end, ways of synchronising.

So it's making a rather big shift in how the Circle was seen, as a role can decide alone to become a circle, and two roles across circles can decide to create a circle. This seems to go a bit everywhere. Now I don't have actual data, as 5.0 isn't turning yet, but see strong issues (as for instance, in a client company, they talked about “circle meetings” for just work meetings between two former services, as the word circle was cannibalised, and would be even more with this change in my opinion and from the facts I have).

Now maybe it's good, but I still don't see the positive effects, knowing that tactical meetings can be done without any issues now with 5.0, and that if you have integrated the holarchy notions it's actually way easier to manage services offers (accountabilities) and domains rather then dealing directly with role etc. within the sub-circle alongside the new “cross link” section which would solve most cases.

Getting concrete examples of how this would allow a more efficient and productive business for the company would really help see the positive effects and aspects, which I don't see for now.
