### ISSUE TITLE
Propose rephrase of "Next-Action" Definition

### ISSUE THREAD

**Issue by MiekeByerley** [holacracyone/Holacracy-Constitution#25]
Suggest a rephrase to accommodate the (DO, Delegate, Defer) aspects of Next-Actions. 

Suggested rephrase: 
“Next-Actions”, which are actions that could and would be useful, to process  within the appropriate time, at least in the absence of competing priorities; and

**Comment by brianjrobertson** [comment]
Hmm, not sure what that's adding over the current phrasing..?  What's covered by that suggestion, which isn't covered by the current text?

**Comment by MiekeByerley** [comment]
The original read: “Next-Actions”, which are actions that you could execute immediately and that would be useful to execute immediately, at least in the absence of competing priorities; and

The word "you" in the sentence limits the delegate aspect, and the word "immediate" limits the defer aspect. When I read the sentences I try to read them from the perspective of someone that is unaware Holacracy has a big influence from "Getting Things Done". I did wonder whether it might be an idea to also add the (DO, Delegate, Defer) in the sentence after actions, for clarity.

**Comment by brianjrobertson** [comment]
This is intentional and desired as-is; a delegated action is not a Next Action for you, and, with Holacracy, you don't necessarily have a duty to track them (the person delegated to does).  And something you _could_ do immediately is part of the definition of a Next-Action (in Holacracy and GTD both), even if you choose to defer it...
