### ISSUE TITLE
Changing an Objection Validity Criteria

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#26]
I'm considering tweaking an objection validity criteria, and I'm trying to assess: (a) should I save this to consider for v5.0 instead of v4.1, and (b) does this change add greater clarity and distinction-making capacity, without breaking anything in the process?

The candidate change is from this objection validity criteria:
(c) The Tension is triggered by presently known data or events, without regard to predicted data or events. However, relying on predicted data or events is allowed when no opportunity is likely to exist in the future to adequately sense and respond to the predicted situation before significant impact could result.

To this language instead:
(c) The Tension is triggered immediately just by facts known at present or recent history, without regard to a prediction of what might happen in the future. However, relying on predictions is allowed when there won't be a reasonable opportunity to sense and respond in the future before significant impact results.

Thoughts or feedback anyone?

**Comment by diederickjanse** [comment]
I think this adds greater clarity, and I don't see any significant changes from how I've interpreted and tested this criterion. If that's true for others, I think it would be fine as a clarification, i.e. v4.1...

**Comment by oliviercp** [comment]
I really like the new 2nd part of the sentence, “_… without regard to a prediction of what might happen…_” ; adding "_what might_" helps explain what "_prediction_" means.

I also like replacing "_data_" by "_facts_" as it it more concrete. I’ve seen people think of "_data_" as metrics...

**I suggest: "_(c) The Tension is triggered just by presently known facts or events, without regard to a prediction of what might happen in the future._"**

I like keeping the first part of the sentence the way you had it originally, because it's easier to hold in mind IMO. The new version adds several dimensions to hold in mind all at once to understand the criterion: 1) a temporal condition for tension triggering ("_immediately_"), 2) a limiting factor ("_just_"), 3) and two temporal conditions for the validity of facts ("_at present or recent history_").

I don't think 1) adds much clarity (it seems to point to criterion b) for valid objections), 2) is indeed an clarifying addition, and I think 3) is covered in the original version by "_presently known_", and therefore adds unnecessary complexity; the phrasing reads a little off too, because you couldn't say "_known at ... recent history_"

**Comment by brianjrobertson** [comment]
Thanks Olivier, that's very helpful!  I think I'm mostly sold on your edit then, unless someone else chimes in very soon...

**Comment by brianjrobertson** [comment]
Change submitted...

**Comment by bernardmariechiquet** [comment]
Hope this is not too late - 
I would suggest to keep the first sentence as it is:
• I love "Facts" and this covers events as well - events are just facts. Adding events juts creates confusion on the meaning of facts. An event is a fact, so why adding it in the question?
• I love "known at present or recent history" - this helps the potential objector grounding his answer by projecting him in the present - stating the recent history helps grounding in the present
• I do appreciate the "immediately" - this will help the potential objector to sense if his tension is based on facts or mental analysis :)

I would also change the second piece - i think "reasonable opportunity creates confusion at least for me and don't see the value added there. And i would tweak a bit to take the best of both...

As a conclusion, I suggest "(c) The Tension is triggered immediately just by facts known at present or recent history, without regard to a prediction of what might happen in the future. However, relying on predictions is allowed when no opportunity is likely to exist in the future to adequately sense and respond  before significant impact results."

And for me this could be included in 4.1. Add clarity and more tips for potential objector

**Comment by brianjrobertson** [comment]
I snuck in one more tweak to the second sentence based on your feedback Bernard Marie; I left the first sentence as-is, as I think we need some more discussion to integrate perspectives there - something to consider further for 5.0.

**Comment by bernardmariechiquet** [comment]
Go to you & looking forward to chatting for 5.0
