### ISSUE TITLE
Clarify responsibilities and authorities of Role Supporters

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#264]
My objective here is to open a space for deepening and integrating different perspectives and polarities in regard with The Role Supporter concept.
During our session (see end of [recording](https://vimeo.com/281290865) password if any would be igipartners), this subject was addressed - as for instance it will be weird for an executive assistant being Role Supporter in most of the Executive's Roles to act upon *Processing Tensions" in section 2.2.1 or *Processing Purpose & Accountabilities" in section 2.2.2.
So section 2.2.1 and 2.2.2 should probably be separated from the following sections 2.2.3 to 2.2.5 to allow such use case.

In addition to that, it would equally be weird for such Executive Assistant Role Supporter to get the authority to take any action or make any decision to enact Role'sPurpose or Accountabilities, as defined in section 2.1, wouldn't it?

I think this concept of Role Supporter need further reflection and use cases as this is a huge shift in the mission of Holacracy to evolve relationship to power, and at the same time I do think such concept is probably needed by reality, at least temporarly during the transition.

**Comment by brianjrobertson** [comment]
It makes sense to me to remove the duties of processing tensions and processing purpose/accountabilities.  I think the authority is important to keep, and not a big deal, because the Role Lead could always define a Policy to limit that authority however might be needed.  However, I think that does bring up a question of whether a Role Supporter should be invited into the governance process for that Role's internal Circle (as the current dev version defines), or whether that's better limited to just Role Leads.  Thoughts?
