### ISSUE TITLE
Remove option for de-minimis role assignment

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#277]
The option to exclude from governance for a de-minimis role assignment seems obsolete in v5.0 and just adding needless complexity.  It's only use-case (to my knowledge) is just to ensure there aren't too many people attending the governance meetings of a circle, which will already be achieved more substantially by #227 and perhaps #226.  On top of that, the addition of Role Supporters as an assignment option gives another pathway for a similar effect as the de-minimis assignment.  Thus, I'd like to remove this needless complexity, unless someone has a compelling (and grounded) use-case that isn't covered by these other changes?

**Comment by bernardmariechiquet** [comment]
I fully agree to remove the "de-minimis" option but I would still leave the option for the Role that controls assignment to exclude from Governance without specifying the context/situation. I have use-cases where people are not yet ready to process tension in governance, and as a Circle Lead I'd like to be able to exclude this person from Governance even if this person has a full time job into such Role.
So ok for removing the de-minimis feature AND I'd like to add the option to exclude from governance 
by leaving the judgment to do so to the Role that controls assignment.

**Comment by brianjrobertson** [comment]
Hmm, that's not allowed in v4.1 for good reason I think, and I wouldn't want to allow a role-assigner to just autocratically do that - sounds like it'd give a way to break the whole tension-processing mechanism.  At most I could maybe see it allowed by a governance policy, but definitely not via an autocratic decision in a role assignment.  Can you give more context on why you think this is important (and not dangerous)?

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I know this is not allowed in 4.1 and I should probably have opened a new issue to further explore this. In some contexts where people are not self-confident enough in bringing tensions or propose something (and there are many of them in the manufacturing and retail sectors), they do not process their tensions, bar is too high for them. They would appreciate not going to governance and Lead Link process their tensions until they feel confortable to govern themselves. There is no danger to break the whole tension-processing mechanism in such cases because they already don't process their tensions. I think this would ease for certain type of people the transition.

**Comment by brianjrobertson** [comment]
Hmm, yeah, consider opening a new issue for this one, seems like a potentially big consideration.
