### ISSUE TITLE
Rename "Rep Link" to something else?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#280]
Given the recent dev-version changes, as a rename of Rep Link now practical and useful?  If so, should it be "Role Rep", "Circle Rep", "Governance Rep", or just "Representative"?  Before answering, please take a look at the current dev-version of the constitution and where/how Rep Link is introduced/defined; given that, do you think it makes sense to change it, and if so, to what?

**Comment by leandroqm** [comment]
Yes, I do feel that "Rep Link" needs an adjustment to be better understood on the dev version.
In terms of usefulness, since the dev version now carries the term 'Circle Lead', 'Circle Rep' would be ideal as it carries a coherent message.
In terms of the most practical option, 'Governance Rep' is the one I would go with because it further explains what the role really does.
If we could add some clarity to its Purpose to make sure Governance is better indicated, I would go with 'Circle Rep'.

My suggestion is for such an edit to Circle Rep's Purpose is simple:
Purpose: _Governance_ Tensions relevant to process in the broader Circle channeled out and resolved.

**Comment by tylerdanke** [comment]
Representative for the win.

**Comment by lmmathurin** [comment]
Sometimes people prefer shorter version...but I think in the Constitution using the complete wording is better than a shortcut.  It doesn't prevent to display a shorter  version in an app.

Circle Representative
Gouvernance Representative (+1 personal preference)

**Comment by sitron** [comment]
After reading the dev version of the Constitution i must admit i don't really understand where you want to go with this emphasis on Governance for Rep Links. Might be that i'm just still "too much into" 4.1.
Anyway, i would rather go with "Circle Rep" than "Governance Rep" as the latter seems to imply that what you are representing is Governance rather than the circle that elected you.

**Comment by pamil** [comment]
Circle Representative sounds more straightforward to me.

**Comment by matthewgilliland** [comment]
+1 for Circle Representative

**Comment by LouisChiquet** [comment]
I'd go simply with “Circle Link”, as the Rep Link isn't a representative at all in the end.

**Comment by chrcowan** [comment]
Given the change from "Lead Link" to "Role/Circle Lead," I think "Circle Rep" fits nicely because it removes the "link" word which no longer conveys what it used to (i.e. parity) since "Lead Link" is changing.

**Comment by brianjrobertson** [comment]
I'm down to deciding between Circle Representative and the short version, Circle Rep.  So:  Should I shorten it?  Vote thumbs-up if so; if you think I should stick with the full word, vote thumbs-down.

**Comment by lmmathurin** [comment]
thumbs-up

**Comment by brianjrobertson** [comment]
Okay, I'm still leaning towards the short version; do any of you who feel strongly we should keep the full version ("Circle Representative" vs. "Circle Rep") want to offer an argument why?

**Comment by julianeroell** [comment]
I work with groups that include many people who do not speak English as their mother tongue. "Representative" would be clear and understandable for them, whereas "Rep" would mean nothing and be a new term to learn. 

In Germany, "REP" is the official short name of the far right wing political party [_Die Republikaner_](https://en.wikipedia.org/wiki/The_Republicans_(Germany)).

**Comment by MaxTranced** [comment]
Most translators will have to use the long version, as many languages are not as flexible as English w.r.t. shortening words. So: for consistency with translations.

**Comment by matthiask** [comment]
I don't feel too strongly about this but the full version better explains what the role is all about. There's just one less step required towards understanding. I know that ship has sailed but if "Circle Representative" is too long then you might want to reconsider "Representative" instead of "Circle Rep". After all, what else is there to represent than the circle?

Shortening the role could still be possible in daily practice.

**Comment by LouisChiquet** [comment]
I'm curious on the process used to update the Constitution? Knowing you've asked for a vote which overwhelming pushed in favour of “Circle Representative”. So, is the process simply we throw inputs at you and you decide or it's through a vote, or? I know @brianjrobertson you have a role for that, but clarity on how it works would be useful.
Thanks in advance for the clarifications as it can be quite frustrating as it seems to depend on the issue.

**Comment by klaas1979** [comment]
We are doing a lot of internal Trainings and do shorten the role name right now. But I would recommend the long name, because the old name was neither understandle fully spelled or shortened. So we need to explain it all the time. The new long name would be self explanatory and will be shortened in daily doing anyway.

In my opinion a constitution should not use shortened words or acronyms without providing the long word before hand. Maybe you can use it like Circle Representative (Circle Rep) and then only use the short version?

**Comment by brianjrobertson** [comment]
@LouisChiquet:  The process is currently "I decide in my Constitution Steward role", after collecting input.  When I poll the community, it is in no way me deferring to a democratic vote to make a decision - voting seems a horrifically bad way to make most decisions to me, and I'd fully expect to get thrown out of my role if I deferred my leadership to a vote like that.  And with only 9 responses to the poll, I wouldn't call any result "overwhelming" - more like "not statistically significant" regardless of the answer.  That said, I do take it as 9 different perspectives that I value, and I definitely do consider those perspectives in my decision-making, especially when one comes with a compelling argument.

**Comment by ericdgraham** [comment]
I like Circle Representative. Why not start with the full terminology and then use short-hand going forward? State the first instance as: Circle Representative (Circle "Rep"). And then use Circle Rep going forward.

**Comment by brianjrobertson** [comment]
I just changed "Rep Link" to "Circle Representative" in my local version, and as I looked at the impact, I don't think it's a good idea - it's just too cumbersome a phrase, with too many syllables (from 2 to 7).  I can't imagine anyone used to "Rep Link" will bother switching to the new language given how much more cumbersome it is, and I think that's an issue; and for the new folks, it's just too much to hold and say, which I imagine will make Holacracy itself feel more cumbersome.

So, I'm either keeping "Rep Link", or we need to find something better that's less than 7 syllables.  We could use "Circle Rep", but I don't think that's a notable improvement from "Rep Link", so I'd rather go with inertia and stay where we are over that (I think).  And the more I think about it, the more I think "link" is actually a decent word for this (it's "Rep" or "Representative" I have more trouble with).

Or perhaps there's something else entirely.  Circle Liaison maybe?  2+3 syllables, although Liaison rolls off the tongue in almost 2, so more like 4.5 syllables.  Not great, but the definition of liaison is really fitting and far better than "representative": Liaison, n., "a person who acts as a link to assist communication or cooperation between groups of people".  Or maybe Liaison Link, but that sounds weird and more complex/jargony to me.

Any thoughts on Circle Liaison over just keeping Rep Link?  Or any other ideas?

**Comment by julianeroell** [comment]
"Liaison" sounds wrong to me: the word "liaison", for me, implies bi-directionality. This is something different from the monodirectional function that the Rep Link is currently defined as.

**Comment by julianeroell** [comment]
As for the "Circle Representative": I _already_ speak of a "Representative" rather than using "Rep Link" because it just sounds so wrong in German. Could it be a solution to call the Role "Circle Representative" and then abbreviate it with "CR"? Or is that jargon-y again? Sorry I don't have a better idea at the moment. :-/

**Comment by ericdgraham** [comment]
I prefer Circle Rep over Rep Link because of the symmetry with Circle Lead.

**Comment by chrcowan** [comment]
I'd pitch to just keep Rep Link. Seems like there isn't enough tension (or data) to support changing it.

**Comment by rebeccabrover** [comment]
@brianjrobertson After reading both the dev version and the thread, I do wonder if the potential gain in clarity of changing Rep Link to anything longer is worth the additional syllables which lend to translation burden and possible further explanation. If Rep is already the generally accepted shortened form of Representative (which it is), I don't see a need to spell it out.

@martinaroell I really appreciate your thoughts on translation. I think about that often. If you are verbally using Representative rather than Rep Link, you are simply using the full form of the intended word and if that helps you as a practitioner and coach, I don't see harm in it. If I were coaching one of your meetings and I heard you say Representative rather than Rep Link, I wouldn't make an intervention _unless_ I thought you had a misunderstanding about the role, which it doesn't seem like you do. Is there a reason you can't shorten Rep Link to "RL" the same way you are suggesting using CR for Circle Representative?

That being said, a reason I do see a benefit to changing to Circle Rep is the use of similar consistency to the names of the roles which sit on the membrane of the Circle. In v.4.1 we have Lead Link and Rep Link. Here we would have Circle Lead and Circle Rep. I think the matched set of roles with places in dual circles is an easier concept to grasp for novice practitioners if the names have something in common. It's a written visual pattern providing a mental clue in the same way the steps of a governance meeting where each person speaking in turn is identified as a round. It's a pattern the brain is likely to pick up and metabolize more easily than just a process to be memorized.

Because I can't help myself, of course I thought about alternatives and the one I like best is Circle Delegate but I think that might cause more confusion than it's worth due to the political connotations to the word in a variety of languages and cultures.

Summary - pitch for Circle Rep. If the change is worth it, better now with many other changes in a dramatically different release than the change later in a smaller release.

**Comment by brianjrobertson** [comment]
Okay, I'm down to two options: either keep Rep Link or switch to Circle Rep.  On one hand, I like the parallel of Circle Lead and Circle Rep.  But I have a new concern about that: it's not actually a parallel and could be confusing.  A Circle Lead is only a Circle Lead within the circle; in the super-circle, they're actually a Role Lead of a Role, and that's where the Rep Link shows up to do their work - they're also representing the Role within the Super-Circle.  So the parallel is really between the Role Lead for a role and the Circle Rep for that role.  Or said another way, the Circle Rep shows up in the Super Circle to represent the role just like a Role Lead would.  Is that potentially confusing?  Rep Link doesn't have this problem, since it doesn't use "Circle" or "Role" in the name.

So, one more poll:  thumbs-up to make the change to Circle Rep anyway, and thumbs-down to keep Rep Link and not change this at this point in time.

**Comment by lmmathurin** [comment]
Thumbs down since it's not adding clarity or enhance significantly the
current wording.

**Comment by ericdgraham** [comment]
In that case, I would keep it Rep Link so as to avoid potential confusion, since they aren't in fact parallel.

**Comment by MichaelDeAngelo** [comment]
@brianjrobertson I think Rep Link is actually less confusing than Circle Rep given Circle Lead. Although I can see the appeal of the parity with Circle Lead and Circle Rep as word/phrase pairs, I believe the two would introduce ambiguity and confusion in early practice. I can anticipate the question "Wait. Which one is which again?"

**Comment by bernardmariechiquet** [comment]
@brianjrobertson may I suggest a third option in addition to Rep Link and Circle Rep: simply "Representative" or "Rep".  That would be consistent IMO with the name of the two roles, facilitator and secretary, which are defined by themselves. No need to include circle into their name. Why wouldn't be the same for Rep or Representative. No need to refer either to circle or to linking, which are other structures defined elsewhere in the constitution.
The notion of link in the expression "Rep Link" creates confusion because there is already a piece definig linking in section 1.3.3. Unless we are able to elegantly cover these two notions "Linking into circles" and "Rep Link" with the same mechanism, which I do not know how to do so far.
In the meantime, Circle Rep is not quite suitable for the reasons I agree on you mentioned previously. Or one should call it Role/Circle Rep as defined in appendix A, which be a fourth option but certainly a too cumbersome one.
So could we not simplify things, in the same way that we have a Facilitator and a Secretary, we may also have a Representative or a Rep with its definition in Appendix A.

**Comment by brianjrobertson** [comment]
Okay, polling again: give me a thumbs-up if you prefer "Representative" over whichever other option you voted for in my prior poll above ([here](https://github.com/holacracyone/Holacracy-Constitution/issues/280#issuecomment-504108099)), or thumbs-down if you like the other option better.  And if you didn't vote in the prior poll, I'd love your input there as well, even if you prefer Representative.

**Comment by chrcowan** [comment]
Interesting. While I like the parallelism of having just "Representative" which mirrors roles like "Secretary," there is something different about it, which may mean it should be treated a little differently, which is that the work of the former Rep Link role, while technically always circle-oriented (i.e. a circle representative) in practice it is often experienced by someone bringing a tension to them as more like a role representative (i.e. it _feels_ basically like they're representing my role's tension), meaning that calling it "Rep Link" or "Circle Rep," is actually a helpful tag/reminder for everyone that the other thing the role is representing isn't another role, but the circle.

Now, I don't know the value of that compared with the benefits, but I do think you'd lose it if you just go with "Representative."

**Comment by LouisChiquet** [comment]
Totally agree on such @chrcowan, however I failed to see an idea that seems to be supported by all to better express and reflect the role (I like Circle Link personally to move out of representation, as it's not exactly such work that is done, but doesn't seems to take on). And Representative seems to be shared, therefore I'd say it's good enough to try, always remaining open to evolve that in the future!

**Comment by brianjrobertson** [comment]
Thanks for the feedback all; this was a really tough decision, but I'm going with Circle Rep to avoid the issue @chrcowan points out, and to avoid confusion with other places in the constitution that reference "representative" or "representing" (e.g. the representatives of a Role in a Governance Meeting, which also includes its Role Leads).
