### ISSUE TITLE
Allow custom check-in and closing round format even for Governance?

### ISSUE THREAD

**Issue by cassus** [holacracyone/Holacracy-Constitution#282]
The Tactical format can be changed already, and I sense that Governance Check-in / Closing round could also be adapted to better support the companies culture. I don't see what harm would come from allowing a different check-in our closing round format for Governance, and only having the core IDM part fixed.

**Comment by brianjrobertson** [comment]
@cassus Do you have a concrete case of an organization that wants to be able to change these, or are you coming from a theory that it would likely be valuable/useful to some?

**Comment by cassus** [comment]
At one of the companies I work with there's a strong culture of human connection. The idea was to allow some reactions during Check-in and Closing rounds so it's not just data and respect but also connection. I'd like the opportunity for circles to experiment with this within the bounds of Holacracy.

**Comment by brianjrobertson** [comment]
Hmm, that sounds like exactly the kind of change I think the constitution would be better off preventing in governance...  Anyone else have thoughts here?

**Comment by bernardmariechiquet** [comment]
I wouldn't go there as Governance Meeting is NOT about human connections but about the Org. and Check-in Round is transitioning into that new space which is not again about the people. And at the same time if an Org. would like to change the Check-in Round, why not? I can see sometimes where it may be difficult for people to dive in directly into such "responses not allowed" discipline from the very beginning of the process.  I would be then very cautious as we want this process to lean on discipline and opening the door to reactions during the Check-in Round could open the door for reactions out of process in further steps of IDM and make this one more difficult to facilitate.

**Comment by cassus** [comment]
@brianjrobertson I'm curious what is the harm in allowing circles to experiment with reactions during Governance Check-in?

**Comment by brianjrobertson** [comment]
Bernard Marie captured most of what I'd say; if you want some more elaboration or other perspectives on it, I bet you'd get a bunch if you asked on the CoP.

**Comment by julianeroell** [comment]
I would like to keep the (Holacracy / Governance) Check-In clean: People say what they need to say _in order to be able to begin the meeting_. Nothing more. 

I can see the appeal of more "culture", relationship-building and exchange in "check ins". The way we address the need for this is to drop in to meetings early and have - ritualised or non-ritualised - "check-ins" (I call them "arrivals") _before_ the official meeting starts. I can see many ways how this could be handled by organisational practise (and / or even roles that take some responsibility for this), outside of formal Holacracy Processw.

While I don't see immediate _harm_ that would come from allowing a modification of the Governance process, this seems to complicate the overall structure for me, making it less clear.

**Comment by cassus** [comment]
In today's Licensee meetup I had a talk with a bunch of people including Michael DeAngelo and Nick. We talked about our Facilitation practices, and most people said they allow some reactions depending on the situation, as judged by the Facilitator.
The enacted rule seems to be: "The Facilitator can stop any reaction" rather than "must stop all reactions".

Hearing this practice from experienced Hola coaches makes me think the written constitution is off from enacted practice on this point. No one in the call said it shouldn't be the Facilitators call what reactions to allow and I agree.

I propose changing the constitution to allow for this flexibility. What do you think?

**Comment by MichaelDeAngelo** [comment]
To provide an example: a person may share an experience they had over the weekend that has gotten them real excited and put them in a great a mood. Another person by react by saying "cool!" In some meetings the facilitator would shut that down because technically it's a reaction (although so is nodding. Another facilitator might allow it because it's additive to the space. I can see this as facilitation style. Although technically not allowed by the current constitution, in my opinion, if it adds to the space,  doesn't create discussion, or harm safe space then it fine. I also let it depend on the team maturity and current team dynamics. If it's a healthy, experienced, and supporting team dynamic I'm more likely to let it be. If there are team dynamic issues and inexperienced team I'm more likely to shut down the reaction.   Yes, it's governance but the meeting still involves humans.

**Comment by brianjrobertson** [comment]
@cassus I'm not seeing a gap between written rule and enacted practice, and I seriously doubt many coaches are allowing lengthy reactions - and if any are, I'd call that bad practice for good reason.  I suspect they were referring to what @MichaelDeAngelo is talking about; when it's a one-word reaction like that or something comparable, it's usually harmless, but either way the most expedient path for the facilitator to get back to process and thus honor the rules is usually to ignore it (although in a newer group sometimes I wouldn't ignore it even if it's actually less expedient - I totally resonate with everything Michael writes about that).  And ignoring it seems perfectly aligned with the constitution to me (if it's one-word or equivalent), because the constitution doesn't demand the facilitator jump in and clarify the rules, just generally hold to the process; and the only rule here in the check-in round is simply "responses are not allowed".  You could interpret a one-word comment more of an "acknowledgment" than a "response", and thus not even falling under that rule.  And even if you do interpret it as a "response", the facilitator is still holding to process as best they can by ignoring it if the response is done by the time they could stop it anyway.

**Comment by brianjrobertson** [comment]
Last call for anyone else who wants to pitch for this before I close it out...
