### ISSUE TITLE
Combine sub-sections of §1.2 (Role Assignment)?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#283]
I'm wondering if the constitution would be more or less readable if one or more of the sub-sections of [§1.2](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#12-role-assignment) were combined?  Thoughts?  Would it be better or worse if they were all collapsed into a single section, with just paragraph breaks between them vs. sub-sections?  What about if the first one, two, or three sub-sections were collapsed into the main section but 1.2.4 and 1.2.5 were kept as sub-sections; is that better or worse for readability?

I'd really appreciate your perspectives on this community!

**Comment by cassus** [comment]
My 2 cent is for collapsing 1, 2, 3 and keeping 4 and 5 as sub-sections

**Comment by ebabinet** [comment]
Brian - I have an alternate proposal for structuring this section so that I think it will flow better:

1) Remove this sentence from the first paragraph 'Anyone so assigned becomes the "Role Lead" for that Role". I think this sentence is not accurate as a non-Partner assigned would not be a Role Lead. Furthermore, it doesn't really define what a Role Lead is.

2) Keep 1.2.1 Eligibility as is.

3) Move "1.2.4 Focusing an Assignment" to 1.2.2

4) Have new 1.2.3 called "Role Leads and Supporters", which explains that any Partner assigned to a role becomes a Role Lead, and that a Role Lead is able to further assign Role Supporters (old 1.2.5). This section would also include the content from the old 1.2.3 about Default Role Lead. Question: is a non-Partner assigned to a role considered a Role Supporter? That's not clear in the current draft, so could be clarified.  One other question: in the current section 1.2.5 it says "A Role Supporter gains the authorities of the Role, but only holds **most** of the duties...", but I was not able to find any clarification of the "most" part in Article 2. Can you clarify what is meant by "most"?

5) Put the old 1.2.2 Resigning from Roles last as section 1.2.4. This section doesn't say anything about how non-Partners resign from a role. Is that intentionally omitted?

**Comment by LouisChiquet** [comment]
I personally like the order and the very “clean” spaces between the sub-articles, which from a practical point of view when looking at the summary allows to quickly reach those. After I remain perfectly open to any change but would be curious to know why “condensing” which would make things maybe a bit more “flooded” in the text, as the article [1.2 Role Assignment](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#12-role-assignment) is a particularly “popular” one (new Holacracy practitioners looking and referring at it mostly at the start as the role assignment is a core topic).

However would second @ebabinet's point over “_Anyone so assigned becomes the "Role Lead" for that Role._” in the top text given article [1.2.3](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#123-default-role-lead) which says “_When a Role is unfilled or led only by external parties who are not Partners of the Organization, then any Partner who controls assignments into that Role is automatically considered to fill it as a Role Lead._”, as in the “_anyone_” on the first paragraph can be included external parties of the org. Would maybe change simply to “_Partner so assigned becomes the "Role Lead" for that Role_”, and it'd also concern the “_Anyone filling a Role with such a Domain may assign people to fill the target Role or remove people from that Role at any time._” sentence before, replacing with “_Any Partner_” so. Except if it's decided to make external parties be able to be Role Lead, which would actually be good because we have the case in iGi with 2 non-Partners filling a role in our Holarchy. Sorry, it's moving a bit out of the subject you brought, but thanks to Eric discovered that point.

**Comment by brianjrobertson** [comment]
Thanks all!  I didn't go with your idea exactly @ebabinet, but it definitely helped me get to the place I landed, which I think works better than what I had before.  Further ideas are welcomed, though I'm also happy enough with this structure now to call the issue closed.

(And @ebabinet: non-partners can be assigned as Role Lead in the current dev version; thanks for finding the bug about how non-partners can resign, I fixed that; and see starting text to 2.2, 2.3, and 2.4 re who the responsibilities & duties in each apply to, Role Lead vs. Role Supporter)
