### ISSUE TITLE
Allow operational proposals in governance meetings, if integration required by governance?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#284]
If governance explicitly calls for integration around a specific operational decision, would it be safe to allow an operational proposal for that specific decision in a governance meeting?  e.g. when a policy says that no one can make a certain decision without integrating with specific other roles, or an accountability includes "... after integrating objections from..." (or equivalent).  In addition to using this in regular governance meetings, this would also allow a special governance meeting to be called to deal with a specific operational proposal when needed, which effectively handles issue #59, at least when the roles in question are in the same circle.

One risk here is that an operational proposal could clog up the governance process and not leave room for governance, but that's easy to address if it happens - someone can just call a special governance meeting, where they control the agenda, and use it to address the underlying governance that's creating the bottleneck.

Anyone else see other substantial risks here?  Is this worth doing to address #59 and potentially other use-cases, or too dangerous to proceed with?

**Comment by LouisChiquet** [comment]
I personally wouldn't fusion the two, not feeling the need. The fact of using the IDM for actual governance and **some** certain/operational decisions shall remain differentiate. Many clients already have processes or methods to make certains/operational decisions, and I feel like it'd be pushing a bit the fact of using the IDM/“integrating objections from...” in the usage of the organisation. Plus following the new accountabilities with the facilitator and secretary being ready to facilitate meetings (tactical and governance) [when called by a role](https://github.com/holacracyone/Holacracy-Constitution/issues/59#issuecomment-421058286) make it easier, and as it's not that often happening, I don't really see the necessity.

Plus my personal in-org point of view, is that sometimes (we're 4 in iGi) I'm glad to not have a role participating or being related to some decisions, and I'm confident they can integrate objections without me (which it wouldn't if they had to brought it to Governance meeting as I'd be participating).

So no, I don't see substantial risks or danger, however as the Constitution have as purpose to be as light as possible (my opinion), I don't see the value of adding more rules which actually are achieved the little and rare times it happens (again, from my experience and what I saw), it'd maybe go “against” (well, not against, but didn't found a better word) diversity of decisions process and make the governance meeting much more heavier if the Constitution “encourage” by simply quoting this possibility. After I naturally have no data as I'm mainly supposing from what I know.

**Comment by chourie2** [comment]
In my interpretation of the current dev version, you can already do such things to elect a Non-Structural Role with any kind of Election Process (3.1.e). If I’m right, I’m not sure this was the intend, so I just signal it since it’s related to this issue.

In that way, I think you could add an f. Point on the list that allow operationnal decision under the restriction that you stated. I think it could be say in one small sentence and will not over-weight too much the constitution.

One concern with such change for me, is that the Governance in « Governance Meeting » might loose some sense.

Beyond this I’m curious about the opportunity to open this Meeting to others decisionnal process. I can imagine some risks and why you didn't include it in your proposal, but like @LouisChiquet I feel like the constitution shouldn’t push to use IDM. But should it push the other way around ?

**Comment by klaas1979** [comment]
In our company we experimented with IDM process for all kind of stuff especially for operational thinks (as an important note: we did not use Holacracy just IDM in day to day operations). The experience was quite bad, because the IDM process is really not a good process for operational decisions. I would not hint beginners to use this possibility, because I would fear from our experience that it would be misused, i.e. a lot of “big/important” decisions to be governed to be decided via IDM. 

If a circle decides to use IDM for decisions, it could amend the facilitator role to facilitate this type of decisions with IDM as an additional accountability?

This is no complete and integrated view on this issue, just my experience. So I would not see big risks, but misuse that could be avoided by leaving Tactical and Governance strictly separated.

**Comment by pjedrzejewski** [comment]
At our organization, we use IDM process for implementing the peer calibrated compensation system. In my Compensation Architect role, I felt more comfortable doing it this way rather than with the advice process alone and I've organized a separate meeting for that. Worked well and now the 2nd iteration (was rather simple, more descriptive process) is being processed via IDM asynchronously via a poll on Workplace. :)

I'm not sure it would make sense to do it as a part of the Governance Meeting where we focus more the structure.

**Comment by sitron** [comment]
In my opinion Governance is not defined by how tensions are handled (IDM) but rather on their output (structural change). So I would not bring in operational matters just because they rely on the IDM process. 
Would this also make it harder to grasp the difference between tacticals and governance meetings for beginners?

**Comment by brianjrobertson** [comment]
Thanks for the feedback everyone; I'm dropping this issue.
