### ISSUE TITLE
Rename "Triage Issues" to "Triage Tensions" in Tactical Meeting

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#285]
"Triage Issues" created confusion in one constitution translation, and the translator wondered what distinction the constitution was trying to make here, and why frame as "Issues" vs. "tensions"; I have no good answer, so seems this step should be changed to Triage Tensions.

**Comment by LouisChiquet** [comment]
I suspect the difference is that, just like Governance meeting, you're in a meeting so it's just for asking people if they have point to add to the agenda. Personally when facilitating with a mature group, I just say “Triage Tensions” in French, instead of the “Triage Issues”, which is a term more for beginners which still get tension as a negative word, and make them understand that it's a work meeting like any other.

**Comment by bernardmariechiquet** [comment]
"Triage Issues" is clear to get, non confusion at least for french translation. We could say "Triage items" or "Triage Tensions" which would be more aligned with "(e) Build Agenda:" that says "The Facilitator builds an agenda of Tensions. This makes senses back to your question to replace "Triage Issues" by "Triage Tensions".

**Comment by seriousplay** [comment]
"Triage Tensions" is much better an option since people who adopt Holacracy
must have learned that a tension is not necessarily an issue. Anything
could be a tension, so consistency is key here.

*Warm regards,*

*﻿Mr. Yiqing He*

*To inspire growth with purpose*

*https://www.linkedin.com/in/smarterlearning/*
<https://www.linkedin.com/in/smarterlearning/>

*086-136-9369-8128*

*Zoom**: **https://zoom.us/j/2018002018* <https://zoom.us/j/2018002018>

*Skype**: yi.qing.he*

*Wechat**: 8855162*

*heyq@purposeplus.cn <heyq@purposeplus.cn>*

**Comment by margauxchiquet** [comment]
I agree that Triage Issues creates some confusion because I often see some people asking: “are we bringing tensions here?”

**Comment by margauxchiquet** [comment]
Just like “Agenda item” in governance. Removing “item” and sticking to “tensions” all the time makes sense IMO

**Comment by margauxchiquet** [comment]
I know it is closed but since the constitution is not out yet .. :)
For me, we are not triaging tensions in a tactical meeting. Rather, we are triage agenda items.
I would suggest “triage agenda items” or “triage items”.
Tension is a gap between reality and a potential and I don't think it applies in a tactical meeting where the agenda item owner is just willing to have a space where he/she can move towards his/her need. Pin @bernardmariechiquet @LouisChiquet

**Comment by brianjrobertson** [comment]
@margauxchiquet That doesn't align with what I teach; I specifically teach that we are indeed triaging to resolve tensions in tactical, and each agenda item represents a tension.  If someone wants something to be different in any way to move their work forward, that's a tension by definition as I see it, and that's what leads people to request actions, projects, information, etc. in tactical.  The whole constitution is built with and from this definition of tension: it's not just a governance thing, it's any time you want anything to be different than it is.
