### ISSUE TITLE
Move Anchor Circle to Article 1?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#288]
Would the constitution be easier to understand and flow more intuitively if the Anchor Circle definition and clauses were moved into Article 1 on Org Structure, in a section after defining Circles, Circle Leads, and Circle Members?  Thoughts?

**Comment by chourie2** [comment]
Hello,

Probably! To go furthermore in your direction, I think it could also help to see the Organization as a Role in the Society. In other words not just presents the Organization view from within (Circle), but also from the outside.

**Comment by sitron** [comment]
@brianjrobertson Would you move all 4.2 into Article 1, or split what is related to org in Article 1 and the rest in 4.2?

**Comment by brianjrobertson** [comment]
Probably a split @sitron.

**Comment by sitron** [comment]
Not sure what is the "best" logic to be respected here: "all gov matters together" vs "what is important first". Maybe try to illustrate the change with a pull request to see if it makes sense or not?

**Comment by ericdgraham** [comment]
I think it's better where it is now in its own section below.

**Comment by rebeccabrover** [comment]
@brianjrobertson I find references to the Anchor Circle as "Anchor Circle" are often limited to matters of mechanics since most organizations that I've seen in practice name it something else (usually GCC the name of the org. Moving what reads to me like good getting started technical instruction to a prominent place in Article One seems like it would put undue emphasis on it as a frequently changing structural part.

When I think of when Anchor Circles are referenced by name (or even not by name since a very common question from novice practitioners is _What's an Anchor Circle?_ to which I answer _The outermost circle._ and I haven't had a follow-up question on that answer yet. )most often, it's either during initial adoption and creation of a first circle or a little later at the creation of a new circle to encompass the existing first circle (typically when a pilot adoption expands). In either case, it's an adoption matter which makes me think reference to is in adoption matters is the right place.

**Comment by LouisChiquet** [comment]
I believe now it's a bit linked with the new issue you brought @brianjrobertson https://github.com/holacracyone/Holacracy-Constitution/issues/310 .

I would personally not agree on this idea, for the given reasons previously, but if it's Article 4 as a whole which is just splitted, then makes more sense.

**Comment by brianjrobertson** [comment]
This is now subsumed in Issue #310
