### ISSUE TITLE
Testing Proposals

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#29]
At section 3.2.2 Criteria for Valid Proposals, Facilitator may discard a non valid Proposal before it is fully processed.
"Some Proposals are disallowed within a Circle’s Governance Process, and the Facilitator may discard these before they are fully processed."

At section 3.2.3 Testing Proposals, Facilitator may test the validity of a Proposal.
"The Facilitator may test the validity of a Proposal by asking questions of the Proposer."

There is a bug there, as there is no explicit rules in the IDM process described further re when the Facilitator may test the Proposal. This happens a lot with new clients and so with respect to the constitution, the Facilitator is not able to discard an invalid Proposal even when questions are asked during the Clarifying Questions. In such case, Facilitator may not discard as it is in the present version and has to wait until Objection round in order to object and then wait until integration to discard the unvalid Proposal.

For me this needs to be fixed before 5.0 as it is not an enhancement but clearly a bug.

**Comment by brianjrobertson** [comment]
This was already fixed, by removing the constraint that the Facilitator could only test during Present Proposal or Integration.  Now, the Facilitator can simply discard it as soon as they discover it doesn't meet the validity criteria.  The Constitution is silent on when they can ask questions specifically to test it, which means it's up to the facilitator to use their judgment.  For example, they already have the ability to ask clarifying questions during that step, so they might ask for the required example at that point in time; if the proposer says they don't have one, then the Facilitator could choose to use the authority they have to discard the proposal at that point...  Or, as another example, if the proposer acknowledges that the tension isn't limiting their roles at all during the Amend & Clarify step, the Facilitator could then jump in and discard.  I don't think we need to call this all out explicitly, since we've instead given the facilitator a lot of latitude to allow them to discard once a proposal clearly doesn't meet the criteria...

**Comment by bernardmariechiquet** [comment]
I got that Brian and was aware you've removed the constraint that the Facilitator could only test during Present Proposal or Integration. This is one piece i track since a long time as I encounter this issue very often with clients.
I sense a big tension on this one and don't follow you with your arguments. Facilitator is the last role you want to give latitude. This role should follow the rules. In all examples you mention, Facilitator has something special above the rules, at least the explicit ones.
For testing objections, the space where this role is explicitly allowed to to do is explicit. Which is not the case for testing Proposal. This is not consistent from my perspective and creates confusion.

It sounds weird to me that in my Facilitator role, in the specific case you mention (Or, as another example, if the proposer acknowledges that the tension isn't limiting their roles at all during the Amend & Clarify step), I would jump out of the process there without this being explicit - same during clarifying questions - as a facilitator I am confortable to ask questions, wait for answer from the Proposer and redirect by asking "any other clarifying question" - nothing else...

I am not sure to spell out clearly my tension here... Something is missing.

**Comment by brianjrobertson** [comment]
I follow you, though I do think this is a very different case than objection testing, because you don't actually do anything special or out of process to test proposals; the facilitator simply discards them once something else happens, without specifically "testing" them himself.  So, it's not that the facilitator "can test proposals" anywhere - it's rather that the facilitator _never_ "tests proposals".  But if it ever comes out that it doesn't meet the criteria, the facilitator simply discards it.  There are no special questions to test this, thus no special rules or space given to do so.

**Comment by MiekeByerley** [comment]
3.2.2 Some Proposals are disallowed within a Circle’s Governance Process, and the Facilitator may discard these before they are fully processed. To be valid for processing, a Proposal must resolve or reduce a Tension sensed by the Proposer.......

3.2.3 The Facilitator may test the validity of a Proposal by asking questions of the Proposer. For a Proposal to survive the test, the Proposer must be able to describe the Tension, and give an example of an actual past or present situation in which the Proposal would have reduced that Tension and helped the Circle in one of the ways allowed by the prior section. The Facilitator must discard the Proposal if the Facilitator deems the Proposer has failed to meet this threshold. However, when assessing the validity of a Proposal, the Facilitator may only judge whether the Proposer presented the required example and explanations, and whether they were presented with logical reasoning and are thus reasonable. The Facilitator may not make a judgment on the basis of their accuracy, nor on whether the Proposal would adequately address the Tension.

I think I understand @bernardmariechiquet. The way these two article read is confusing, it took me a couple of readings to figure what was going on here. I think this is due to the manner in which 'Processed' is being used, and the splitting up of the 3 criteria required for validity. 

In 3.2.3 To survive the test (by the Facilitator) of validity the proposer must describe the Tension and provide a reasoned example. In other words if it meets these it is valid for processing, however according to 3.2.2 that is not the case because suddenly there is the extra requirement that the proposal must resolve the Tension (which is not done by the Facilitator). Who by?

In 3.2.2 ....To be valid for processing; indicates that a proposal needs to be established as valid prior to processing, meaning that the Facilitator's testing is not part of the act of processing. This contradicts the preceding sentence as, the Facilitator would discard Proposals before 'Processing' occurs and only if the criteria under section 3.2.3 are not met. Whether the Proposal resolves the Tension is discarded by the governance process not really the Facilitator as the Facilitator cannot pass judgement in this realm.

I think there is a high risk of Assumption occurring with the way it is currently written, also the order of the two Sections feels wrong. I would suggest greater clarity as to over process, what is inferred to as "processing", What part of it the Facilitator can accept/discard and by what means the remainder is accepted/discarded.

**Comment by julianeroell** [comment]
Further conversation in the Holacracy CoP: http://community.holacracy.org/topic/testing-proposal
