### ISSUE TITLE
Update Adoption Declaration to include section for partners to sign to agree to abide by constitution

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#290]
In addition to the adoption declaration document, as a Ratifier or a hiring role, I'd also like a simple form included with the constitution that I can distribute to partners and ask them to sign to agree to abide by and enact the terms of the constitution to the best of their capacity.

**Comment by LouisChiquet** [comment]
I am not really sure what legal value it may have (knowing that French labour laws are very strict on that). We are working with clients to update working contracts to include Holacracy (making it compatible with French labour laws). I'm not really fond of the idea, and wouldn't do it personally, as it can be a Damoclès' sword in French legislation (used by the employee). @bernardmariechiquet, inputs?

**Comment by chourie2** [comment]
Maybe such document shouldn’t just be translated like the others, but also be redacted in an appropriate manner and should contain the appropriate methods on how to use it.

For example if the document can be signed as is by the partners, or if some specifics contents of it should be included in some specified legal document.

I think that such manner and methods can only be defined country by country which could be tricky to put in motion, since it’s also need some legal expertise to be « translated ».

But I feel like it would be valuable for everyone to be able to rely on that legal translation and on a process, probably here on GitHub, to get access to that legal translation with an appropriate validation process if needed.

**Comment by sitron** [comment]
i like the idea. Doesn't mean it _has_ to be signed by any partner of all Hola companies, just a doc that can be used as a base standard. I'm sure such a doc would have been good for us at Liip.

**Comment by LouisChiquet** [comment]
To add on my previous message: Legally speaking, employees don't have, in France, the legal authority to do so. Just managers or the leader of the company, as there is a subordination link legally with the work contract. Therefore, if the CEO sign the Constitution as the system of the company, de-facto every of his subordinates need to apply such. Therefore, I don't see the need from a purely Constitutional point of view, at least in France. After, onboarding the employees, and involving them in the decision process, is more of a decision that **widely change from one company to another**, therefore putting such document (even if not mandatory to pass through for adopting Holacracy I suspect?) wouldn't add that much value.
And what do you do if one person refuse to sign? Or sign, but then later says “Oh, we did that under pressure of the boss” (something that already happened)? I know it's more on how to accompany the clients rather then purely the Constitution, but so why would the Constitution include such?

**Comment by bernardmariechiquet** [comment]
@brianjrobertson This is a great move! I have often asked myself this question and some clients have gone so far as to modify their employment contracts. This would simplify things and make it easier to engage all employees from the beginning. Excellent suggestion.

**Comment by bernardmariechiquet** [comment]
Moreover I think from a legal and human perspective, such an agreement should be proposed to each employee before kick off.
