### ISSUE TITLE
Circle Lead accountability towards Governance

### ISSUE THREAD

**Issue by sitron** [holacracyone/Holacracy-Constitution#292]
In Appendix A of the dev version i see this accountability for the Circle Lead:
> Defining Roles and/or Policies via the Circle's Governance Process to enact its Purpose and Accountabilities

I was wondering in what way is a Circle Lead different from any other role in processing tensions through governance? Should that be an accountability of all the roles of a circle?

**Comment by sitron** [comment]
After having talked to @brianjrobertson i now understand what is meant. Each role of the circle can process its tensions but the Circle Lead is accountable of processing tensions to enact the purpose of *the circle* (vs the roles within the circle)

**Comment by jeanlucchristin** [comment]
Not so clear to me
I imagine that if the constitution goes out as it is, there will be a lot of misunderstanding and questioning triggered by this accountability.
I do not have a concrete proposal but I think it is useful to specify that the other roles also have this accountability in order to realize their own purpose

**Comment by brianjrobertson** [comment]
Every role does now in v5.0; everyone filling a role is also a Circle Lead within that role's inner circle...

**Comment by jeanlucchristin** [comment]
OK, let see
