### ISSUE TITLE
Add Glossary as addendum to the Constitution

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#303]
Holacracy introduces many new semantics. Yet the definition of those resides outside of the Constitution, in an non-authoritative document.

I wish the [glossary](https://www.holacracy.org/glossary) was an integral part of the constitution.

**Comment by LouisChiquet** [comment]
Interesting point. As said in the introduction of the Holacracy® Constitution, “_The Constitution is also not an instruction manual or a guidebook for learning to use the Holacracy system._” and I like to keep apart the pedagogical from the Constitution. Why? Because interpretations of the Constitution may vary first of all (it's not precise in the Constitution that you need to have an -ing verb for an accountability, it's your interpretation), and it'd be reducing a large portion of various practices which are all using the same Constitution, but with different cultures and therefore interpretations and would go against [Article 3.4](https://www.holacracy.org/constitution#art34) in my own opinion. Second, any changes would need to be passed through GitHub and with the current process, I don't find it very realistic in my opinion.

Would love to hear other thoughts on that.

**Comment by brianjrobertson** [comment]
Hmm, I could see it being useful to have an appendix to the constitution with those definitions, but having it as an authoritative source seems problematic, since the only authoritative source should be the definition given in context in the constitution text itself.  So, given that, I'm thinking a glossary appendix would be better implemented not here on github, but as an effort of moving from the text here to a printed (or PDF) version of the constitution, which could easily include an appendix for reference in the same document...  That said, if anyone thinks I'm wrong here, please do jump in - I'd love to hear dissenting views.
