### ISSUE TITLE
Allow a role to add accountabilities to itself

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#308]
In v5, a role can create its own cross-role circle with another role, and that circle can then add accountabilities to the founding roles.  For consistency, that means a role really should be able to add accountabilities directly to itself as well.  And there are cases where this would be useful as well: e.g. to broadcast a service the role provides for the sake of its purpose, so others know they can engage it (there's no reason this should need to go through the Super-Circle's governance process, and it already doesn't have to if the role is linked into another circle).

**Comment by LouisChiquet** [comment]
“For consistency, that means a role really should be able to add accountabilities directly to itself as well”
I don't believe so, as we're at another level. The example you took, doesn't convince me as, why would I like as a Client, to see my supplier add offers that are just declining the offer that interest me?
For instance, ”Supplying my client with cars”, I wouldn't care as the client to have my supplier add accountability about internal services he needs to do so. Plus would add more service offers, on what is he doing, while that isn't the goal of accountability. Accountabilities are services to client basically, and it makes perfectly sense to need to pass through the Super Circle's governance process to add accountabilities on the Circle, as it's not the Circle that can define what its clients wait. He can always throw inputs to its clients, manage its internal process through accountabilities internally, etc. But this would add complexity alongside confusion (as people don't necessarily under accountability right away) for little value, or even negative effects as services will multiples, rather then think strategically from a client perspective.

**Comment by bernardmariechiquet** [comment]
I love the idea a role may add accountabilities directly to itself, that make perfect sense to me. Can't any business add a service offer to its catalogue? Of course yes.

**Comment by julianeroell** [comment]
I would find this extremely confusing. Any change in the Governance Records should run through the regular Governance Process, in my opinion. 

Roles don't exist in a vacuum: they interact with other Roles. Adding accountabilities at-will, without communication with the Circle, will easily create confusion / overlap / unclarity. (Or not. possibly safe to try, as all confusions created by "adding services" can then later be sorted out in Governance again. But... ouff, the work! )

**Comment by Clifdon** [comment]
I agree with @martinaroell. Adding accountabillities without communicating would eliminate the so powerfull feedback loop of governance.

**Comment by colinfrei** [comment]
I like accountabilities to be tension driven:
- "it's not clear to me who's accountable for this"
- "To me, X seems to belong to a circles purpose, but they don't agree"
- ...

If it fits their purpose they can do it, with or without an accountability.

I've seen quite a few cases where accountabilities were added for everything a circle/role feels they do, which to me reduces clarity by obscuring things. I fear that making it even easier to add accountabilities would lead to even more of that.

**Comment by klaas1979** [comment]
I would not allow this: I see a lot of potential problems with beginners. An accountability does not need to bound to the purpose of a role. If I can add accountabilities I could in the worst case give myself permissions to do things, that were prior out of my role. As beginner I would just add it to "my own role"  and make it unclearer and create personal roles just because I can do it and I do not need to do difficult governance.

For me the potential harm is bigger than the upside for advanced practitioners. You can always use asynchronous governance for this. We do this a lot and there are more escalations than expected. That are sorted out in the governance meeting.

**Comment by benoitpointet** [comment]
I agree with all doubts expressed above.

>  give myself permissions to do things, that were prior out of my role

I'd like to build up on that: I see the risk that a role-filler would use that mechanism to give themselve legitimity to do things that are potentially loosely aligned to the purpose of the role.

It would also allow people to create work for themselves, in the sense of making themselves (look) very busy/important. Or grab in their role, yet probably for themselves, an area of concern that they are interested in.

Although the Constitution says nothing about it, my interpretation is that accountabilities ought to align to purpose: any accountability that does not align to purpose weakens the effect of the purpose hierarchy and potentially augments waste. But that's probably another tension ;) Yet that proposal would reinforce it.
 
This proposal would weaken another key aspect of Holacracy: purpose and accountabilities are outside-in signals to the role.

**Comment by brianjrobertson** [comment]
Note the intended implementation of this would only allow adding accountabilities that express the purpose of the role, which the role would otherwise be doing anyway even without the accountability, not broadening it.

Also note that this is already almost possible in draft v5, because two roles can now create a circle themselves around their roles, and add accountabilities to either of their roles via that circle; in fact, one of those roles could then opt-out of the circle, leaving a circle with just that role in it, and that role-filler could then add accountabilities to their own role.  And even beyond that mechanism, a role-filler can already (in draft v5) autocratically make their role a circle and create new roles within it, with any accountabilities that serve the overall purpose of their role.

So, given that, how is this particular feature more dangerous (with the intended purpose limitation) than what's already possible?  Why should this be prevented, thus forcing role-fillers who want to do this to create sub-roles to do it instead, or to group up with another role in a cross-role circle to do it?

**Comment by benoitpointet** [comment]
### Congruence to the spirit of v5

Ok I reread most of v5, and indeed, this proposal is coherent with the changes you mention, and totally congruent to 1.1.c in v5 (master) : `one or more “Accountabilities”, which are ongoing activities the Role will enact, either in service of other Roles in the Organization or to support its own Purpose.`

So it would remove most harm.

Yet ...

### "Circles across roles" argument

One of the main driver for this change seems the consistency issue brought by "Circles across Roles". It feels a bit wrong to try to solve this issue on the side of role governance rather than on the side of this new construct.

Moreover, according to 1.3.4 in v5 (master) accountabilities added by a circle into which the role is linked don't come from within the role, but from the governance process of the circle, even if it being a circle across roles, and those accountabilities stay under control of this governance process, not under control of the Role Lead.

That is: as a Role Lead, going through a "linked-into" circle to add accountabilities to the role is no less effort than going through Super-Circle governance.

Btw under what control would those "self-allocated" accountabilities live? Would they be governable in the Super-Circle governance process and would they live in a "governance space" belonging belonging to the sole role?

### Accountabilities as expectations and/or offering

Don't get me wrong, I have nothing against a role "publishing its services" to the broader organisation. I believe in service architectures. But services are not expectations from the broader context, they are offerings to the broader context, as answers to those expectations.

So I would be in the favor of two distinct properties: 
- keep the "accountability" property of a role as output expectations upon the role, controlled by the circle governance process.
- introduce an "offering" property, controlled by the role.

This would allow to represent the bi-directionnal work relationship of the role to the broader org with clear authority scheme.

**Comment by brianjrobertson** [comment]
I'm intrigued by the idea of separating the distinction of Accountability and Offering as a way to address this and add additional value (thanks @benoitpointet).  But I'm not ready to add it to the constitution yet, and it relates to another more experimental constitution development project I'm working on (around differentiating types of accountabilities), so I'm going to queue this up as something to revisit in the context of that project, and close this as a current v5 issue.

**Comment by benoitpointet** [comment]
A few thoughts that I share here, for the record, or more ;) :

I see an offering as a corollary construct to accountability: accountabilities are constraints from the outer world on the role, for the greater good. Offerings are value-propositions from the role to the outer world, for the greater good (i.e. aligned to purpose).

Offerings will enliven cooperation and value exchange, while accountabilities enforce it.

Some offerings can also become accountabilities, delivering something could indeed be expected by some role.

Role should have authority on its offerings, no specified offering is also possible (like no accountability, purpose, ...). Offering being an "inside-out" dynamic, the roles can define their offering, and the circle offerings may sum up to the sum of roles offerings, or vice-versa. That's why a circle could make a role accountable for an offering – _I am still very unclear on what that implies, maybe this is over-engineered_.

Offering is not "creating work for yourself" (like creating an accountability on your role would), it is a value proposition for the others, a proposition waiting for a client.
