### ISSUE TITLE
Remove "Adoption Matters" (Article 4 in v4.1) and distribute contents elsewhere

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#310]
Check out the super short contents of Article 4 at the current point in the development version; as of this post, that's [this version](https://github.com/holacracyone/Holacracy-Constitution/blob/33e2d229b5654b95e90cfe5e372fb1a75fc3ea6d/Holacracy-Constitution.md).

It'd be easy to remove this article entirely:

- §4.1 and §4.5 are just administrative about adopting the constitution, and could easily go into the preamble or otherwise outside of the main body of the constitution entirely.  
- §4.2 is now a super short single section on the Anchor Circle, and could easily go into Article 1, under the Circle section (as §1.3.5).
- §4.3 on Legacy Policies and Systems could go into either the Operations or the Governance article, or perhaps into a new article on partnership stuff if one gets added.
- §4.4 on Process Breakdown could go back into the Governance article (which is where it is in v4.1).

As it stands, this article seems like a haphazard and fairly random grouping, without a strong cohesive theme.  Should it just be removed?  Thoughts?

**Comment by chrcowan** [comment]
@brianjrobertson Interesting. I can see how the grouping is haphazard, but it does have a theme "adoption matters," which is a helpful grouping of rules from a user's perspective. With that said, there are often things that would help users but still may not be the concern of your role, because another role (e.g. whomever writes the "Desk Reference" version) could handle that. But as it is, I kinda like having them in one place even if they address different installation points.

**Comment by ericdgraham** [comment]
I think you could break it apart and it would be an improvement. It does seem a little scattered currently.

**Comment by LouisChiquet** [comment]
I like the fact that the Article 4 is basically bringing more technical features alongside interface or extreme not much used (like process breakdown), that people shall invest when trying to get a much more fine interest and understanding of Holacracy.
And at the same time, the Constitution is not a pedagogy document so I don't see any issues, even if I like the idea of having an article on how to kick-start/launch the adoption.
