### ISSUE TITLE
Remove Role Supporters (obsoleted by Role/Circle merger functionality)

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#313]
In looking for ways to simplify the constitution and remove anything not clearly needed, I started wondering if Role Supporters are still needed.  They were originally added to the dev version before the role/circle merger played out; now that that's present, any Role Lead can use those rules to break down their role, add an included role, and assign someone to it, as an alternative to assigning someone to the whole role as a Role Supporter.  Given that capacity, is there any reason or use-case that indicates the Role Supporter construct is still needed or at least substantially more efficient; i.e. where the same goal couldn't be met nearly as well by instead breaking down the role and assigning someone to a role created within?

**Comment by leword** [comment]
The question(s) I would have are a) if a "Role Supporter" role created within the primary role has the same authority to act on behalf of the primary Role as the Circle Lead, and b) if that's an important part of the use-case solved by Role Supporters.  Top-of-head I'm only thinking of supercircle governance ( where you probably want the primary role-filler anyway ), and authority grants that explicity reference the primary role.  In that case, maybe you can delegate authority via policy somehow?  Anyway, my $0.02 seems safe enough to try without it; and then see if cases come up in practice where the "roll-your-own" approach seems to create a lot of overhead.

**Comment by chrcowan** [comment]
Hmm...hard to get my head around the question. If you did maybe a video (I'd probably need visuals) then I might be able to say something substantive.

**Comment by oliviercp** [comment]
Unless I misunderstand your sentence, I think you meant "any Role Lead can use those _**rules**_ to break down their role". Mentioning it because it's particularly confusing.

To your question: it's tricky because I don't have any real use case to draw from. On one hand, I'm sensitive to the confusion that can be created by the distinction between "Role Supporter" vs sub-circle role. I was trying to explain the distinction to a friend recently, and it was a little weird. It's like Role Supporters are a new construct that doesn't obey the same rules as other roles fillers, and require to be thought about differently. It adds complexity. 

It also adds some weirdness: I can see a temptation for a Role Lead to assign Role Supporters to his role because it's easy and flexible (the value of ambiguity), but it could also be done instead of differentiating functions within that role. Of course it's a judgement call for when to choose to break down the functions vs just having "supporters", but I can easily imagine cases where a Role Lead will choose the latter not because it's more appropriate but because it's easier. I could imagine myself doing that! Roles Supporters are an easy way to avoid clarity.  

On the other hand, my friend was particularly excited about the prospect of Role Supporters being able to help him in some roles without him having to think about differentiating functions within his role (i.e. break it down into a circle). However in his explanation of his use case, he did mention he'd like his colleague to help with a few specific activities of his overall role's work...

So, I don't really know. I'm not a fan of Role Supporters from a theoretical level, but I liked their practical use. I almost see them as a useful tool to use until you learn better tools (i.e. get clear on who needs to do what)

**Comment by brianjrobertson** [comment]
(Yes, I did mean "rules" in that sentence, thanks Olivier; I edited it to avoid future confusion.)

**Comment by brianjrobertson** [comment]
Thanks for the comments all.  In considering them and thinking through the use-cases I know of, I think they can all be handled effectively with a sub-circle role (plus some policies in some cases).  I also think the added complexity and the risk that @ocompagne highlights are substantial; so, my intention is now to remove Role Supporters.  If anyone wants to make a case otherwise, please do so ASAP.

**Comment by chrcowan** [comment]
No strong opinion either way at this moment.

**Comment by ericdgraham** [comment]
My hit is that it's not worth the added complexity to add in this new construct when the same outcome can be achieved without it.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I would like to come back to this notion of supporter, which was deleted last August during my holidays, so I did not see this deletion until much later. At two of our customers, we had to create this notion of Supporter. In one case, it is a team in a production workshop. With a team leader and 5 or 6 members. We felt with the client that the team leader had neither the skills nor the leadership to be the Lead Link in a circle, the members of his team had neither the minimum leadership nor the skills to manage roles. In a transitional phase, and in order not to penalize the whole structure in the process of adopting Holacracy, we defined a role with the Team Leader as Leader and all members of his team were assigned to this role with the status of Supporter, as defined in the development version of the constitution 5.0 before August. We therefore anticipated an evolution of the constitution and the ratifier adopted an amendment to constitution 4.1 pending 5.0.
We have the case of another customer who owns a restaurant and in some roles, such as the role of a diver, disabled people are affected. The customer feels that these people are not able to manage roles as defined in the constitution and decides to use the same Supporter status via an amendment pending 5.0.
Hope you will(it's not too late) to reconsider this deletion. Otherwise we will have to renew an amendment in 5.0.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet Hmm, I wonder if there's another solution to this issue under the current v5.0 ruleset, even without the Role Supporter construct?  I'd love to explore that first, before we conclude that the extra complexity of Role Supporters is actually required.

So, what would you do instead if you didn't have this functionality and also couldn't adopt a constitutional amendment for some reason?  For example, you can achieve almost the same thing by breaking down the role into a circle and creating whatever sub-roles within that are needed for the part of the role you do want those people to manage; is the concern with that approach that it's too complex?

One thing I wonder, at least in the second example you gave: If those people can't manage roles, I can't imagine how they could be partners at all - the duties of a partner requiring managing roles.  Perhaps what's needed is more flexibility in assigning roles to non-partners, so you can simply avoid making those people partners in the first place?

What other ways might this tension be solved, if we didn't re-introduce Role Supporters?

**Comment by bernardmariechiquet** [comment]
> So, what would you do instead if you didn't have this functionality and also couldn't adopt a constitutional amendment for some reason? For example, you can achieve almost the same thing by breaking down the role into a circle and creating whatever sub-roles within that are needed for the part of the role you do want those people to manage; is the concern with that approach that it's too complex?

@brianjrobertson The most common problem encountered is the fact that some people know how to do the work assigned to them but do not have the self-management skills to process tensions, purpose, and accountabilities. They're doers, not managers. Does it make sense? 
So, your first suggestion of breaking down the role into a circle and creating whatever sub-roles within that are needed for the part of the role you do want those people to manage, doesn't fit as these people cannot manage? This only takes the problem to another level.
And we want to be able to make them evolve, progress, at least for those who wish to do so, towards the status of role lead. This is why we need a status before that of role lead to be in line with reality.

> One thing I wonder, at least in the second example you gave: If those people can't manage roles, I can't imagine how they could be partners at all - the duties of a partner requiring managing roles. Perhaps what's needed is more flexibility in assigning roles to non-partners, so you can simply avoid making those people partners in the first place?

I like the idea of creating a maturity scale in terms of self-management skills (prior partner, partner), I think it's a good idea, to introduce different statuses, which comes back to what was conveyed by the construction of Supporter.

> What other ways might this tension be solved, if we didn't re-introduce Role Supporters?

In fact, becoming a role leader requires a certain number of self-managerial skills defined in the constitution, which the employee did not necessarily have at the time of the transition from a conventional system to Holacracy. Isn't the question to integrate a mechanism/something in the constitution around this "transition".

**Comment by brianjrobertson** [comment]
@bernardmariechiquet That makes sense to me, yes, and I've sensed similar tensions.  My current thinking is to broaden the eligibility for role assignments (in §1.2.1) to allow roles to be assigned to non-partners **_even if_** those people have not agreed to enact all duties typically required of a role-filler, and then have any duties the person has not agreed to enact fall back on the role assigners who made the assignment.  That way, you could have people like you're describing not be "partners", which is probably more appropriate anyway since they can not handle the duties of a partner, but still assign roles to them.  Any thoughts on this approach?

**Comment by brianjrobertson** [comment]
@bernardmariechiquet I'd love to hear if you think the change I just submitted (linked above) will meet your need here?

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I don't see any explicit reference to non-partner assignment to a role in that change you've submitted. 1.2 says:

> Anyone so assigned then fills the Role as its "Role Lead"

My question for you: how the Role controlling Role assignment Domain may assign a non-partner?

To add on that, sounds weird to me that only partners are referenced in the preamble.

> The “Ratifiers” are adopting this “Constitution” as the formal authority structure of the specified “Organization”. The Ratifiers and all other “Partners” the Organization has engaged to take part in its governance and operations must do so in alignment with the rules and processes defined herein.

What about the employees who are not partner(s)? They should appear clearly as they are doing work of the Org. within Roles and may attend Tactical for instance.

**Comment by LouisChiquet** [comment]
Great comment @bernardmariechiquet ! To add on:

From my interpretation of the change, you have non-partners which are Role Lead (as “Anyone so assigned becomes the ***"Role Lead"*** for that Role”), while the person which is Role Lead, in charge of assignment (or the multiples person if they are multiples in that role) also get added as Role Lead because “When a Role has no Partners of the Organization assigned to fill it, then any Partner who controls the assignment is automatically considered a Role Lead of that Role as well”, the “as well” defines that for me. Also an issue, it's specified that only partners can call and attend tactical meetings, while in practice we need them (and also can't do working agreements).

More broadly: Why equally have Role Lead and sometimes Role Filler in the constitution then being referenced (knowing that in assignment article, there's only ever Role Lead status being referenced)? Knowing that there isn't the Role Supporter status anymore? Even if I'm personally in favor of reestablishing the status. As 6.1 is truly great article, but, would be better on a per role basis. What happens if I want to have someone supporter in a role, but then role lead in another? Can happens in companies where at the start, some people are in multiples services, and some services are mature enough, and some aren't.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet Re:

> My question for you: how the Role controlling Role assignment Domain may assign a non-partner?

They just assign the role to the non-partner.  The section doesn't need to reference that possibility explicitly, because it was never limited to partners in the first place.  The role can be assigned to "anyone who accepts the assignment" - there is no restriction given that would limit it to just partners.

> To add on that, sounds weird to me that only partners are referenced in the preamble. What about the employees who are not partner(s)? They should appear clearly as they are doing work of the Org. within Roles and may attend Tactical for instance.

That's because it's unlikely non-partners would be signing this constitution or agreeing to abide by all of it (but partners typically would), so putting something like that in the preamble wouldn't have any effect/meaning.  But that doesn't mean it's not useful; just that you'll need to find another way to ensure non-partners align with whatever rules are important.  That could be in their employment contract, or in a service contract of some sort for a contractor.  And you may not want to ask them to agree to align with all the rules of the constitution; H1 has an outsourced bookkeeper, and they haven't agreed to follow all the constitution's processes - they don't attend governance for example, and don't track all of their actions & projects the way a partner must.  But they still fill a role, and have agreed to do enough to get most of the role's work done, with the Circle Lead picking up anything they haven't agreed to do but would otherwise be required of a partner filling the role.

**Comment by brianjrobertson** [comment]
@LouisChiquet Re:

> Also an issue, it's specified that only partners can call and attend tactical meetings, while in practice we need them (and also can't do working agreements).

There's nothing in the constitution that would prevent someone from inviting non-partners to attend Tactical Meetings in my interpretation, even without a policy modification; but if you interpret there is, then it's still changeable, as anything about tactical can be changed via a policy.

> More broadly: Why equally have Role Lead and sometimes Role Filler in the constitution then being referenced (knowing that in assignment article, there's only ever Role Lead status being referenced)?

Good point, there is no need for the distinction of "Role-filler" any longer, since it's the same as "Role Lead".  It only appears in one place in the actual text, plus in two headers, and I've removed it from all of them - thanks!

I didn't totally understand what you were referencing or asking in the rest of your post, so please let me know if I've missed anything important.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson There seems to be a lack of understanding between us, from the very beginning of my speech on this wire on 2 January. I'm not talking about subcontractors, I'm talking (as I think I clearly explained earlier in the thread with two concrete cases in two companies) about employees who do not yet have the skills to be a lead role, and who already have employment contracts.

> @brianjrobertson I would like to come back to this notion of supporter, which was deleted last August during my holidays, so I did not see this deletion until much later. At two of our customers, we had to create this notion of Supporter. In one case, it is a team in a production workshop. With a team leader and 5 or 6 members. We felt with the client that the team leader had neither the skills nor the leadership to be the Lead Link in a circle, the members of his team had neither the minimum leadership nor the skills to manage roles. In a transitional phase, and in order not to penalize the whole structure in the process of adopting Holacracy, we defined a role with the Team Leader as Leader and all members of his team were assigned to this role with the status of Supporter, as defined in the development version of the constitution 5.0 before August. We therefore anticipated an evolution of the constitution and the ratifier adopted an amendment to constitution 4.1 pending 5.0.
> We have the case of another customer who owns a restaurant and in some roles, such as the role of a diver, disabled people are affected. The customer feels that these people are not able to manage roles as defined in the constitution and decides to use the same Supporter status via an amendment pending 5.0.
> Hope you will(it's not too late) to reconsider this deletion. Otherwise we will have to renew an amendment in 5.0.

What are the solutions provided by 5.0 to prevent us from creating new constitutional amendments? I don't see any at this stage. Could you help?

**Comment by brianjrobertson** [comment]
@bernardmariechiquet Yes, I understood you were talking about non-partner employees, I just don't see that as any different than non-partner contractors, and I don't see a reason why we'd need to integrate anything in the constitution for that case specifically.  If someone isn't a partner, then their expectations and duties are not governed by the constitution, but by whatever other relationship agreements/contracts might exist (which, most likely, a partner has engaged them under).  Why would you need any kind of constitutional amendment in order to assign non-partner employees to a role, relying on whatever relationship terms the organization has already defined (or chooses to define) with those employees?

**Comment by LouisChiquet** [comment]
Because it's easier to handle the resources throughout the organisation, alongside to know who you address.

As what you mean, from what I understand, is that basically the use of GlassFrog is useless for non-partners, therefore you lose all the benefits that Holacracy can bring.

You have said yourself “_H1 has an outsourced bookkeeper, and they haven't agreed to follow all the constitution's processes - they don't attend governance for example, and don't track all of their actions & projects the way a partner must. But they still fill a role, and have agreed to do enough to get most of the role's work done, with the Circle Lead picking up anything they haven't agreed to do but would otherwise be required of a partner filling the role._”. But in Holacracy, filling a role, doesn't mean only doing the work, but also organizing it, and managing it like a small business. And so if they're non-partners, how can you make them fill a role?
Knowing that currently, in my interpretation of [article 1.2](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#12-role-assignment), non-partners can be assigned to roles in the organisation.
That would mean, in GlassFrog, we have people assigned, with whom we play the Holacracy rules, and others which we don't, while it's clear that they are legally employees of the company? It is adding complexity for me, where we could simply lower it with Bernard Marie's suggestion. 

Knowing that in French labour laws, it creates a hole sort of, as ratifiers (power holders) de-facto give their power to the Constitution when ratifying it, but so they'd have to define people which aren't partners (how legally is that differentiated, knowing that the employees' contracts are generally all the same), on a base to base? It'd leave open for people to choose between the two, Holacracy or just continuing as they did before. Making us lose the benefits of having a rule book, which is Holacracy.

Also, [article 1.2.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#121-default-assignment) “_When a Role has no Partners of the Organization among its Role Leads_” brings great confusion. As 1.2 clearly says that a non-partner may become role lead, but 1.2.1 state that “_When a Role has no Partners of the Organization among its Role Leads, then any Partner who controls the assignment is automatically considered a Role Lead of that Role as well_”. So to take HolacracyOne's example, on the bookkeeper, the person filling the Circle Lead role is also assigned to the bookkeeper role therefore?

**Comment by brianjrobertson** [comment]
@LouisChiquet I'm sorry, I'm not following you at all; if an organization doesn't want to assign non-partner employees to roles, they don't have to.  Or if they want to know they'll be held to all of the same rules as partners, they can simply make them partners or mandate that all employees must follow all rules in the constitution that they're able to follow as non-partners, or whatever else the organization wants to do - it's very flexible.  I don't understand what you're saying or trying to point out, or why a constitution change would be helpful at all to what you're trying to achieve.  I'm not actually disagreeing with you - I'm just not understanding where you're disagreeing with me in the first place, or what argument you're trying to make.

Re this part:

> Also, article 1.2.1 “When a Role has no Partners of the Organization among its Role Leads” brings great confusion. As 1.2 clearly says that a non-partner may become role lead, but 1.2.1 state that “When a Role has no Partners of the Organization among its Role Leads, then any Partner who controls the assignment is automatically considered a Role Lead of that Role as well”. So to take HolacracyOne's example, on the bookkeeper, the person filling the Circle Lead role is also assigned to the bookkeeper role therefore?

I wouldn't say the CL is "assigned" to the BK role, but rather that they are considered a Role Lead of the Role but only to the extent the BK role-filler isn't covering the duties.  So they are not assigned to the role, and they are not a normal Role Lead with all Role Lead duties, because they only have them to the extent the BK doesn't cover them.  So it's more like a backup; if someone asks the normal (non-partner) BK role-filler to do a basic duty of a role-filler and they don't, then they can expect the CL to cover it.  Or if there's a governance tension to process from BK but the normal BK role-filler isn't invited to governance as a non-partner, then the CL can represent the role in governance.
