### ISSUE TITLE
Allow Secretaries to authoritatively interpret Working Agreements

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#316]
We had a case come up in HolacracyOne where two partners had different interpretations of a Working Agreement, and one wanted an official authoritative interpretation that would bind the parties until the agreement was changed.  The constitutional clause empowering Secretary interpretations currently only applies to the Constitution itself and all Governance created thereunder, but makes no mention of Working Agreements.  Without that explicit mention, it's easy to interpret Working Agreements as outside the bounds of Secretary interpretation.

And that begs the question: should the constitution allow the Secretary to authoritatively interpret Working Agreements?  Not allowing them to leaves no single authority capable of reaching a binding decision, which is all sorts of problematic I think.  But allowing them to means an organization role can interpret a personal agreement.  My current thinking is the latter is better; there’s nothing inherently wrong with placing that authority on an organizational role if the partner knows it going in (and can always end the agreement, which they usually can unless they’ve agreed otherwise), and the Secretary is not a typical organizational role - it’s not at all charged with getting work of the organization done, but just with holding due process, and it’s an elected role, both of which mitigate the potential issues in that.

Thoughts/reactions?

**Comment by rebeccabrover** [comment]
@brianjrobertson Given the ambiguity of language by nature and the flexibility inherently built into both working agreements and governance by the constitution, it makes sense to me the Secretary would have the authority to interpret meaning on both.
It does seem possible for the constitution to stay mute on the subject of interpretation of working agreements and let each organization decide how they want to manage that via governance; however that seems like it would cause more confusion for newly practicing orgs (and those newly practicing v5) than giving the authority to the Secretary by default (as the adjudicator in other instances of differing interpretations) for a sense of consistency and ease in adoption and letting advanced organizations make the change to another mechanism if it matters that much. 
Random thought...This authority highlights the value of a good Secretary in a very tangible way and I could see that being of use when trying to coach organizations through the power-shift and re-adoption of the word Secretary from assistant to archivist and steward.

**Comment by chrcowan** [comment]
@brianjrobertson I'm going to start typing and hopefully, I'll stumble upon some coherent thoughts. I think the issue is actually pretty complex, but I'm going to set aside issues of context (org. vs. partner vs. person, etc.) and just say...it makes a lot of sense to me to leave it out of the official role definition, which would also allow someone to propose an authority for it (maybe even adding it to a relevant Secretary role).

**Comment by ericdgraham** [comment]
I hesitate to add that authority to the Secretary role. It crosses a significant threshold that seems important to maintain, IMO. It could also get very personal if an org role is interpreting a personal agreement, and could easily get messy and lead to someone calling for an election if they disagreed with the interpretation. Forward looking? Yes. Safe enough to try? I don't think so in this case. As soon as there's a situation where this is needed, it's already likely a contentious topic and asking a circle Secretary to step into that position at that time seems inappropriate. Seems like it lands in the Org space/People space that's more important to let each org decide how they want to handle it (eg creating a role for it) rather than baking it into the constitution, which forces (to some degree) that situation on organizations.

**Comment by brianjrobertson** [comment]
One theme I see in the suggestions above is the idea of letting the organization create governance to decide what role can interpret working agreements.  The trouble here is that right now the organization itself doesn't clearly have that authority, so any governance specifying how that works would be invalid, unless the partner has agreed to it.  That agreement could come from a clause in the constitution, because partners all agree to that, or it could come from another working agreement made with the partner… but if there’s differing interpretations of _that_ working agreement, we’re right back to having no overarching authority, which I don’t think makes sense.

So, I think we do need a constitutional clause specifying that the organization has the authority to interpret working agreements.  If we just add that without putting the authority on Secretary, then sure governance can specify how it works, but it will default to Anchor Circle Lead - and that seems far worse than defaulting to Secretary while still allowing governance to change that.  So, I think @rebeccabrover's logic here is spot on - the organization needs the authority to do this, and Secretary seems the best default.  I'm going with that.  Thanks all for the help thinking this through!
