### ISSUE TITLE
How can a Circle Lead constrain activity that's outside the Circle's purpose/accountabilities?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#317]
I've seen several cases now (one recently in HolacracyOne) where a role took on some activity because someone asked and they thought it maybe/vaguely fit their role's purpose, but where the Circle Lead of the containing circle was clear that the activity did not serve the purpose or accountabilities of the circle at all (it wasn't just that the Circle Lead wouldn't do it that way and was wanting to control the implementation, and it wasn't just that a specific action or project didn't fit, but that an overall activity stream didn't fit).  This is an interesting tension to try to resolve as a Circle Lead in the current ruleset.  You can't solve this easily in governance - just adding an accountability or even a domain elsewhere doesn't necessarily change anything.  The best tool a Circle Lead has is a prioritization or strategy, to effectively say everything else the role might focus on is more important to the circle than this activity that the Circle Lead thinks doesn't fit.  That works, but it feels really weird to use that tool this way.

So, that brings up the question: how can a circle lead constrain activity (not just specific projects/actions) that they believe doesn't serve the purpose or accountabilities of the circle?  One option is to give the circle lead the authority to judge an activity as outside the scope of the circle, and have that automatically mean no role can interpret that activity as serving their role's purpose (although they still could do it if it served an accountability; I'd limit the constraint just to interpretations of what serves the purpose, because if it fits an accountability of the role, it seems like resolving that via governance within the circle is really important, as some other role may be relying on that activity).

Thoughts/reactions?

**Comment by leword** [comment]
Couple thoughts:

1. could it be resolved by narrowing the role's purpose in governance?
2. as I understand interpretation of other parts of governance goes to Secretary if there's a conflict of interpretation;  could LL & role-filler go to Secretary with "would you interpret this activity as serving this role's purpose"?  If the answer is yes, goto #1.  If no, then the role filler knows they're effectively doing IA/II

**Comment by brianjrobertson** [comment]
Hmm, interesting...  #1 wouldn't have helped in this case, but #2 could have done it and makes some sense to me.  I'll reflect on that further, and I welcome other thoughts anyone has as well.

**Comment by julianeroell** [comment]
Besides clarifying the _Role's_ purpose in governance, it may also be an opportunity to clarify the _Circle's_ purpose and accountabilities...

**Comment by sitron** [comment]
@brianjrobertson how do you differentiate an "activity"/"activity stream" from a "project"? 
My first thought is that giving more authority to the LL to judge whether an activity fits a role or not is a dangerous path, and thus the differentiation btw activity and project should be very clear. 

It looks to me that the problem should be how to make sure the role is sufficiently clear so that no misinterpretation can be done rather than how to coerce a role filler. But maybe if you give a concrete example it would be easier to understand why clarifying governance doesn't help?

**Comment by brianjrobertson** [comment]
Note I'm actually not suggesting we consider giving the Circle Lead authority to interpret what fits in a role... just what fits in the **_circle_** overall, and have that then constrain each role's interpretation.  But I'm torn on this - it still seems easy to misuse/overuse, and there's always the secretary interpretation avenue that could be used instead... although I often find I really wish I or another circle lead had this authority; it seems a more direct way to enact an important part of holding the boundary of the circle: keeping activities that don't fit our purpose out of the circle.

**Comment by gvandegrift** [comment]
A specific example might help.  I'm imagining that it would just be a conversation with the role filler.  If that role filler doesn't come around to the Circle Lead's way of thinking, then perhaps the conversation evolves to what purpose would make it clear to the role filler that the activity stream in question isn't appropriate.  If that's not productive, then I guess I would begin to wonder if the role filler is actually a good fit for the role.

**Comment by oliviercp** [comment]
By nature, purposes are often less specific and concrete than accountabilities so they leave more room for interpretation. Purpose is also holarchical and I think the constitution could reflect that better. Without some kind of constraint on role fillers to interpret their role's purpose within the purpose of the broader context, it's really difficult to restrict/clarify purposes. 

A role's purpose really should be interpreted as "_[Purpose of my role] as it relates to [Purpose of my circle] as it relates to [Purpose of its super circle] as it relates to [Purpose of that super circle's super circle], and so on..._"

It's not entirely clear in the constitution right now. Article 2.1 only says you have the authority to take action you believe "_is useful to enact your **Role’s** Purpose_". And yet in 1.3, it defines a circle as a "_container for organizing Roles and Policies around a **common Purpose**_". And in 1.3.1 it adds that a Role/Circle can _" further break down how that Role achieves **its** Purpose_".

So by reading these several articles, it is pretty clear to me that a role's purpose is to be interpreted within the scope of its circle's purpose. But it may not obvious to the casual practitioner in that it requires piecing things together, and the fact that a role's purpose has a scope of its circle's purpose is not framed as a constraint but just as informational context. 

So to address the tension, I think it'd be useful to clarify/frame that scope as a constraint on the role filler for interpreting their role's purpose. 

The next question is regarding how we resolve differences of interpretation. It makes sense to me that the Circle Lead's interpretation would trump the role's filler interpretation, since they're holding the overall circle's purpose, and like any other role, they get to interpret it. However, like for any other role, their interpretation may be challenged and brought to the Secretary to make a ruling. I think the same mechanism can apply here. It's consistent. 

The only question remaining for me is which Secretary can make a ruling on it; should it be the circle's Secretary, or the broader circle's Secretary? I haven't thought it through entirely so I'm not 100% convinced of my stance here, but it seems to make sense to me that the broader circle's Secretary should make the ruling, since the circle is part of that super-circle, and the circle's purpose should be interpreted within that broader circle's purpose.

**Comment by chrcowan** [comment]
@brianjrobertson I like Lewis's suggestion of going to the Secretary for a ruling. That may then create a tension for the maverick role-filler about the purpose definition, etc. (assuming the Secretary rules against them), but they can process that.

**Comment by ericdgraham** [comment]
It seems a little bit heavy-handed and brings the Circle Lead closer to a more conventional manager function. But I can see how that would be useful and may help streamline the circle's activities. While possibility limiting some innovation. Or even limiting the spirit of innovation knowing the CL can cut off a workstream entirely. Hmm. Torn on this one as well. Stepping back, since there's still a great deal of autonomy and personal authority built into Holacracy, this could bring in more of the alignment element and create a more equal balance. Maybe moving slightly more conventional (one way I'm holding it) is useful for overall adoption. Worth experimenting with possibly? Add it into Beta and get some input?

**Comment by brianjrobertson** [comment]
@ocompagne Re the first part of your message above:

> Without some kind of constraint on role fillers to interpret their role's purpose within the purpose of the broader context, it's really difficult to restrict/clarify purposes.

This issue has actually been fixed already in v5; §3.5 on Interpreting the Constitution & Governance now reads:

> As a Partner of the Organization, you may use your reasonable judgment to interpret this Constitution and anything created under its authority, including how these apply within a specific situation, and then act based on your interpretation. In so doing, **_you must interpret all Governance in the context of the Purpose and Accountabilities of the Circle containing it, and avoid using any interpretation that conflicts with that context._**

I'm wondering now whether to clarify that this means "the Circle containing its purpose **_as interpreted by a Circle Lead_**", or whether to leave that unspecified and up to interpretation and Secretary ruling.  And I think I'm going to go with the latter for simplicity.  As a Secretary, I'd probably rule generally that this clause as-is means no one can interpret something within the purpose of their role that the Circle Lead says it outside the purpose of the containing circle; but even if a Secretary didn't rule that way generally, each specific conflict case could still be brought to them.  So, I'm closing this issue, unless anyone has something more to add; thanks for the dialog!
