### ISSUE TITLE
In the absence of RepLink ...

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#318]
_Sorry for thinking in 4.1 terms here:_

I'd like Holacracy to have a rule to solve absences of Rep Links.

Take the example of grouping roles in a new circle. This new circle has a default LL: the LL of the outer-circle. The organisational change hasn't interrupted to top-down chain of information. Yet this new circle has no RepLink and thus the bottom-up chain is broken. This gives a power to the LL role it should not have, since it now is the only channel to the outer-circle.

Possibilities:
- "in the absence of an elected RepLink, any core-member of the circle may act as such in the outer-circle meetings".

**Comment by brianjrobertson** [comment]
I'm not clear why this is an issue; why can't someone just call for an election of a rep link and then use that pathway?

**Comment by benoitpointet** [comment]
Damn. 2.5.4.d solves the case: "the first Core Circle Member of the Circle to declare he or she is acting as the surrogate".

**Comment by brianjrobertson** [comment]
That's in v4.1; in v5.0, the surrogate section you're referring to is specifically/only for Facilitator and Secretary.

**Comment by benoitpointet** [comment]
Why having removed it?

**Comment by brianjrobertson** [comment]
Because other changes in v5 mean some circles won't want Rep Links (like a circle for a multi-filled role that barely does much), and it's not needed: you need a surrogate for Secretary & Facilitator power to make the meeting work to elect someone else; but for Rep Link, you can just run an election when you need to, and there's never a tactical need for one to make a meeting work.
