### ISSUE TITLE
Disallow requests from partner-to-role in Tactical Meetings (while allowing requests from role-to-role or partner-to-partner)

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#326]
In v5.0 beta, no one may make requests in a tactical meeting unless the request serves one of their roles.  Can anyone think of any cases (ideally ones you’ve actually seen) where it would be useful to allow a request to come from a partner vs. one of their roles?

**Comment by matthiask** [comment]
What is the harm you're trying to prevent by disallowing requests from partners?

It seems to be that this restriction is not necessary since the role-fillers are themselves responsible to interpret whether an action or a project fits their own interpretation of their role.

**Comment by klaas1979** [comment]
I ask myself about Individual action. This is a request from a partner as rolefiller within the circle? I.e. I request from the Lead-Link to find an apropriate structure for my individual action. Maybe contrived but a case for this example?

**Comment by RS-DU34** [comment]
> What is the harm you're trying to prevent by disallowing requests from partners?

I think the harm would be a "request-fest" (especially in less mature implementations) of roles making requests that they _think_ will help someone else. If the other partner needs something out of a tactical meeting, they could just do it outside the meeting.

**Comment by RS-DU34** [comment]
> I ask myself about Individual action. This is a request from a partner as rolefiller within the circle? I.e. I request from the Lead-Link to find an appropriate structure for my individual action. Maybe contrived but a case for this example?

no, an individual action is a specific "exception" scenario of someone in the organization taking an action outside the normal rules of engagement due to a critical situation; pay special attention to the "Communication & Restoration" section in order to "restore balance" after an individual action - but this GitHub issue is not related to this so we should probably not continue on this subject in here - I recommend you take another read at the individual action section and take your doubts to the Holacracy community: https://community.holacracy.org/topics

**Comment by LouisChiquet** [comment]
Some people around the table during a tactical meeting maybe don't fill the role which have authority over a point, or fill a role which actually care about the point, but just happens to personally have the experience, and sometimes, it's useful for them to just add a point of information to the agenda and deliver their content. Saw that happens a couple times and be very useful for the purpose of org.

**Comment by leword** [comment]
Not one I've seen exactly, but I'm thinking of a partner requesting something from an HR/ People/Partnership role.  There might be a role that's specifically designed to provide a service to partners, and it seems like it would be weird to disallow asking for use of that service in a meeting.     

Although I suppose I could also imagine this the other way-- like that might be exactly the case where's it's useful to have this rule to cut it out; so I'm not sure that example proves/disproves anything.  

I think the harm this rule could prevent, is either: 
1) role-fillers accepting requests on the assumption that filling the request is in some way in service of the overall purpose of the circle or the organization, when it isn't..
or
2) having to check _every_ time to make sure the request is service of the circle/org.

There's a certain streamlining that comes from being able to assume that if I take on this thing you requested, that getting it to you will actually be helpful to some common purpose, rather than having to wonder or explicitly check on it every time.  

I don't imagine that this restriction would prevent anyone from providing information or context in an agenda item.

**Comment by oliviercp** [comment]
_EDIT: Sorry my hashtags are converted into links; I'm just referring to the numbered list 1, 2, 3 in this comment, don't click on the links!_

I start with the assumption that tactical meetings are to focus on the work of the circle, not address people's (inter)personal tensions _unrelated_ to the work of the circle. Now there are also (inter)personal tensions _related_ to the work of the circle... So to better think about the question I find it helpful to differentiate the different types of tensions that might show up:

1. Role tensions coming from roles in the circle --> "My role A needs XYZ from your role B"
2. "Partner tensions" related to the work of the circle --> "I have an issue collaborating with you on this project (of the circle) because you have bad breath"
3. "Partner tensions" unrelated to the work of the circle --> "I don't like the food that our company restaurant serves at lunch"

It's pretty clear that #1 serves the purpose of the tactical meeting and #3 doesn't. But #2 is the grey area where I can see cases for partner tensions being useful to process during tactical. 

The risk is that the boundary between #2 and #3 is up to interpretation, it's not black and white. I can easily imagine some people making the case their tension belongs to #2 when it's borderline. E.g. "I'm not being paid enough to be responsible for this project you're asking of my role", "I don't like the lunch food from the restaurant so I don't eat much, but then I don't have enough energy to work on this circle's work in the afternoon". 

So if we were to allow partner tensions in tactical meetings, I think it'd be important to have some ways to differentiate tensions from category #2 and #3.

**Comment by brianjrobertson** [comment]
> What is the harm you're trying to prevent by disallowing requests from partners?

Yes, a request-fest, or a boundary blur; e.g. someone taking meeting space to make a request to serve themself personally, or to serve a role in another circle that's intentionally not invited to the meeting.

@LouisChiquet I'm only talking about requesting projects/actions, not sharing information; the intent of the current language is not to restrict that to serving the agenda owner's role, so I think the case you've raised is already covered.

@ocompagne That's helpful, thanks; we could limit requests to those that serve the circle's purpose, which would attempt to allow option 2 but not 3. But I'm leaning towards keeping the current restriction in place so only option 1 is allowed, just to avoid anyone having to judge between 2 and 3, knowing there are plenty of other times & places those can get addressed.

If anyone has further thoughts, please share; otherwise I'm closing this issue with an answer of "no, they should not be allowed".

**Comment by chrcowan** [comment]
Well, I can think of situations in which I might take IA/II for something not currently captured in a defined role, and then I might request something from someone else. This has shown up in new circles in which there is a lot of individual initiative going on both on the requesting and requested sides. And I'm only mentioning that because I think there is a good argument there for broadening the language to include anything that serve's the circle's purpose rather than only to serve one's own role. 

The challenge with thinking of specific examples is that on the requesting side it's often not obvious the perspective/context FROM WHICH a tension is felt. Sometimes it's like 35% assessment design and then 35% assessor, and maybe 10% design services, and maybe 5% some undefined role, but figuring all of that out often isn't needed when requesting something from someone else, because the more important question is, "What role are you requesting action FROM?" Roles take actions and make decisions, but people and roles feel tension. So, I would say that the role-or-IA/II-restriction for _accepting requests_ stays, but I can't think of what benefit a role-only rule for requests has over just using the circle's purpose as a guide.

**Comment by brianjrobertson** [comment]
@chrcowan That does resonate, though I'm still stuck on the potential harms I see to allowing allowing requests not from an invited role; beyond the two named above, another is that it likely reinforces the conventional power dynamic of "access to a meeting gives you power", rather than "roles you fill give you power".  Preventing them removes that potential harm and the other two named above, and I think would generally help instill the paradigm shift that sustainable Holacracy practice requires.  So I'm still leaning towards preventing them, but I wanted to put out one more call for other perspectives before landing on that...

**Comment by chrcowan** [comment]
@brianjrobertson ooohhhh....yeah, the whole "access to a meeting gives you power" is a good point I didn't consider. Well, a lot of this comes down to the specific phrasing you're considering using to encode the prohibition against non-role-based requests, because I'd still like to allow the cases I'm envisioning. Will you share the specific phrasing?

**Comment by brianjrobertson** [comment]
@chrcowan It's the current phrasing in the v5.0 beta; see [paragraph (f) in §2.4.2](https://github.com/holacracyone/Holacracy-Constitution/blob/v5.0-beta/Holacracy-Constitution.md#242-facilitation--process).

**Comment by chrcowan** [comment]
@brianjrobertson that doesn't trigger any warning bells for me. Looks good. :)

**Comment by brianjrobertson** [comment]
Okay, I think I've figured out a way to ensure we still disallow the third undesirable case @ocompagne raised, while still allowing the useful examples of the second, and making the line between them more clear:  Allow requests from role to role, from partner to partner, or from role to partner, but disallow requests from partner to role.  So, requests for actions or projects to solve tensions like "I'm not paid enough and want a raise" or "I want lunches provided" would almost definitely go nowhere, because those are things a partner would request from a role and that's not allowed; but requests for Working Agreements from another partner would be fine, like "I'd like you to show up to work by 9am so we can collaborate".  This distinction also allows the needed space for the interpersonal apps we've been working on, which support requests to partners with new processes.

**Comment by oliviercp** [comment]
Nice! I like how clean the distinction is in theory. In practice, I have a little doubt that it would always be so obvious, but I'm not finding any example at this moment. I.e., if I request an action (as a partner) from someone else, I wonder if it's always clear whether I'm asking the person as a partner or from their role, especially in those cases where I want to influence how the partner energizes their role. I don't find a clear example so I'm not saying it doesn't work, I just wanted to call out that little voice in my mind.
