### ISSUE TITLE
Allow additions to Circle Lead and remove default accountabilities

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#330]
We (IGI) have observed that several Lead Links clients have withdrawn the managerial functions for which they remained responsible from a business perspective. Let's take an example: The Lead Link is accountable for assigning people to roles in his circle. Here is the blind spot: nothing is specified about the fact that in order to be able to assign people to roles, it is necessary for a Lead Link, on the one hand, to identify and manage the skills that are required in the circle to do its job, and on the other hand, that he knows the skills of the people well enough to be able to assign the right people, which presupposes that he follows the skills of these people. That makes sense, doesn't it? We observe that sometimes (quite often), these last, common sense activities that were managed by these managers before adoption, were no longer managed after adoption. Why is that? Because Lead Links are so keen not to break the rules of the constitution - and there is an explicit statement that no accountability can be added to Lead Link role - that often **unconsciously** they stop putting energy into these activities which are nevertheless key to the smooth running of their circle and the company. Three clients have in fact made a constitutional amendment to complete the Lead Link role to fill this blind spot. And now, for them, the blind spot has disappeared.
I therefore propose to complete the definition of the role of Lead Link to make the constitution more functional and avoid this blind spot that penalizes. Otherwise those companies that have been practicing Holacracy for 4, 5 years and that persevere towards a more and more mature practice (companies like we would like to have many more) will have to renew an amendment in 5.0.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet I love this inquiry!  I've seen this issue too, and it brings up lots of connected issues and questions for me.  Some thoughts:

Generally, on most roles, accountabilities are useful if others need to be able to expect it of the role (and thus request actions/projects around it) even beyond what the role would choose to do on its own to serve its own purpose.  We know that for most roles, it's not useful to try to clarify everything the role should do in its accountabilities; roles do lots of things to serve their purpose, and most are not useful to add as explicit accountabilities.  So, what you're suggesting here opens the question:  Is this true for Circle Lead as well, or does Circle Lead need to be special in this regard for some reason?  Perhaps Circle Lead does need to be special, in which case we should clarify these and likely several other general functions that we know good Circle Leads will do.

That may really be the best answer here.  And yet, I see two other possibilities that might address the tension and I think are worth at least exploring/considering:

1) Perhaps Circle Lead does not need to be special in this regard, and we can treat it like any other role and not try to document everything it should do as accountabilities.  If that's the case, then we should probably **_remove_** the accountability you reference around assigning roles (and perhaps one or both of the others as well).  I imagine this might actually solve the tension; it lets coaches take a clearer stance that the Circle Lead's job is to express its purpose (like all roles), and to do that, it has several special powers given in the constitution, including role assignment/removal.  But without that being an accountability, it makes it more clear that of course the Circle Lead needs to go beyond the accountabilities; in fact there may be none on the role at all to myopically focus on.

2) Again, if Circle Lead is indeed not special in needing extra up-front definition, then perhaps we should lift the restriction on adding accountabilities to it, and allow any additions to cascade to sub-circle Circle Leads, thus allowing what you describe that some clients have done, but without requiring a constitutional amendment to do it.  This would also solve some other tensions, like when a company uses a special strategy-setting process, or OKR's, and actually does want/need to add a function to all Circle Leads (several other processes/apps may reasonably desire this as well, without it being a bad idea to do, and it'd be nice if they didn't require a constitutional amendment to adopt).  I know this change would open up a potential bad practice, of adding specific circle operational functions to the Circle Lead rather than creating a separate role for them; but perhaps preventing that bad practice constitutionally is actually creating more harm than good by preventing the good-practice reasons to add to Circle Lead?  We could also potentially mitigate the bad-practice cases, at least in part, by having any additions to Circle Lead automatically cascade and apply to all sub-circle Circle Leads (at least until removed in sub-circle governance).  That way, you could only add something to Circle Lead if it were relevant for **_all_** sub-circle Circle Leads as well; this would still allow cases like in your example or the OKR example, but would prevent a circle from sticking one of its own specific operational functions on Circle Lead, as these wouldn't apply in sub-circles.

Thoughts?

**Comment by bernardmariechiquet** [comment]
Thank you very much @brianjrobertson for the quality of the questions you ask that open up new horizons that I hadn't thought of yet.
Intuitively, I would opt for the second of the two paths you propose (we should lift the restriction on adding accountabilities), probably because it is closer to the reality of what I encounter in the field.
We can consider that the constitution assigns to the role of circle lead the minimum expected functions, which is his job since the constitution, in reality, makes explicit the managerial functions (which were not explicit in the conventional model) and distributes them on roles, policies, and processes.
We can also consider that the anchor circle that adopts the constitution can define the managerial expectations of the organization's circle leads, which are indeed expectations for all circles. This is typically how the clients who made amendments have functioned. They defined and described the expectations of the circle leads. They even created a community of circle leads to help each other by sharing best practices in management.

**Comment by bernardmariechiquet** [comment]
A special treatment could be added by making it explicit that only the anchor circle can add accountability to the role of circle lead.
This would correspond rigorously to the reality of the cases of the companies I helped. In short, simply avoid this type of amendment by integrating this new feature to redefine the role of Circle Lead by the anchor circle. It seems logical to leave it up to the ratifiers who change the management system, to let them customize the one they want.

**Comment by colinfrei** [comment]
I think it’s important to clarify that there are actually three paths - 1. and 2. above, but also 3. the Circle Lead _does_ need to be handled differently in this regard.

My understanding is that the reason accountabilities _can’t_ currently be added to the Circle Lead, is that it’s to prevent that role from being overloaded, and slipping back towards a traditional manager role. By not being able to add accountabilities, it’s easier to point out that people are not actually asking the Lead role, but are slipping back into old habits of asking the manager.

While those effects can be countered with coaching, having that more explicitly in the constitution does add value in my eyes though.
Keeping the Circle Lead role slim supports the power shift away from the traditional hierarchy.

**Comment by colinfrei** [comment]
To respond to the specific issue:
> Here is the blind spot: nothing is specified about the fact that in order to be able to assign people to roles, it is necessary for a Lead Link, on the one hand, to identify and manage the skills that are required in the circle to do its job, and on the other hand, that he knows the skills of the people well enough to be able to assign the right people, which presupposes that he follows the skills of these people.

‘_To identify and manage the skills that are required_’
isn’t that implicit in the ‘_monitoring the fit_’ accountability? But yes, maybe implicit isn't good enough.

'_knows the skills of the people well enough to be able to assign the right people_’
That implies that candidates for a role come from a more or less pre-defined group of people. In many circles at Liip there’s a wide range of people from across the whole company that are potential role fillers. There’s no chance for me to keep up-to-date on the skills of 180 people well enough to make that decision, but it’s also not necessary. It just needs a bit of work when assigning a role filler, similar to what needs to be done when hiring someone.

**Comment by brianjrobertson** [comment]
Okay, I'm going to proceed with the changes from both of my two options above.  I am not going to limit the power to add to circle lead to just the Anchor Circle though - this violates one of the key principles I've discovered is important and am using in evolving the constitution for v5, which is that the Anchor Circle should have no special-case rules in any way (the reasons why are longer than I want to convey here and would be a tangent from the main point of this thread).

I also don't think allowing additions to Circle Lead will be a problem for the point @colinfrei raises, as long as any additions automatically cascade any apply to all sub-circle Circle Leads; that stops a circle from using the power to just handle a specific operational function, which is the real risk I see there.

**Comment by chrcowan** [comment]
@brianjrobertson This is cool and different and handled the way you describe it in your comment above, I think it even makes sense. :)

**Comment by bernardmariechiquet** [comment]
> Okay, I'm going to proceed with the changes from both of my two options above. I am not going to limit the power to add to circle lead to just the Anchor Circle though - this violates one of the key principles I've discovered is important and am using in evolving the constitution for v5, which is that the Anchor Circle should have no special-case rules in any way (the reasons why are longer than I want to convey here and would be a tangent from the main point of this thread).

Okay, this is great, appreciated.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I know I'm a little late in the 5.0 process, but I'm taking a chance knowing that I wouldn't want to make a constitutional amendment on 5.0 right now and that it would be great if GlassFrog software had this great feature. 
One more point on the question of the circle lead. Many of our clients have come to the conclusion that they need two distinct roles instead of the circle lead for the simple reason that the polarity of coaching role leads takes a back seat to business, even in the case where the circle lead has all the required skills. I therefore suggest that a circle can create one or more other structural roles, and that these roles automatically apply recursively to each sub-circle.  This may be an addition to [article 1.5.3](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#153-amending-the-circle-lead-role)
I am prepared to give further explanations if necessary.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet Hmm, this one is tricky; it's a big change, and one that has the potential to be severely misused - we've seen clients wanting to do this too (mandate all subcircles have a specific role), but the cases I've seen always seem to me like a broader circle over-controlling, instead of just telling the sub-circle what they're accountable for and letting the sub-circle self-organize around it.  So I'm not sure I can think of any cases where a client wanted to do this *and* where it seemed like a good idea to me to let them (plenty of the former, but none of the latter).  If you have more specific cases/arguments you can offer around why you'd want to let the client do this, I'd love to hear them (ASAP if you want them considered for v5.0).  Please open a separate issue if so, to keep that distinct from this one.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Duly noted. I've opened a new issue https://github.com/holacracyone/Holacracy-Constitution/issues/371
