### ISSUE TITLE
Generalize Money as Resources

### ISSUE THREAD

**Issue by plamarque** [holacracyone/Holacracy-Constitution#333]
In 

> 2.1.3 Don't Spend Money

the paragraph explains that it's not only about money but also other assets of the Circle. Hence, shouldn't we generalize the term Money to Resources ?

Also, since the paragraph explains the process to actually spend, I suggest to rename the paragraph's title  : "2.1.3 Spending Circle Resources"

**Comment by brianjrobertson** [comment]
I see two issues with this:  One, it breaks the parallel construction of the sub-paragraphs in 2.1; currently they all start with "Don't" followed by some simple summary of what not to do, and I think this simple formation and parallel construction is really useful in this section.  And two, the term "Resources" has been really problematic in the past, because it surfaces lots of confusion about whether people's time counts as a "resource" - and if someone interprets that it does, the rest of the rules start to breakdown.  This section was specifically updated to refer to "money" and "assets" and limit the use of the word "resources" to limit this potential confusion; and using it in the paragraph title seems like the place most likely to trigger this confusion.
