### ISSUE TITLE
Amendment: alternative language conventions (Hypoport)

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution#344]
_At Hypoport we've implemented some changes around language and embedded them in our own version of the facilitation cards. The changes are mostly didactical in nature but have the potential to trigger changes in the language used in the constitution. We've received a lot of positive feedback and seen good results from practice so far. I share it here to inspire changes in the relevant places in the document_ 

**Here's a brief overview of the proposed changes**

- "objection" --> "safety concern" / "concern"
- "Objection Round" --> "Safety Check of the Proposal"
- "valid" --> "needs to be integrated" / "duty of integration"
- "valid objection" --> "a harm that needs to be integrated"
- "invalid" / "not valid" --> "doesn't need to be integrated (here)" / "independent tension" / "not admissible"
- "NVGO" --> "formal error" / "formal mistake"

_The following are the relevant excerpts from our publication here:_
https://medium.com/hola-be/evolution-of-the-holacracy-facilitation-cards-78778706cf99

We changed some language and the name of a process step. What was previously called **“Objection Round”** we now simply call **“Safety Check of the Proposal”** ­– because that is what it is after all. This explanation has been part of our framing for the Objection Round for quite a while. Instead of having to explain it, again and again, we simply decided to change the name of the step itself. That is easier.

We stopped using the word “**objection**”. Instead, we talk about “**safety concerns**”. Additionally, these “concerns” are not “**valid**” or “**invalid**”, but rather “**need to be integrated**” or “**do not need to be integrated**”. This is a bit longer, but the intention behind these changes is to reduce the subtle inner resistance that is provoked by using the words “objection” or “invalid” (“I am wrong!” / “My colleague is wrong!”) The old terminology sounds like being in a trial in which someone is being convicted in the end and in which there are “winners” and “losers”. Nothing could be further away from the intention of the process of integrative decision-making. So, let’s get rid of it.

“**Safety concerns that do not need to be integrated**” are being experienced as far less aversive and confrontative than “**invalid objections**”. The willingness to share “safety concerns” (formerly “objections”) and to explore them open-mindedly increases. Sharing “concerns” that help to make the proposal safer is much easier psychologically than raising “an objection against a proposal”.

The value of a “**safety concern**” is much easier to grasp for all parties involved than the value of an “**objection**”. Even though “objections” clearly help to make the most of the governance process, the word feels like the very opposite of that. “Objections” taste like petty quibbling, an attitude of refusal, veto, blockade or personal disapproval. The term is an impediment, which is why we decided to erase it from our vocabulary.

First of all, “safety concerns”, or shorter “concerns”, are what they are — a subjective perception. That the person feels a tension is an undisputable (phenomenological) fact. It is therefore not very helpful to label the concern as being “**valid**” or “**invalid**”. People feel judged. Therefore, we propose to use different adjectives. The process helps to filter out “safety concerns” that “**do not need to be integrated**” (formerly “are invalid”). In German, we use the shorter phrase “nicht integrationspflichtig” which can be translated as “**no duty of integration**”. These concerns may still be meaningful tensions for the respective “**harm-sensor**” (formerly “**objector**”), but according to the constitution, they do not need to be integrated at this stage of the process and can therefore be safely ignored.

We renamed “**non-valid governance output — NVGO**” as “**formal error**”, because that is ultimately what it is. The cryptic acronym “NVGO” now no longer is a mystical trump card which confuses beginners of the practice, because somebody suddenly slams it onto the table out of the blue — often without a corresponding explanation.

As the name indicates, a “formal error” is an error concerning the form of the proposal, not necessarily its content. The proposal violates the grammar of admissible governance constructs, as defined by the constitution. This is like the automatic grammar check of a word processor which underlines the faulty constructions in red. The content may be ok, but the form is not ok. That’s all there’s to it, really. A formal mistake is usually integrated easily and swiftly during the integration by restructuring the proposal.

A “**formal error**” (formerly “**NVGO**”) does not constitute a reason for prematurely abandoning the processing of the entire proposal, as it is often assumed. A premature abandonment of the process does not help the proposer to solve his original tension at all. Even worse, he feels “wrong” and is less likely to try to use governance for solving his tensions the next time. Such catastrophes are avoidable by eliminating the misleading word “**non-valid**” (the “**N**” in “**NVGO**”) from the vocabulary completely while at the same time connecting the concept of “**formal error**” with the concept of “**needs to be integrated**” (German: “integrationspflichtig”). Formal errors always need to be integrated, i.e. one has to (and usually in most cases can) integrate them during integration.

**Comment by brianjrobertson** [comment]
@denniswittrock I love that you guys are experimenting with this and looking for language that makes learning Holacracy easier!  I actually read your blog post when you first released it, specifically to look for anything that seemed useful to change in the Constitution, and I asked a couple of our experienced coaches to do so as well.  But, none of us came up with anything from it that we thought made sense for constitution-level changes; so I'll share some of our thinking here, and I'd love to hear if you or other coaches disagree, and why (although just in reviewing this again now, I think I do see one change at least that makes sense to me to make - more on that below).

Also note I'm not pushing back on using the language you suggest in some contexts - as you say, it's perfectly compatible with the constitution and not conflicting with the rules in any way, and I believe you when you say how much value it's added for your teams in practice, and I suspect that will be true for others as well in some contexts.  I'm also not pushing back on the process card changes - our role that maintains those is likely to integrate some of your changes into ours, and even the ones we don't integrate may still be better in your environment and others.  So, to be clear, in this context here I'm only looking at and referring to possible constitution changes, and not to potential process card changes or language usage outside of the constitution.

Given that, there are several parts of what you've written that aren't constitutionally relevant.  For example, "NVGO" (and "Not Valid Governance Output") never appears in the constitution, so that's not relevant to this discussion.   "Invalid" also never appears, except in one case in a header about governance in general, but never applied to "Objection" - so constitutionally, there is no such thing as an "invalid objection" already.  As for "valid objection", that's not a defined term, although the adjective "valid" is used before "objections" in a few cases, so that part is relevant, although I think it's important to differentiate common language practice, in which "valid objection" is thought of as a thing, and the constitution, in which "valid" is merely an adjective sometimes applied to the defined thing of "Objection".

So, after accounting for all that, I see three constitutional questions in what you're raising here:  (1) Should we rename the term "Objection" to something else; (2) should we change the usage of the word "valid" as a descriptor of certain Objections; and (3) should we change the name of the step "Objection Round".

For (1), I don't think we should.  I haven't found anything that seems better, even though I resonate with the problems that stem from using "Objection".  I don't think using "concern" instead works, because "concern" is already used to describe something broader than "Objection"; in the constitutional usage, a "concern" is a superset of both what we'd commonly call valid and invalid Objections; people raise "concerns", and then we test them to see if they are actually "Objections" or just concerns that do not meet the Objection threshold.  If we used "concern" to mean what "Objection" currently means, then we need another word to describe that superset, and I don't think there's another word that makes sense for that.  I also don't think it's practical to simply not use a term to describe the subset of concerns that need to be integrated; that would require a massive rewrite of lots of text, and I think the result would be far less clear.  Another option is to use a multi-word phrase in place of "Objection", like "concerns that require integration"; of these options for removing "Objection", I think this option is the strongest... but I still think it's far simpler and more clear to define a single-word term to mean that in the Constitution, rather than using a long phrase everywhere we want to refer to what is now called an "Objection".

For (2), about the usage of the word "valid", I think perhaps we should make a change here.  Currently, "valid" appears before "Objection" in a few places, and it's completely redundant in every one.  Objection is already defined to mean specifically those concerns that meet the criteria for needing to be integrated; i.e. the definition itself already includes what the distinction "valid" is trying to say.  So, we could simply drop the word "valid" before "Objection" in all cases, and not lose any clarity.  I'm curious if anyone has thoughts on this before I go ahead and make that change.

For (3), about whether to change the name of the step "Objection Round":  If we're still using the term "Objection", then I'm not sure this change would help more than it would add potential for confusion.  But I'd love to hear other opinions here; anyone think we should rename that step to a "Safety Check Round" or something similar, even if we are still using the term Objection?

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Here's my take on that one.
Unfortunately, I also don't know what word to use instead of Objection. Perhaps it will appear later in our evolution, or perhaps we will become more comfortable with the association of that word and the meaning we put into it.
As for the word Valid, I don't think it adds anything. Let's just use it as an adjective, which it is, without putting more emphasis on it.

**Comment by plamarque** [comment]
In my experience people are often hesitant to object. I facilitated many meetings where I had to push participants to say something during objection round where I knew there was an unpopular proposal made by someone but others were hesitant to object. When I managed to encourage them to speak out  they often started by « well... I’m not sure if it’s an objection or not but I think...<insert honest concern here> ».

Hence, avoiding the term objection could be less intimidating. I will try the « safety check »  as I think it has the potential to put participants at ease by sounding like the objection qualification is up to the process, not to them.

Also (I’ll have to double check this) I think V5 constitution uses the term « potential objection » a few times. To me, it means those are actually not objections. In fact there is no such thing as a valid or a qualified objection, there are concerns that a test (a check) transforms into objections as part of the process.

Also note that at the end of the process, the objections should not exist as they have been resolved. So they are an internal construct. For the users, their sensors alert them on concerns they have and the output of the process is new rules to follow.

**Comment by brianjrobertson** [comment]
Okay, I'm going to clean up the language to remove the use of "valid" as suggested above, and consider this issue closed; however, if anyone (or you @denniswittrock as the submitter) sees more language changes you think are worth discussing further, please post here and I'll reopen this issue.
