### ISSUE TITLE
Merging role-filler and role-lead

### ISSUE THREAD

**Issue by leiomokusei** [holacracyone/Holacracy-Constitution#346]
I understand that there is a distinction in the constitution between :
- role-leads, who are "assigned", typically by the lead of the super-circle
- role-fillers, who include role-leads + elected roles

Why not simplyfing by saying that all are leads? A facilitator is a lead of the role "Facilitator", same with Secretary/ Rep.

It would have the pros of avoiding the dual use of "role-filler" and "role lead"
I am wondering what are the cons?

**Comment by brianjrobertson** [comment]
I actually just removed the distinction of Role-filler while processing another comment (replaced it with Role Lead), as it only appeared in one place (a Circle Rep accountability) aside from headers.  But I hadn't considered that it's somewhat ambiguous whether those elected into roles are "Role Leads" - it's actually the intent already that they are indeed "Role Leads", although I see why you might interpret it otherwise, because that isn't said explicitly.  Still, I'm going to assume that the most likely interpretation now is that they would be considered "Role Leads", especially now without another distinction used at all.

**Comment by leiomokusei** [comment]
The edit made solves part of my tension, but not entirely because:

1. There is still a mention of "role-filling" in:
> 1.3 Responsibilities of Role-Filling

2. The following sentence suggests in my opinion that only **assigned** (eg not elected) role fillers are leads mostly because, as you say, there is no explicit mention that elected roles are leads:
> Anyone so assigned then fills the Role as its "Role Lead". 

As a suggestion, assuming that you consider that "filling a role" is a synonymous to "being role lead", then I would state clearly that equivalence somewhere.

An idea could be the rewrite of the quote above by
> Anyone filling a Role is its "Role Lead". 

I imagine it could be either in the sections Role Definition/ Role Assignement (although the fit wouldn't be perfect with the section title) or a new section "Role Lead" between both.

What do you think?
