### ISSUE TITLE
Clarify Circle Members definition

### ISSUE THREAD

**Issue by leiomokusei** [holacracyone/Holacracy-Constitution#347]
The constitution says :

> Each Circle has a group of "Circle Members" who may represent its Roles in its Governance Process.
> A Circle's Circle Members include all Partners filling its Circle Lead Role, as well as each Partner serving as Role Lead for a Role in the Circle.

What is the meaning of the word "include" in "A Circle's Circle Members include all Partners [...]"?

Is it because it also includes the potential Circle Rep ? If yes, what about clarifying it in the definition for clarity purpose? Something like

> Circle Members are all Partners filling its Circle Lead Role, each Partner serving as Rep Circle for a Role in the Circle, as well as each Partner serving as Role Lead for a Role in the Circle.

Or would it be possible to have other members? For example Partners with no roles ? If yes, what about clarifying how to decide how to accept/ remove members from a circle (governance process, other)?

**Comment by brianjrobertson** [comment]
No specific reason for that, and I do see the ambiguity it creates.  The intent is to keep Circle Members exclusively to the Role Leads within the Circle, plus Circle Reps (who also act as Role Leads for the Role/Circle they represent).  But we can't reference Circle Rep there because it hasn't been defined yet, and the constitution follows a pretty strict standard of not using a defined term before it's defined.  That said, I don't think that's an issue - this should just take a simple language clarification.

**Comment by leiomokusei** [comment]
Clearer. A bit frustrating to not have Circle Reps mentioned in the definition, but I understand the priority given to the respect of the standard. I guess a mention of the Circle Rep via Appendix A would have been possible, but probably too much wordy.

Although imperfect, the edit solve my tension because at least its now clear that a Partner without role can't be a Circle Member.
