### ISSUE TITLE
Governance process // asynchronous

### ISSUE THREAD

**Issue by margauxchiquet** [holacracyone/Holacracy-Constitution#357]
First reading this part: “5.3 Governance Process
Any Circle Member of a Circle may initiate its Governance Process by proposing a change to its Governance. To do so, the “Proposer” must first share a “Proposal” in writing with all other Circle Members, using any communication channel allowed by the Secretary. Those other Circle Members may then ask clarifying questions, share reactions, and raise concerns about adopting the Proposal. Each concern is an “Objection” if it meets the criteria herein, and the person who raised it is the “Objector”.”

I thought we would not held any meeting anymore. It was not clear to me that this process was asynchronous and that we still had meetings.
I would suggest changing it in “5.3 Governance Asynchronous Process”
“Any Circle Member of a Circle may initiate its Governance Asynchronous Process by proposing...”

**Comment by brianjrobertson** [comment]
I discussed this a bit in the recent v5.0 upgrade workshop; let me know if you still have suggestions after listening to the recording of that.  In short, this is intentional - the thresholds defined in there are in place regardless of whether you use a meeting or an asynchronous process to meet them; the fundamental thresholds are now given primacy in v5.0, instead of the process to meet those thresholds taking the lead or being fused together (both were the case in v4.1).
