### ISSUE TITLE
Section 1.2.2 is confusing

### ISSUE THREAD

**Issue by Pam-H** [holacracyone/Holacracy-Constitution#359]
The way the 2 sentences are now, the sentences seem to contradict each other. The first sentence sounds like they can only use a focus if all elements in the Role definition are still relevant within that focus. But then the second sentence goes on to say, each assignment focus is treated as a separate Role and the details apply only within that specific focus. I think I know what you are going for and I think just a couple tweaks to the wording could make it more clear, as follows. 

I suggest the following changed wording:

A Role assigner may focus an assignment on only a specific area or context, if all elements in the Role definition existing at that moment, before the focus is created, are still relevant within that focus. When a focus is used, from that time onward, each assignment focus is treated like an entirely separate Role, and that Role's Purpose, Accountabilities, and Domains, apply only within the focus specified for each assignment.

**Comment by brianjrobertson** [comment]
Hmm, the suggestion is changing the intended meaning - there is no time element to it.  I'm not entirely sure what you're saying is conflicting or unclear in the original, or what you're trying to resolve with the suggestion; can you expand further?

**Comment by Pam-H** [comment]
Okay, this is the text as it stands now.

"A Role assigner may focus an assignment on only a specific area or context, if all elements in the Role definition are still relevant within that focus. When a focus is used, each assignment focus is treated like an entirely separate Role, and the Role's Purpose, Accountabilities, and Domains apply only within the focus specified for each assignment."

I guess maybe it's clear enough?? But I don't really think so.

The first several times I read it, it seemed like the first and second sentences were sort of contradicting each other - like the first sentence was saying all parts of the original Role needed to apply to the focused Role as well, which makes a lot of sense to me,  and that's how it was in v4.1. But then the 2nd sentence was saying the focused Role would be its own entirely separate Role, which is sort of a new thing in GF beta2. Why are you wanting it to be a separate Role? Because GF is now allowing additions to it, that can then be subtracted, while NOT at all allowing the original parts of the Role to be changed?

Even to an English speaker, it sounded sort of like 2 contradictory sentences. I think from the seminar Brian R gave recently, I was understanding a misuse of Holacracy in the past had been people trying to create a focus, and have only part of the original Role apply to that focus, which makes sense to NOT be allowed. 

So I was trying to add something about once a focus was created... but now Brian is saying that is adding a time element that shouldn't be there. That makes me think even moreso that what H1 is trying to do with this part of the Constitution is still NOT clear enough here.

If it seemed contradictory to a native English speaker, won't it sound even more confusing or contradictory to a non-native-English speaker? So I was trying to add wording that would clarify it...

maybe better wording would be 
"before any focus is created"

"A Role assigner may focus an assignment on only a specific area or context, if all elements in the Role definition existing at that moment, before any focus is created, are still relevant within that focus. Once a focus is created, each assignment focus is treated like an entirely separate Role, and that Role's Purpose, Accountabilities, and Domains, apply only within the focus specified for each assignment.

Or if it is really a separate role, instead of just "like a separate Role", maybe it needs to just BE a separate role with a separate name of a Role. For example, maybe the focus becomes part of the name of the Role. Sales for China vs Sales for Europe... Or Partner Partner for David for timeframe X vs Partner Partner for Mary for timeframe Y. 

Another possibility is leave it the way it was in v4.1 but just make it super clear that no one is allowed to attempt to take only part of that original Role into a focus.

Thanks, 
Pam

PS I asked Chris Cowan through CoP to weigh in on this too. He seems to have a particular knack for seeing where someone might get confused by something and giving it extra clarification, or making it more efficient, etc. 

Thanks for all the hard work all of you are doing. And I second what jennyslack said about Yay for version 5.0 beta.

**Comment by Pam-H** [comment]
One more thing. It occurs to me that I actually LIKED the ability of v4.1 to see a Role (I guess it would be a multi-filled Role in this case) with the specific foci next to it. I would not really want them off in their own little world where I could not see the list of foci (multiple focus-es) that apply for that Role with a focus. 

At that point, it almost seems like someone needs to just create a new Role??

I understand that it's a super nice feature of GF to paste the entirety of the Role and its details into the one you split off and created a focus for, and I'm assuming you are trying to give additional freedom to it, by allowing one or a couple of things to be added to just that specific focused Role, without being able to delete any parts of the original Role, unless Governance made that change to all foci. But it seems like it's being made unnecessarily complex for new people to understand a focus, because by that point, you are almost talking about new Roles instead of "like new Roles". Do you really need to give that level of freedom to it? I'm assuming that you are trying to make it consistent to other changes - like being able to add to a Circle Lead's Role, but not take away anything except anything new you added.  ??

**Comment by brianjrobertson** [comment]
@Pam-H Hmm, I'm getting the sense that you've got an idea of what this change allows that isn't aligned with the intent and my own mental model or interpretation of the text.  e.g.:

> One more thing. It occurs to me that I actually LIKED the ability of v4.1 to see a Role (I guess it would be a multi-filled Role in this case) with the specific foci next to it. I would not really want them off in their own little world where I could not see the list of foci (multiple focus-es) that apply for that Role with a focus.

I like this too, and it won't be changing - this change won't affect this at all.

> I understand that it's a super nice feature of GF to paste the entirety of the Role and its details into the one you split off and created a focus for, and I'm assuming you are trying to give additional freedom to it, by allowing one or a couple of things to be added to just that specific focused Role

No, that's not what we're trying to do, and not what this change is intended to allow.  That's the point of the first part of the clause: you can only focus an assignment if all elements in the Role definition are still relevant within that focus.  Perhaps what's not said and needs to be said though is that you also can't later change a role with a focused assignment if the change wouldn't be relevant for all foci.  In other words, the intent is the opposite of what you suggest here, just as it was in v4.1 - this isn't changing.  The whole role definition has to apply to every foci, always.

The intent of "each assignment focus is treated like an entirely separate Role" is not to change anything significant from v4.1, just to clarify some ambiguities it left; that was already the intent in v4.1.  This clarifies things like "what happens if you request a project of a role with different focused assignments" (someone in one focus assignment can't accept for another, because it's effectively a different role), or "what happens if someone in a focused assignment calls a governance meeting for the role; who attends?" (just the people with that same focus assignment, because it's effectively a different role than the other focus assignments), or "if a role-filler creates a policy in the role, does it apply to people in the role with other focuses?" (no, it's effectively a separate role).

If you have any ideas on how the language could more clearly convey this, I welcome them.

**Comment by Pam-H** [comment]
Thanks Brian. That is helpful to me to see what you're aiming for. I will think about it and see if anything comes to me to help the clarity.

**Comment by brianjrobertson** [comment]
I'm closing this for now, but welcome you (or anyone) adding comments afterward if anything comes to you and I'll re-open.
