### ISSUE TITLE
potential addition to 5.3.2

### ISSUE THREAD

**Issue by Pam-H** [holacracyone/Holacracy-Constitution#365]
I have heard Chris Cowan comment, on multiple occasions, that something being confusing, is always a valid Objection. That seems important since one of the key things Holacracy strives for is clarity. So is there a way to add that to the objection tests?

Could 5.3.2 a) be worded:

**(a)** The Proposal would reduce the capacity of the Circle to enact its Purpose or Accountabilities, including by a lack of clarity.

Or alternatively "Including by any lack of clarity". 

Thanks for considering it.

**Comment by brianjrobertson** [comment]
Hmm, I wouldn't consider something being confusing as always a valid objection, and I'd be surprised if @chrcowan would either, but I'll let him jump in if I'm wrong.  I also wouldn't say that Holacracy strives for clarity as a general thing, but rather that it strives for enough clarity to resolve the present tensions.  One of the misuses of Holacracy I often see is people going for "perfect" clarity or just pushing for clarity for clarity's sake, and I think this change would increase that tendency.  The current design intent is specifically that "something is confusing" is only a valid objection if you can point to why that confusion may cause harm, and that concern passes all the test questions (including notably whether you're anticipating that the lack of clarity or confusion will cause harm, and whether it's safe enough to try; if it's safe enough to try something unclear/confusing to someone, then Holacracy's bias is intentionally to try it, not to try to clarify it up-front).

**Comment by chrcowan** [comment]
@Pam-H I think I see what you're going for and I kinda like it because it gives at least one example case. Although I don't think it makes sense to bake it into the rules for that reason alone. I just think of "creates confusion" as a good exemplar for addressing some common confusions about what objections are and how they work.  

With that said, I seem to have created some confusion over things being confusing! I don't think I said, "creates confusion" is always a valid objection, what I probably said was that "creates confusion," always satisfies criterion 1 (harm). And usually satisfies criterion 3 (created by the proposal). My point is that the objection may absolutely still be invalid, but it should be invalidated based on the proper criterion. 

For example, "This creates confusion for John's role," will likely fail criterion 2 (from your one of your roles). I think this is an important point because I often see Facilitators respond to objections like this by saying things like, "Ah, well if it's about one of John's roles, then it's not really harm..." (which isn't true) or, "Ah! it sounds like you're anticipating that it will be confusing for John..." (which is likely not true).
