### ISSUE TITLE
Rename Article 4 (from "Power Shift" to something else)

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#367]
The current name of Article 4 ("Power Shift") risks detracting from the major Power Shift involved even in just adopting Article 1 and management-hierarchy "stubs" for the rest.  I'd hate for anyone to think the only "power shift" is in Article 4, or even that the main/primary one is - I think the biggest and most impactful power shift is in going from a personally-held power structure to a written/constitutional one.  In addition, every other article has a more concrete name, but Article 4's is currently quite abstract.  So, should we rename Article 4?  If so, to what?  Thoughts?

**Comment by bernardmariechiquet** [comment]
As far as I am concerned, I would hate it to be said of a company that just adopting Article 1 and management-hierarchy "stubs" for the rest, that a form of powershift has been done. In reality, such organization just specified a structural cool tool, the role/circle, to define and assign responsibilities to others. But no power has been explicitly transferred from the power holders. We are still in a hierarchy. There is no explicit empowerment, and therefore no power shift. At best it is a general policy that explains how to delegate responsibilities, but in no case is it a transfer of power.
This being said, I propose to rename article 4 by **Empowerment** or **Explicit Empowerment**, which seems to me to really define the content of this article.

**Comment by chrcowan** [comment]
I'll withhold any commentary on BMC's point above, and just say I think there's an obvious candidate which would be, "Authority of Role-Fillers." Reasons:
- It's already the title used in the first sub-section of Article 4, which suggests something
- Thematically, it applies to everything in that section. 
- It aligns with Article 2's title, "Duties to Other Role-Fillers" 

If you went this way, then I don't know what you call section 4.1, but here are some ideas: 
- Standard Authority
- Golden Rule
- Reasonable Judgment

Alternatively, you don't rename it all, and instead move it up and take out the intro part of Article 4 that deals with ratification. I'm not sure what to do with it yet, but it seems weird to have it placed there. In addition, 4.3 Navigating Legacy Power seems very closely aligned with that intro paragraph, but they are currently separated by everything else in that section that deals with the authorities of role-fillers. 

So, then I go to the question of what to do with those two bits...and well, I don't know exactly because they clearly represent a second ratification threshold (the first being in the Preamble), which would explain why it feels awkward inside of Article 4. 

And that brings me to a tension I've been feeling about how these two thresholds are operationalized (I'll just mention it now, but maybe better as a separate thread). And it's that these two thresholds are too thinly sliced, conceptually-speaking, to have enough practical relevance. Or at least it currently seems that way to me. 

For example, Article 1 defines a Domain as something a Role may _exclusively_ control and regulate..." but it isn't until Article 4 that we get rules which restrict others from impacting someone else's Domain. The same with Policies. Now, I can do some interpretive tricks to maybe make intelligent sense of that, but it's still hard to know how I might coach someone in an organization that's only using Article 1 about what having a Domain really means. 

Actually, no, it's worse than that. Because, if the document has nuances like this, then they color the entire document. And I would imagine that a typical user can't feel confident that their own reasonable interpretation is accurate if the definition of a Domain is essentially split across two sections and two very different thresholds.

In trying to respond to OP's question, I realized that this weirdness is also evident when comparing the Preamble to the ceding power parts in Article 4. That is, the Preamble states that the "Ratifiers" must "align" to the "rules and processes defined herein" as the "formal authority structure." But then in Article 4 it says, the "Ratifiers," must "cede their power," "into the rules and processes defined herein." So, either these are duplicative and a solution may be to eliminate one of them (which would be a BIG change), or, these are actually different in which case more needs to be done to clearly explain how they are different from each other. So, maybe something in the Preamble that explicitly states that the Ratifiers retain legacy power. I don't know. Sorry to hijack the thread, but it seemed relevant to the original question.

**Comment by bernardmariechiquet** [comment]
@chrcowan interesting perspectives thanks.
I would invite you to join https://github.com/holacracyone/Holacracy-Constitution/issues/370

**Comment by MichaelDeAngelo** [comment]
I like a heading that has "Authority" in it in some way but I'm not sure of the exact wording. When looking at Article 4 I see it as making it explicit what authorities Role fillers have, constraints, and origin. So, my mind leads to something like "Distributed Authority", "Authority of Role Fillers" (as Chris suggested), or "Scope of Authority"

**Comment by oliviercp** [comment]
I like "Authority of Role Fillers" as well, it's simple and direct, like the titles of other articles. I like the idea of "Scope" too because the article also deals with limits to role fillers' authority. So something like "Scope of Role Fillers' Authority" would cover the content of the article well, and I love that.

But overall, I would still settle for "Authority of Role Fillers" because it's simpler.

**Comment by benoitpointet** [comment]
"Delegation of Authority"

**Comment by denniswittrock** [comment]
If you title it "**Authority of Role Fillers**", then the very first paragraph about Ratification and _4.3 "Navigation Legacy Power"_ feel extra and don't quite fit under this new headline.
Otherwise, I like it. 

If those two sections are _not_ removed from this article, the headline needs to be broader. In that case simply "**Authority**" , "**Scope of Authority**",  "**Matters of Authority**" might be viable candidates.

**Comment by brianjrobertson** [comment]
Thanks all, this was really helpful; I'm changing to "Authority of Role Leads", and moving the parts that don't work with that title.

**Comment by brianjrobertson** [comment]
I'm intending to change this article title from "Authority of Role Leads" to "Authority Structure", so it's a bit broader (it covers more than just Role Lead authority).  If anyone thinks that's a step backwards, please speak up.
