### ISSUE TITLE
Restructure preambles, articles 1 and 4 for a clear constitutional power shift (even with only article 1 and stubs)

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#370]
@brianjrobertson I've been feeling the following tension for some time, amplified during the work I've been able to do during 5.0 workshop with you recently. I would hate to call something Holacracy with just Article 1 and management-hierarchy "stubs" for the rest, adopted
For me, this would not be any longer Holacracy, it would not even be a constitutional power neither constitutional management. 
I propose to clarify the confusion that seems to arise with the arrival of the modular version of Constitution 5.0.
As much as I find the idea of modularity interesting, it seems important to me to make sure that the integrity of what is constitutional management/power, is respected.
At the very least, Articles 1 and 4 must be kept to continue to call Holacracy a constitution. A constitution needs IMO some clear mechanisms for explicitly transferring power from power holders (and also addressing that implicit expectations hold no weight), not only giving explicit responsibilities that are already happening in the conventional management hierarchy.
See perspectives https://github.com/holacracyone/Holacracy-Constitution/issues/367#issuecomment-711132015
Moreover, I think the essence of the Holacracy brand would be diluted if just article 1 makes it Holacracy. 
Therefore, I propose to change both the structure and the order in the following way:

1- Organizational Structure (Core)
2- Power Shift (Core)
3- Tactical Meetings (Stub possible)
4- Duties to Others (Stub possible)
5- Governance (Stub possible)
6- People & Partnership (Stub possible)

**Comment by brianjrobertson** [comment]
@bernardmariechiquet I see what looks to me like a pretty substantial power shift in just Article 1 + stubs; before adopting that, a boss in the management hierarchy can tell someone what to do and expect they'll do it; after adopting that, the boss no longer has the right to expect the person will do something outside of their roles' explicit accountabilities.  That's pretty big in my view.  That also makes for a shift from a power/expectation structure of "do whatever the boss says" to "this constitution defines the rules of the game" - thus, it seems like a shift to constitutional power to me.  What am I missing, or what are you seeing differently here?

Another way to try to integrate here:  Is there a specific sentence or two somewhere in Article 4 that, if it were in the Preamble, would address your concern, even if the rest of Article 4 were left as a separable module?

**Comment by bernardmariechiquet** [comment]
> @bernardmariechiquet I see what looks to me like a pretty substantial power shift in just Article 1 + stubs; before adopting that, a boss in the management hierarchy can tell someone what to do and expect they'll do it; after adopting that, the boss no longer has the right to expect the person will do something outside of their roles' explicit accountabilities. That's pretty big in my view. That also makes for a shift from a power/expectation structure of "do whatever the boss says" to "this constitution defines the rules of the game" - thus, it seems like a shift to constitutional power to me. What am I missing, or what are you seeing differently here?

Nope, don't agree with you. A boss may still expect someone implicit expectation outside of their roles' explicit accountabilities, nothing prevents it.

> 
> Another way to try to integrate here: Is there a specific sentence or two somewhere in Article 4 that, if it were in the Preamble, would address your concern, even if the rest of Article 4 were left as a separable module?

Wow, one or two specific sentences would not be enough IMO.  I don't see how we could integrate this way. I'll try to think more about it, but with no guaranty.

**Comment by rebeccabrover** [comment]
@brianjrobertson @bernardmariechiquet
I agree with Brian that the first big shift is in article one whether or not it is super highlighted.
I think implicit expectations are there for a long time both no matter which articles are adopted and if governance is a stub, the current power-holder still has the right to change accountabilities at any time. What I think is particularly useful about that is even without a process, the action has to happen if the "boss" wants to expect something new. They can't just order action, which is a huge step.

**Comment by bernardmariechiquet** [comment]
@rebeccabrover  I agree with what you write but something is missing to make it a shift. I still find the bar too low to call it a power shift, or a constitution. It's probably a question of personal bias, or iGi bias, or french culture, or both of them. There is a long history in France about the "constitution".
@brianjrobertson If you continue along this path, it seems to me that the following sentence should be added to Article 1 of Article 4: 
**"No implicit expectations or constraints carry any weight or authority. Nor do any dictates issued under the Organization's old power structure before it adopted this Constitution."**
This would strengthen and make this article's mechanism stronger and clearer from a power shift perspective, and only then, only then, can we start talking about power shift.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I also do think the first sentences of art. 4 should be placed in the preambule:
**"By adopting this Constitution, the Ratifiers cede their power to govern and run the Organization into the rules and processes herein, except for any powers that the Ratifiers lack the authority to delegate. As a Partner, you may rely upon the authorities granted by this Constitution to the full extent the Ratifiers held such authorities before adopting it."**
IMO, this would make such document a Constitution.

**Comment by bernardmariechiquet** [comment]
I would also place https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#43-navigating-legacy-power up front into the preambules. Except the last sentence which would be into article 1 as mentionned above:
"No implicit expectations or constraints carry any weight or authority. Nor do any dictates issued under the Organization's old power structure before it adopted this Constitution."

**Comment by bernardmariechiquet** [comment]
So that we now may rename article 4 something like "Authority of Role Leads" or "Role Leads Empowerment" which would be an answer to https://github.com/holacracyone/Holacracy-Constitution/issues/367
IMO article 4 would become far much cohesive.

**Comment by chrcowan** [comment]
@brianjrobertson you said 

>  I see what looks to me like a pretty substantial power shift in just Article 1 + stubs; before adopting that, a boss in the management hierarchy can tell someone what to do and expect they'll do it; after adopting that, the boss no longer has the right to expect the person will do something outside of their roles' explicit accountabilities.

But that doesn't fit with my interpretation of reading Article 1 in the absence of Article 4. I don't see anything in Article 1 that would _clearly and explicitly_ limit a "manager" from expecting someone to do something outside of a role. If that is the intention then I think it needs to be much more clear. 

And if that IS the intention (and is made more clear), well, then it seems like it would get really really really close to saying what is already stated in Article 4. Meaning, as I try to get my head around this, I see a few possibilities:  

1) The intention is for Article 1 to be definitional, without any powershift per se. This is actually easier to get my head around (bracketing the question of whether this is a good idea or not for the moment), but if this is true, then I could make several concrete suggestions about how to make Article 1 a lot less powershifty. Of course it would change (again) what is means to be "practicing Holacracy," to be more aligned with the Article 4 threshold, which means branding-wise we'd need another term to describe the definitional/structural adoption. I don't think this is what you're going for.

2) The intention is for Article 1 to be a powershift, but not quite as much of a powershift as Article 4. If this is true, then the difference between them needs to be much more clear. What can or can't I do that's different? And why is that difference important? If they aren't different enough, then that's a good argument to join them together somehow (e.g. BMC's suggestion of making them the first two articles and calling them both "Core" is one way to do that, but no opinion on that specific idea at the moment). Currently, as an example, the definition of a domain seems very confusingly split across both Articles (as I mentioned in the other thread), so that's a place where I'm not seeing a meaningful difference. 

3) The intention is for Article 1 to have some sneaky powershift stuff in there without making it overt, which leaves Article 4 to carry the main portion of the explicit powershift. I can see why doing it this way could make sense because it would allow much more room for interpretation, and the actual practice of the rules like which elements are emphasized, is more organic to each organization (usually requires some good coaching to then make sense of it). It could kind of ease them into it. But if this is true, then this is basically the approach that we've used previously. Meaning, the value of the modularity goes way down, and may even make things more confusing compared to just saying, essentially, "Ratify all the rules, then do your best to live up to them." 

Anyways, I've written a lot on this, but maybe for the moment the most important question for me is (to circle back to the first point), how do you justify the interpretation of Article 1 as saying, "_the boss no longer has the right to expect the person will do something outside of their roles' explicit accountabilities_"? because maybe I'm just missing something.

**Comment by MichaelDeAngelo** [comment]
In part I think this is about how strongly or dogmatic we (community, coaches, constitution steward, whomever) want to hold "Holacracy" and what is considered an organization "practicing Holacracy". I think modular adoption enables a balance between accessibility and dogma for organizations. For some organizations starting with just adopting Article 1 would be an authority game changer and all that can be reasonably achievable on their Holacracy journey before they adopt the next article. Requiring Article 4 as part of the core doesn't take advantage of the accessibility modular adoption can create for organizations, in my opinion. Nor does it create the space for the organization to start their Holacracy journey while working on the internal change management challenges in preparation for other article adoption. For many organizations, I think Article 4 will be one of the last to adopt especially if they are coming from a place of a long standing traditional structure. I think it is more powerful and sincere for organizations to make explicit that Article 4 "will come later" rather than what we have today which is adopting the powershift from the beginning but not really following all the rules because they are not ready and just doing their best. And, if they want to adopt powershift but not follow it, they still can; just adopt 1 and 4.

**Comment by bernardmariechiquet** [comment]
I do not think that the comments that seek to incorporate Article 4 are dogmatic. As far as I am concerned, they are based on a hundred or so companies that have been accompanied on their journey to adopt Holacracy in recent years. No dogmatism here, just reality.
On the other hand, I would not say the same of the modular approach starting from article 1. It seems to me to be very mental and therefore dogmatic, I am always embarrassed on the subject, not having a concrete case of a company that would show me that they had indeed adopted Article 1 for a while to prepare themselves for je ne sais quoi and that they would then have adopted Article 4.
The setting in motion of the change passes by experience through the adoption of a constitution that contains a true powershift. This is what my research has been showing for 12 years now. Show us concrete cases.

**Comment by chrcowan** [comment]
I resonate with Bernard Marie's point above, though my version of it is something like...I can only imagine a company adopting only Article 1 if they ALSO are _intending_ on adopting more or all of it. I used to think that the Art-1-ONLY group might include companies that aren't really sold on Holacracy yet, but they want to move in the direction of self-organization. I'll call this a "wait-and-see" approach. But I no longer believe this is really the group that will be drawn to Art-1-ONLY.

It seems to me (or my guess is) that the actual use-case is for companies that actually want/intend to do all of it (on some level), BUT for some reason it's too much, not practical, etc. at the moment, so they are happy that a modular approach can give them a clearer and friendlier roadmap for adoption. Let's call this the, "convinced-but-careful" approach. This group will be a lot more tolerant if there are slight problems with how the articles are divided (e.g. the domain split I mentioned before, or the issue of the second ratification threshold), as they are planning on resolving those issues at some point anyway. 

But if that's true, then the narrative about the modularity of the constitution shouldn't be told in terms of the "wait-and-see" approach; i.e. "You don't have to do all of it, you can just start with a piece and evolve from there." Instead, it would be more accurate to tell the story like this, "All of the rules are important because they work together as a cohesive system, but if for some reason that's too much to take on, the constitution has done a pretty good job of breaking the rules up so that you could focus on one article at a time."  

So, some of the confusion I think I've had is because I heard the "wait-and-see" modularity story, which doesn't fully line up with what I'm reading in the v.5 constitution. Meaning, resolving some of these issues might have more to do with consistently framing and explaining the intent of the modularity in terms of "convinced-but-careful," rather than trying to solve the issue by changing the constitution itself.

**Comment by bernardmariechiquet** [comment]
> 
>  "All of the rules are important because they work together as a cohesive system, but if for some reason that's too much to take on, the constitution has done a pretty good job of breaking the rules up so that you could focus on one article at a time."
> 
@chrcowan I resonate with this. And I'll add... in bold below.
"All of the rules are important because they work together as a cohesive system, but if for some reason that's too much to take on, the constitution has done a pretty good job of breaking the rules up so that you could focus on one article at a time, **or rather, it allows you to temporarily ignore an article when the bar is too high."**

**Comment by brianjrobertson** [comment]
Thanks all, this kind of rich dialog was exactly what I was hoping for, and exactly what I needed to find an integration of the various perspectives shared here.  I think I've found that now - I'll submit momentarily, and I'd really love any feedback on the change.
