### ISSUE TITLE
Require Working Agreements (6.2) to be "Written"

### ISSUE THREAD

**Issue by chrcowan** [holacracyone/Holacracy-Constitution#373]
@brianjrobertson I'm not 100% confident in this, but I think it would make sense to require that 6.2 Working Agreements are, "written" (which is the same word used when requiring the tracking of projects and next actions). Alternatively, maybe just saying they need to be, "explicit" would do it.

In thinking through how I'm going to coach others on using Working Agreements, I can envision a lot of confusion over how they differ from governance. Moreover, my concern is that someone could say that an implicit behavioral agreement was made even if it wasn't. 

And while it seems a little strange to me to require them to be, "written" my current thinking is that it's probably a good idea all the time anyway to require them to be written. Given the behavioral requirement, and the conscious agreement needed, these aren't the kinds of statement people should agree to or craft impulsively. 

This is why I think I prefer this to just requiring them to be, "explicit," (i.e. just spoken) which could make sense in some cases, but leaves people vulnerable to think the agreement was explicit when it really wasn't (i.e. When people act on implicit assumptions or agreements, they don't tend to think of them as implicit). With that said, if for some reason requiring them to be, "written," is too rigid, then at least requiring them to be _explicit_ would give me grounds to provide the kind of coaching I need. 

So, my suggestion is to add one word to the first sentence of the last paragraph in 6.2:

• As a Partner, you have a duty to align your behavior with any **written** Working Agreements you have made.
OR
• As a Partner, you have a duty to align your behavior with any **explicit** Working Agreements you have made. 

Adding this near the end of the section would have the effect of not making it seem too rigid.

**Comment by brianjrobertson** [comment]
@chrcowan I have no tension with adding "explicit" as a requirement.  I originally did have "written" in there, but I actually removed it, with mixed emotions.  On the one hand, I totally resonate with everything you've written; on the other, it seems to better match a natural way of working to make simple verbal behavioral agreements and expect to align with them, and I'm not sure forcing these to be written is a good thing.  For example, I think I'm super careful and clean with my agreements, and yet, in my relationship, I still occasionally make small verbal behavioral commitments I expect to align with, and it would feel pretty weird to say "we either need to write this down so you can really expect it, or you really can't hold me to it".  These are often really small things, like "I'll leave most of my dishes in the sink instead of on the counter".

That said, as weird as that would feel to force that to be written down or not really counted upon, perhaps that would actually be best - I can see the argument for that.  Your thoughts?  I'm especially curious to hear what you think in a personal relationship context, because I think in this case that will give us the best clues as to what makes sense here in the organizational relational context.

**Comment by chrcowan** [comment]
@brianjrobertson My thoughts are that it does make sense to actually _force_ them to be written down. I thought of an example I have with my wife in which we both agreed that when asked the question, "How was your day?" the other can't just say "It was fine," or "Good," or any other token response to dismiss the question. I won't go into the details of that specific rule, but I thought it would be weird to say that it didn't count because we didn't write it down, when in fact it's one that's been working great for years. But then I realized two things: 

- There is still nothing preventing anyone from making, agreeing, and fulfilling non-written agreements, it's just that it's technically aren't enforceable unless written down, which means that experienced practitioners could consciously and safely ignore the written requirement up front if they so choose. 

- Even if it is a little weird, so what!? It's not THAT weird to take a few moments to write it down. It would take the same effort as sending someone a text message. 

- Requiring them to be written is a better conceptual fit with tracking projects and next actions outside your head, and having a shared constitution and governance records. Without that requirement it's kind of an outlier and therefore could easily be misinterpreted as they _shouldn't_ be written down.

**Comment by gvandegrift** [comment]
Totally agree on the notion of writing them down.  Clarity just makes life easier.  FWIW, as a family, we have pretty regularly written down agreements.  For example, we had a bedtime activity agreement that all the kids signed.  The agreement was a godsend when weird disruptions would cause the kids to think that bedtime didn't apply (getting home late from the grandparents or a sporting event, for example).  Just point to the agreement.

The kids are all grown now, but we still keep that agreement on the refrigerator for fun.

**Comment by bernardmariechiquet** [comment]
I'm a bit annoyed when I see that the examples cited concern couple or family relationships. I don't know where we're going, and it bothers me that we're leaving the organizational sphere. I would like the evolution of the constitution to be based on concrete cases and in the field of companies.

**Comment by matthewgilliland** [comment]
I think it might be natural that we tend to use people-space examples here rather than org-space examples; all of the org-space examples I can think of off of the top of my head would require more context for others to parse, while I think everyone grasps the family-based examples. And many or most of the WAs I'm involved in are people-space, just within the context of the org, e.g. "I agree to prioritize attending a "clearing conversation" upon request from another partner."

+1 to forcing them to be written; one thing I'm already a bit worried about with misuse of WAs is that some countries' labor laws might consider them a form of job expectation, and I can imagine ways in which that could cause trouble if it happened, depending on the circumstances. Forcing them to be written down would help with accountability and transparency of that accountability.

**Comment by Aliocha-Iordanoff** [comment]
Here's an example I'm thinking of: when a new partner joins the company. He integrates the team and we often realize in these moments the dozens of small agreements that exist explicitly or informally. And these are relational agreements.

As these agreements only concern a partner from the moment he subscribes to them. One might consider that the word "explicit" would be right in the constitution.

In my example, if I tell the new teamate that I would like him to do his washing up like the others who have lunch there, I made it explicit verbally. And at the same time, to support a culture of the explicit in the organization, I realize that it would be really interesting to write these things there, because in reality, welcoming a new partner makes me realize that we also have implicit relational agreements that exist between us.

**Comment by brianjrobertson** [comment]
Thanks all, after considering all these comments further, I'm going to add the "written" constraint.
