### ISSUE TITLE
Clarify that Anchor Circle is also a role?

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#374]
In https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#14-circles 
The strict definition of a circle is
> A “Circle” is a container for organizing Roles and Policies around a common Purpose.

With later
> Every Role is also a Circle internally.

I interprete this as a Circle has no domain nor accountabilities, it's the containing role that does.

Yet regarding anchor circle:
> The broadest Circle that holds the Purpose of the whole Organization is its “Anchor Circle”. 
> The Anchor Circle holds all authorities and Domains that the Organization itself controls, and has no Super-Circle. 
> The Anchor Circle may change its own Purpose or clarify its own Accountabilities via a Policy. 

Those seem remnants of the v4 concept "a circle is a role" that contradict the v5 "a circle is an inner organisation of a role"

**Comment by brianjrobertson** [comment]
Yeah, I had this thought too, but I'm not sure if fixing it is worth the extra complexity it would add.  As-is, it seems likely readers will infer all the correct treatment.  I'm not sure it'd actually be as clear though if we add something to clarify that the Anchor Circle is really also a role that represents the whole org, and that it's the role that has Accountabilities.  In other words, while this clarification makes the document more accurate and consistent, I'm not sure it's a practical benefit given the added complexity.  Unless someone can find a way to say it that's really simple and doesn't risk confusion - which would be ideal, but I'm not sure I have a good idea on how to do that.  Thoughts?

**Comment by chrcowan** [comment]
Hmm....@benoitpointet, do you have a recommendation for how it could be clearer?

**Comment by benoitpointet** [comment]
Quite simply, beginning of 1.4.3:
> The broadest **Role /** Circle that holds …

**Comment by brianjrobertson** [comment]
Hmm, I like the simplicity of that, but I really don't like using the slash in there - that seems potentially confusing.  Although perhaps less so overall than the current wording.  Anyone else have opinions about that potential solution?

**Comment by bernardmariechiquet** [comment]
**1.4.3 Anchor Circle** may become **1.4.3. Anchor Role**:
"The broadest Role that holds the Purpose of the whole organization is the "Anchor Role". The Anchor Role holds all authorities and Domains that the Organization itself controls, and its inner Circle has no Super-Circle. The Anchor Role may change its own Purpose or clarify its own Accountabilities via a Policy. The Anchor Role has no Role Leads, unless a Policy of the Role says otherwise."

This requires to change also **1.5 Circle Leads**
"Anyone serving as a Role Lead for a Role also automatically fills a “Circle Lead Role” within that Role's internal Circle, and is thus a “Circle Lead” while acting in that capacity. The Circle Lead Role has the definition given in Appendix A."

**Comment by benoitpointet** [comment]
That full switch to "anchor role" as proposed by @bernardmariechiquet does not seem to hurt, on the contrary: it can better fit organizations that have no "board structure" but a single owner, …

**Comment by brianjrobertson** [comment]
While I appreciate this one in theory for technical accuracy, I'm skeptical whether this really matters in practice at all, and the changes suggested here seem likely to reduce clarity in practice for novices (and maybe more experienced folks too), even if they are technically more accurate.  So, I'm going to drop this one, although please feel free to offer more arguments or suggestions and I'll consider further.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I think exactly the opposite. The notion of the circle is not obvious to beginners, one more concept to explain. As a result, the simple explanation that is often given is to say that it is a team in a way that mentally differentiates it from the concept of role, which creates more confusion than it helps. I think it's urgent to call a spade a spade. The holarchic structure is fractal, and we've been beating around the bush for too long. It's really time to take the plunge just to make it easier for newcomers to understand from the beginning. The more experienced folks you mention who you think might have difficulties would only be in trouble for that very reason. It's time to deconstruct in order to construct at another and simpler level.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet I appreciate our shared goals here, though I strongly disagree; I believe we need different terms for the different perspectives, and I believe that will keep communication far simpler and Holacracy much easier to learn and practice.  I think merging the terms makes clear communication a nightmare, and makes the rules far more complex to read and understand.  That said, if you want to try coaching an implementation with the terms merged (using a derivative version of the constitution with role & circle merged), I'd love to hear about your experience; my hypothesis is that it will be a disaster, but I'm open to being wrong and re-examining my conclusions if you try it and tell me otherwise.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Difficult to do this test without having the software aligned!
