### ISSUE TITLE
"reasonable time" clause for async gov?

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#377]
In the core desc of the gov process https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#53-governance-process, which if I understand correctly, is the new definition of async gov, there's no notion of "reasonable time" to raise objections, while to clause is used in the "spending" and "impacting domains" sections.

I would see opportune to add the resonable time construct in 5.3.

**Comment by brianjrobertson** [comment]
@benoitpointet That's intentional; absent a policy otherwise, I think it's important that the default governance threshold leaves almost no room for doubt about the validity of a proposal passing, and an ambiguous "reasonable time" clause could leave a lot of room for doubt.  Note there is a clause in that section though that reads "A Circle may adopt a Policy to define a time limit for raising Objections, after which anyone who has not responded is assumed to have no Objections."  So it's possible, just requires a policy.

I'm closing this issue given that, but please do comment if you think it's worth further consideration and I'll open it back up for more community comments.
