### ISSUE TITLE
Make Circle Lead a designation, not a role?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#382]
In the current dev version, the Circle Lead role only has one real field: a domain (role assignments).  Its purpose and accountabilities are just inherited from the Circle, and not unique.  This brings up an interesting cascade of possibility: That single domain on the role could easily be removed, and replaced with rules about role assignment that mimic the same effect (kinda like how resources and strategies aren't domains on the Circle Lead role, yet per the rules the Circle Lead effectively controls them much like a domain).  If that were done, the Circle Lead role would no longer have any fields on it, which brings up the next possibility:  We could remove the Circle Lead role entirely, and make "Circle Lead" just a designation to refer to whoever leads the Role in the broader circle (e.g. "whoever serves as Role Lead for a Role also automatically serves as 'Circle Lead' within that Role's inner Circle).  That would remove the strange duplication between that Role assignment and the Circle Lead role assignment within the Circle; currently, these two role assignments are really the same role, but actually two roles at the same time - which seems awfully confusing to me (at least from the perspective of a novice practitioner trying to understand this paradigm).  If we made the two changes above, it could actually be just one role, with "Circle Lead" being just another way to refer to that one role.  Any reactions?

**Comment by bernardmariechiquet** [comment]
Excellent. This addresses the tension that I have had for over 2 years. Weird to use two different words for the same concept, same construct.
And I was really embarrassed that the role of Circle Lead was still defined in Appendix A with only the domain "Role assignments". It felt weird too.
Now you have to pull the thread from the ball. The next step is to remove the notion of circle, sub-circle and super-circle. This would be great because this notion of circle is also redundant and also annoys novices. We could then talk about roles, sub-roles and super roles quite simply.
I know that some experienced practitioners may be anxious as they sense they need to be able to differentiate the two perspectives by using two different words. It seems to help them. I wonder if this is not a defect of those who are familiar with the constitution 4.1. And that if we forget the 4.1, which I have been working on for more than two years, I sense that double word, role and circle, creates more confusion than it brings value.

**Comment by denniswittrock** [comment]
An interesting move that could simplify things further. I like it. The Circle Lead role construct would vanish from the constitution entirely. I wonder if and how the difference would be felt in practice. Basically, we _already_ tell people that in the super-circle they are just like a regular role, and in the sub-circle, they are the "Lead Link" (Circle Lead). So this change would confirm that it is **one and the same role**, only referred to differently in different contexts or from different perspectives. Designations are a function of perspectives taken with regard to a single role. 

The move that @bernardmariechiquet proposes would be a logical continuation in that direction, yet I am not sure it would be well equally well received and comprehended. Eliminating the concept of "circles" and replacing it with the notion of "sub-role" and "super-role" would drive home the point of the identity of constructs of "role" vs "circle", yet I suspect that most people may think less abstractly in terms of a relative, perspectival role-awareness, but rather in terms of groups of humans ("KISS": keep it simple, stupid! ). 

Heck, most people still think a group consists of _people_ (people being the "parts" of the group, while it is rather their _interactions_ which are the "parts" of a group - people are "partners, not parts" of a group, their communications are). Eliminating the concept of a "circle" in favor of an expanded understanding of "role" might go a bit too far and leave them disoriented. But maybe I am wrong. In that case, it would be more straightforward.

**Comment by klaas1979** [comment]
I like the idea. On the positive side beginning circles (I use this word to get the relation more clear), have a harder time defaulting a lot of projects to the Circle Lead Role because it is missing. Instead the work would became Individual Initiative or would it be added to the Role Lead (within the super circle)?

I do not get the construct clear completly, I see two sides of the same coin:
- It feels way better, because it is now just a role and not like the two roles before. And I guess it could help to flesh out needed meta work (i.e. stuff from the Lead Link v4.1 role) as separate roles. In the right mindset it could become a powershift accelerator.
- The worst case would be that a Circle Lead is then interpreted as something standing above the other roles, having no roles within the circle but just the meta role in the super circle. This would prevent the powershift by the block, that the role is "out of reach".

Still I really like it and have the inner feeling that it would help in the long run and evolution of holacracy.

@bernardmariechiquet idea would make it even better. But I needed the word "circle" to make clear what I reference, so I guess it could be needed for ease of discussions.

**Comment by rebeccabrover** [comment]
@brianjrobertson I'm not quite sure how I feel about this yet, but my first gut hit is the ambiguity created (along with the additional freedom) is more harmful than helpful when trying to adopt this and sets the bar higher for understanding role assignment at the outset, either through a new untested process created for this version or through some sort of app the org would need to create when adopting (if adopting as a whole).

**Comment by leword** [comment]
I like it.  In the software implementation in GlassFrog currently we have to special-case role assignment so that it also assigns a CL role within the subcircle.  It always seems like a good sign when an architectural change removes need for a special case in implementation. 

This also makes me wonder a bit about Circle Rep- since currently we have to the same double-role/double-assignment thing going on there.  However, a fix for that might be to treat Circle Rep like a special case of the general Role Linking concept- not sure.

Without thinking about it too deeply, I also like the idea of removing the 'circle' concept and just having roles.  But that is a much bigger change of course- it would probably take years to bring the GlassFrog codebase fully up to date with that understanding.  Although we've already moved the UI a long way in that direction.

**Comment by chrcowan** [comment]
Not sure how I feel about it. I can imagine some benefits, though I can also imagine that it could create other confusions. Still sorting through my thinking on it. 

One thought that is clear though is that it's usually helpful to have multiple words to convey different _perspectives_ on a thing (e.g.1st person, 2nd person, 3rd person). This might be why I like having the role/circle distinction.

**Comment by oliviercp** [comment]
Regarding removing the CL role: it's true that it could be "empty" if the domain is removed, but v5 also allows for adding to the CL (article 1.5.3) and it's unclear to me how that would be captured if there was no CL role. As another argument against, I'm afraid it will be confusing to people. There is a designation of Circle Lead but no role to see it. In my experience, it's already an issue with the current LL definition that several of its authorities are not in governance but in the constitution itself; many people don't check the constitution but do look at the governance. Removing the CL role would reinforce this separation IMO.

**Comment by bernardmariechiquet** [comment]
I propose to push the idea of doing away with the concept of Circle and Circle Lead, in favor of a single concept, that of Role and Role Lead.

All functions and authorities of Circle Lead, even those defined in appendix A in version 4.1 of the constitution, in reality, apply to all roles, even when they have not (yet) sub-roles. Both those described in the constitution and those described in Appendix A. They reflect the "managerial" functions of any role, whether it is "already a circle with sub-roles" or "only a role with no sub-roles".

If one wishes to merge the concepts of role and circle, it would suffice to make explicit these managerial functions common to all roles somewhere in the constitution. I would suggest to add that in article 5. And to allow ratifiers to add more of them so as to cover the functionality (which is required by tension described in https://github.com/holacracyone/Holacracy-Constitution/issues/330 ), and that would probably address the issue https://github.com/holacracyone/Holacracy-Constitution/issues/390 with article 1.5.3.

This would also argue in favor of bringing Article 5 closer to Article 1. https://github.com/holacracyone/Holacracy-Constitution/issues/358

I am aware that this is a complex change and it seems to me that it makes the constitution much simpler once this change is applied.

**Comment by SamirSaidani** [comment]
Concerning the Circle Lead designation question, in my understanding, I would say that a Role is encapsulating a unique inner circle, composed by default with one Role, the Lead Role (and not the Role Lead). 

There is for me a problem with the way Role Lead is defined : "Whoever fills a Role becomes its "Role Lead"". It conveys the idea that someone becomes, i.e is the Role Lead. I prefer : "Whoever fills a Role is energizing its Lead Role". Playing the Lead Role instead of being the Role Lead is more consistent with the Role/Person separation principle. For me, Lead is a Role. If not, I'm wondering what kind of organizational construct it is. Once you accept that, (inner) Circle Lead Role is naturally another way to refer to the Lead Role of the inner Role Circle.

For the problem of Role vs Circle, I see them as two different concepts : Circle and Role are two sides of the same concept, a Holon, exactly like Head and Tail are two sides of the Coin concept. The sides exist by themselves. Getting rid of one of them is like calling a coin "tail". (or "head", just flip the coin to decide).

Unifying both concepts requires the introduction of a third concept, the Holon : the Role becomes the name of the outer envelop of a Holon, and the Circle is its inner envelop. The Holon upstream, and its downstream. The proposal to get rid of the Circle concept and keep the Role concept is actually the proposal to get rid of both Circle and Role concept, and use only the Holon concept (incidentally called by the proposal "Role").

Although theoretically correct, the idea to only use the Holon ("Role") concept would probably require to overload the communication with details not needed with Role/Circle distinction, and would cause much more cognitive effort to grasp it. For instance, let's compare : "which Roles are your Role member of ?" or "which Roles are members of your Role ?" versus the very same questions "which Circles are your Role member of ?" and "which Roles are members of your Circle ?". As far as I'm concerned, it's far more easy to figure out the Circle/Role questions whereas I'm feeling a kind of cognitive overlad with the Holon version since it's melting both the container and the content. All in all, although the theory seems attractive to me, I don't feel this approach usable in practice.

**Comment by brianjrobertson** [comment]
@ocompagne Hmm, I think this concern of yours could actually be more of an argument for doing it:

> There is a designation of Circle Lead but no role to see it

That's equally true for Role Lead already in v5 beta; there is a designation, but no role.  It seems potentially even more confusing to have those two use different treatments.  If Role Lead isn't a role, Circle Lead probably shouldn't be either.  And it'd be super weird to try to force Role Lead to be a role (@samir-s, I disagree with you here - I don't think it's very useful to think of that as a role; it's a distinction that refers to the person who fills a role, while they're acting in the capacity of the role; not a role itself).

Olivier, to your other point: 

> v5 also allows for adding to the CL (article 1.5.3) and it's unclear to me how that would be captured if there was no CL role.

Yeah, that is an issue.  But I think we can find another way to meet the need behind that; perhaps a way to add expectations somehow to all Role Leads and/or all Circle Leads.  I'll think about that further.

@bernardmariechiquet, I admire and respect your wonderfully tenacious advocacy for your perspective on dropping all language around circles and circle leads, and I really get the conceptual elegance of that thinking... but I still don't think it's a good idea practically.  The main reason for me is the one Samir points out, about how difficult and confusing the languaging is if we don't have separate words to refer to the separate perspectives.

**Comment by bernardmariechiquet** [comment]
@samir-s You're right, a role is a holon, it always has been!
And it takes people a long time to integrate this notion, just like the holarchy. One of the reasons is that human beings make little use of this structure, even though it represents the structure of all living beings. Because he has rarely used it. Pyramidal thinking was omnipresent.
And at the same time, it's quite easy to explain to someone what a holarchy is, there is no lack of metaphors, the human body, etc.
What, second reason, comes to complicate, to hinder this understanding that the Holacracy practitioner needs, is this double concept, role and circle, which comes to close this possibility and prevent this learning that could be natural from the very beginning.
This raises the question of pedagogy. Should it start from concepts we already know, such as a team becomes a circle? A role is the description of the activities of the role? And in this case no mental shift, the status quo is de rigueur. If on top of that you add the modular approach as I heard sometimes in the eco-system, then the probability of the necessary mental shift is strongly compromised.
Or create a mental disruption right from the start, which simplifies the journey a lot. People really feel like they're setting off on something new, and, again, the explanations can be simple.
This is also the case with the concepts of purpose, tension, and accountability.
At iGi institute, we do for everyone very concrete micro-training sessions before the encoding of roles, on the new concepts of roles, raison d'être, accountability, tension. We've been doing this for several years now and we realize that the journey is much easier for everyone.
This is why we think, based on our 11+ years experience, that mental disruption at the beginning is a key factor of success in adoption.
There is nothing brutal or violent about it for the people. They are taught a new subject from the very beginning instead of having to endure the previous mental models in addition. And we accompany them quietly at their own pace, or even in a modular way. Disruption is required, it cannot be modular.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson  Our comments have crossed. I invite you to look at my last comment. Especially regarding pedagogy.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet My concern isn't about the mental disruption of it at the beginning - as you say, I think that can be incredibly useful.  My concern is with confusion even among pro practitioners; even I would still want different language constructs to refer to the different perspectives more easily/elegantly, and that's definitely not because I'm stuck in the old paradigm and struggling to think in a holarchic mental model.  It's because the additional perspective-based language is just really, really useful, and communicating about organizational stuff without it would be much more difficult and require more extra words around whatever I'm trying to say just to clarify meaning and remove ambiguities.

**Comment by SamirSaidani** [comment]
A proposal could be the following. Role-filler, Role Lead and Circle Lead are all three the same concept, a designation for Lead. If a inner Role of the Circle's Lead needs to add an expectation to the Lead, the inner Role adds an expectation to its inner Circle. These expectations are private to the inner Circle, exactly like the inner Role : they are invisible from the broader Circle perspective. The inner Circle inherits automatically from the expectations of its Role, but the other way around is not true. By the constitution, the Lead is accountable for its Role accountabilities (the interface with the broader circle) *and* the inner Circle accountabilities. It gives us a way to add expectations to the Lead without the role construct. I would get rid of the recursive accountability hack. It's up to the Lead to build a new Role from its inner Circle expectations, or not, or to object, as usual. As a side note, this move is impossible if Role = Circle, we need two separate nested membranes to implement this solution.

**Comment by bernardmariechiquet** [comment]
> It's because the additional perspective-based language is just really, really useful, and communicating about organizational stuff without it would be much more difficult and require more extra words around whatever I'm trying to say just to clarify meaning and remove ambiguities.

So @brianjrobertson we will both agree that we disagree on this.
This probably means that we are not yet mature enough to be able to integrate the two polarities.

**Comment by SamirSaidani** [comment]
@bernardmariechiquet  In my understanding, even if everything was a "Role", i.e a Holon, to get the full power of the concept, you will need to reference at some point the inner enveloppe of the holon and its outer enveloppe, (respectively called here "cercle" and "role") so you will be back to square one. It's like proposing to talk only about coin, without never bothering talking about tail and head: that would definitely put a limitation to such a framework. See for instance my proposal where I'm explicitly using the different sides in a different way: in the "Role is all" framework, in my proposal, you will logically have to talk at some point about the "Role inner side" and the "Role outer side", or something like that, i.e find a name for the inner side and the outer side of the Role. So I'm saying that Role and Circle are much more than just a language convenience, they are a part of the holon structure just like sides are part of the coin structure. In holacracy current framework, I don't see the necessity to overload holacracy with the holon concept. Following the Occam's Razor principle, referencing holon sides (i.e "role" and "circle") are enough.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet What you say there resonates with me; I look forward to discussing further when opportunity presents, and hopefully finding an integration at some point.

**Comment by bernardmariechiquet** [comment]
> In my understanding, even if everything was a "Role", i.e a Holon, to get the full power of the concept, you will need to reference at some point the inner enveloppe of the holon and its outer enveloppe

@samir-s I know this argument. So many people use it. I feel it's a bit conventional and worn out.
I can use the term atom or cell without having two different names for the inside and the envelope. That's why I don't agree with this argument.

On the other hand the term circle is so connoted, as being a group of people is counterproductive, and creates misunderstandings and false beliefs.  A circle is also a two-dimensional figure, a role is 3-D.

On the other hand, when I talk about holon, it is clear that I am taking advantage at every moment of a new mental model which is the one of the holon definition. 
"A holon (Greek: ὅλον, holon neuter form of ὅλος, holos "whole") is something that is simultaneously a whole and a part. "
Removing Circle, defining Role as being a holon would be IMO a better way to get the full power of the concept.

I observe that this notion of holarchy takes a long time to be understood by those who practice Holacracy, because the terms role and circle as defined today do not help much to go in this direction. I think only one term, a Role defined as being a whole and a part at the same time would bring value and help shifting mindset.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I'm curious to see how we will let ourselves be moved by the evolution on this and many other subjects.

**Comment by SamirSaidani** [comment]
@bernardmariechiquet Fortunately feeling an argument conventional and worn out does not invalidate an argument. Your argument as far as I understand is just to not reference the sides at all as they are useless, which does not also invalidate the argument. I think that we can both agree to disagree here. In my view, there is a confusion between Role and Holon, like taking the side of a coin for the coin, but it's probably just a matter of perspective : you seem to not see the holon sides at all as a valid perspective. 

Since you're talking about the origin of the Holon idea, a Holon is defined by Arthur Koestler, the inventor of the holarchy concept, as a "two-faced Janus, the Roman god: one side (the whole) looks down (or inward); the other side (the part) looks up (or outward)" (src: Wikipedia) in A. Koestler's book "Janus: A Summing Up". So I will at least agree with you on this: I'm not the only one to think that holon sides matter.

My bet is that at some point of the evolution of the "Nothing-else-than-a-Role" framework, you will feel the need to reference the Role (aka Holon) sides. I'm pretty curious to see how it will goes in real. Let's the practice settle this question.

**Comment by bernardmariechiquet** [comment]
> My bet is that at some point of the evolution of the "Nothing-else-than-a-Role" framework, you will feel the need to reference the Role (aka Holon) sides. I'm pretty curious to see how it will goes in real. Let's the practice settle this question.

Precisely all that I evoke comes to me from practice. More than one hundred companies have been accompanied in Holacracy since 2009!
And many clients share the same point of view as soon as they have a bit of practice and no longer confuse circle and "us".

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Is GlassFrog one of the barriers to merging role and circle? I would understand that.

**Comment by LouisChiquet** [comment]
If we are to keep the use of “circle” it'd make sense then, to like in holarchy systems, define each level with a different word (e.g. molecule, atom, proton/neutron, quark etc.) to not be confused at all, to ensure clarification of the level of complexity at which we are (which is bureaucratic imo). Or simplify it all with a single word as Bernard Marie proposed since the definition is the same at all levels.

For the two “faces”, we'd have the same issue as to “when use the word “circle” or not”, and simply use “super-role”, “role” and “sub-role” depending on where you're talking about, which is currently what we are already doing in companies with many levels in the holarchy. Looking from user-x, it'd concretely give:
“I'm filling the Copywriting role, which is in the Marketing circle, a sub-circle of Cosplay.”
“I'm filling the Copywriting role, which is in the Marketing role, a sub-role of Cosplay.”

Also on the pedagogy matter: the usage of the word “circle” is very conventional, and easily in the mind of people, is confused with the definition of a circle in sociocracy, or collective intelligence or other methodologies which have their own.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet No, GlassFrog isn't a barrier here, it's really just that it seems like a bad move to me.  But one thing that might convince me, or at least make the discussion more concrete, would be if you took a stab at editing the Constitution to integrate the terms.  My hypothesis is that the resulting version of the constitution would be way more complex and difficult to understand or follow.  If that hypothesis is proven wrong, and you end up with a result that actually seems simpler and easier to comprehend, then that likely would convince me.

**Comment by Aliocha-Iordanoff** [comment]
I tried to change the references to Circles to Roles only. It's still improvable but I think it's still clear and it brings something simple to have only one organizational container. 

I didn't send a Pull Request 

https://github.com/Aliocha-Iordanoff/Holacracy-Constitution/blob/Circles2Roles/Holacracy-Constitution.md

**Comment by brianjrobertson** [comment]
Interesting @Aliocha-Iordanoff!  I love the effort and getting to see what this might look like. And, having reviewed it now, my sense is that it doesn't work well. There's a technical elegance to it for sure, but it seems much harder to read and understand for a typical reader now.

**Comment by brianjrobertson** [comment]
I'm about to submit what I believe is a nice step towards what's been discussed in the thread above, without the potential downsides of it.  I’d love more eyes on the changes if anyone is willing to review, to help ensure I haven't broken anything.

In short, the change is that I’ve removed the domain of role assignments on the Circle Lead Role, which means the Circle Lead role definition now has nothing defined on it beyond whatever purpose and accountabilities are on the broader role.  So Circle Lead is still a separate role technically, but one with the exact same definition now as the broader role, and hence I think that will reduce some of the weirdness and potential confusion discussed above, and it just feels more elegant and simple to me.

To get there though, I ended up making some other related changes:

- I finally got rid of the really awkward and confusing language in former §1.2 about domains on role assignment, and replaced it with much more understandable language about Circle Lead authority to assign roles.
- You can still delegate role assignment power from Circle Lead to another role by creating a domain, using the rule that says any function or power of Circle Lead can be delegated just by placing it on another role.
- However, because role assignment is no longer a domain, that means you can’t use the rules of announcing intent to impact a domain to change a role assignment; you have to get explicit permission from the Circle Lead.  I could add a clause allowing announcing intent, but it adds a lot of text and makes the whole thing read more complex, which I don’t like, so I've opted not to (but welcome feedback).
- I changed the rules around Covering Unfilled Roles to default unfilled roles to being filled by Circle Lead, instead of by whoever controls the role assignment (if that's been delegated from Circle Lead).  This made everything read much smoother, and I think it actually makes more sense this way anyway.

Comments are very welcomed, just share them soon, because we're getting very close to releasing v5.0 now...

**Comment by SamirSaidani** [comment]
For what it's worth, and for the record, I'm sharing the current model we are using in our company, that avoids to have the Role Lead "automatically" filling CL Role. 

We are still using the term "Lead Link" (LL), but just read "Lead" if you prefer: 
- a Role has a unique inner Circle, with at least one Role, the LL Role. 
- We always talk about the LL of the Role X, outside X, or the LL of the Circle X, inside X. 
- LL is an atomic Role (no inner circle).
- Filling a Role _means_ filling its LL Role. 

Works fine for us.

**Comment by Aliocha-Iordanoff** [comment]
@brianjrobertson 

Once these changes are made, we are finally very close to the idea of using only one entity: the role.  And the partner assigned to the Role is Role Lead. 
This partner has the authority to assign sub-role leads and so on. 

I think that would really be a step towards conceptually simplifying the constitution. It just requires reworking some semantics in some articles to avoid clutter in the sentences. I'm willing to work on it with you in the next few days if it can be integrated into 5.0.

**Comment by brianjrobertson** [comment]
Sorry @Aliocha-Iordanoff, after reviewing the impact of this change in your prior draft, I believe it'd be more harmful than helpful.  It seemed to greatly complicate the mental model required of the user, and I didn't get a sense that further work on it would likely improve that - it seemed a more fundamental issue than wording tweaks would help alleviate.  Besides that, I've already announced that v5.0 is now feature-complete and no further significant changes will be attempted, so those who were waiting for that announcement to start translation and other work based on it can proceed, and I don't want to reverse that stance now that I'd communicated it.

**Comment by stephaniedwelch** [comment]
Just saw this, this morning.

First item I notice is that, given "the Circle Lead role definition now has nothing defined on it beyond whatever purpose and accountabilities are on the broader role," there is something curious in 1.4.5.

`A Circle may add Accountabilities or Domains to the Circle Lead Role, and later remove these additions. ...`

`A Circle may remove any Accountabilities, Domains, authorities, or functions of its own Circle Lead Role. It can do this either by placing them on another Role in the Circle, or by defining an alternate means of enacting them. ...`

Part one seems clear, but part two now seems to conflict since there are now no inherent Accountabilities or Domains; should it only state "authorities or functions?" Otherwise, it seems all Accountabilities and Domains would now fall under the earlier paragraph and not need to be reassigned in order to be removed.

Unless we are talking about being able to reassign the Accountabilities and Domains of the Circle itself, but that isn't super obvious and might need to be spelled out. Such as: "A Circle may remove any authorities or functions of its own Circle Lead Role, or any Accountabilities or Domains inherited by the Circle Lead Role from the Circle itself. It can do this either by..."

**Comment by brianjrobertson** [comment]
@samir-s I really like the use of "means filling" in your language use above - I think that's a nice improvement over "automatically fills".  I'm going to integrate that into the constitution momentarily; thanks for the contribution!

**Comment by brianjrobertson** [comment]
@stephaniedwelch Regarding [your comment](https://github.com/holacracyone/Holacracy-Constitution/issues/382#issuecomment-828605294) above, it's referring to Accountabilities and Domains added by a Super-Circle to the Circle Lead role.
