### ISSUE TITLE
potential loophole: what is added to a circle lead role can never be erased from governance

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#390]
In 1.5.3:

> A Circle may add Accountabilities or Domains to its Circle Lead Role, and those additions automatically apply to every Sub-Circle's Circle Lead Role as well, recursively. A Circle may not add Accountabilities or Domains just to its own Circle Lead Role.

> A Circle may remove any Accountabilities, Domains, authorities, or functions of its own Circle Lead Role. It can do this either by placing them on another Role in the Circle, or by defining an alternate means of enacting them. Doing this automatically removes the relevant element from the Circle's Circle Lead Role, for as long as the delegation remains in place.

If I interprete this strictly: suppose I add an accountability XYZ to the Circle Lead Role (thx to the 1st paragraph), then the second will forbid total removal of XYZ and force to maintain it in existence through delegation to a role or a process.

Thus: what is added to a Circle Lead Role can "never be removed from governance".

**Comment by bernardmariechiquet** [comment]
I think that @benoitpointet points out a flaw in the solution implemented here to manage, among other things, the tension that I brought a few months ago. https://github.com/holacracyone/Holacracy-Constitution/issues/330

I would suggest
> A Circle may add Accountabilities or Domains to every Sub-Circle's Circle Lead Role, recursively. A Circle may not add Accountabilities or Domains just to its own Circle Lead Role.

This would still solve the tension I brought https://github.com/holacracyone/Holacracy-Constitution/issues/330 because the concrete cases that I have related occur at the level of the Anchor Circle that wishes to define explicit managerial functions for all CIrcle Lead Roles into the whole holarchy, for the Circle Lead Role definition previously defined in appendix A.

Or option 2,  we could open up the possibility of modifying the role of the Circle Lead Role only at the level of the Anchor Circle, which would be exactly what reality has brought us (I mean iGi institute) as cases in recent years, and which has led us to develop constitutional amendments. 

This raises the question: how far to anticipate a pattern beyond what reality has shown/demonstrated to us.
Are there concrete cases that would show that the second option, which consists of letting the anchor circle define the role of Circle Lead Role itself, (as a parameterization of this managerial role that is specific to each organization), would not be enough?
