### ISSUE TITLE
Recursive amending of all 4 "core roles"

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#391]
> A Circle may add Accountabilities or Domains to its Circle Lead Role, and those additions automatically apply to every Sub-Circle's Circle Lead Role …

I love this recursive construct, this will make it very easy to customize this role to the needs of an organization. It can be seen as over-engineered, but the gain of clarity when it applies to the whole org or big chunk of it is significant. 

**Recursive** amending is not something that seems foreseen for Circle Reps (4.1.1), Facilitators and Secretaries (4.1.2). Is there a reason why? It would be very handsome to have the same mechanism.

**Comment by brianjrobertson** [comment]
Just because I've never seen or heard of a use-case that requires it (or, ideally, a common use-case in several orgs).  I have seen that with Circle Lead but not the others, and the Constitution generally only evolves based on real experienced tensions, not anticipated ones.  If you have run into such cases, please do share them and I'll reopen this issue.
