### ISSUE TITLE
"Progress Updates" --> "Progress on Projects"

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution#393]
It is unclear, what _"or other initiatives"_ refers to during the "Progress Updates" step. I have never ever experienced anybody reporting _anything else_ than **updates on projects**.  Therefore, I propose to drop _"or other initiatives"_ because it is redundant (and confusing, since nobody knows what it means). 

On the _facilitation card_, this step is referred to as "Project Updates", not "Progress Updates". While discussing this issue in our translation team we agreed that highlighting the "progress" part is still useful, since we want to get at what is new or different, i.e. the progress part of the information. 

The new name of the step, **"Progress on Projects"**,  is a compromise between "Progress Updates" and "Project Updates" that contains the best of both names. 

### _**CURRENT VERSION**_

**2.2 Meeting Process**
The Partner convening a Tactical Meeting must find someone to facilitate it. Unless a Policy says otherwise, that person must use the following process:
[...]
**(d) Progress Updates:** Each participant highlights progress in any Project or other initiative that they are regularly reporting on for their Roles in the meeting. Participants may only share progress made since a prior report, and not the general status of any work.

### **_NEW VERSION_**
**2.2 Meeting Process**
The Partner convening a Tactical Meeting must find someone to facilitate it. Unless a Policy says otherwise, that person must use the following process:
[...]
_**(d) Progress on Projects:**_ Each participant highlights progress in any Project _[...]_ that they are regularly reporting on for their Roles in the meeting. Participants may only share progress made since a prior report, and not the general status of any _project_.

**Comment by bernardmariechiquet** [comment]
On this point, I don't quite agree in that as far as I can regularly give news on things that are not projects at tactical meetings. Like for example tensions that everyone is supposed to manage in the long run (even if the software doesn't allow it), or new habit that I have set myself (sometimes the checklist is not a sufficient mechanism), or recurrent flow supported or not by accountability like for example "publishing an article every 2 weeks". In the latter case, each article is not captured as a project on the software because my production process is so automated that it is not useful. And yet it is useful to report on the progress made during tactical meetings. 
Where I agree with you is that there's something missing in the software: things that are not projects and that may require news. Progress in managing tension, for example.

**Comment by brianjrobertson** [comment]
The current rule intentionally does allow for more than just project updates, as @bernardmariechiquet states and offers examples for.  So @denniswittrock, you're suggesting a change in rule to a more restrictive rule, and to consider that, I'd need to hear arguments for why the broader allowance is actually harmful (not just that it isn't used, because it definitely is in some companies).  I'm closing this as a result, but please do comment (or open a new issue) with arguments for restricting the current rule if you have them.

**Comment by denniswittrock** [comment]
@bernardmariechiquet and @brianjrobertson, thanks for the examples and the clarification. The issue is closed for me as well.
