### ISSUE TITLE
Move core role definitions from an appendix to inline in the constitution

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#404]
I believe the constitution would be easier to follow and feel more organized if the core role definitions were directly inline, vs. called out at the end of the document in an appendix.  For example, instead of the section in Article 5 saying each Circle has a Facilitator and referencing the Facilitator role in the appendix, it would just define the role right there inline (and the appendix would go away).  Beyond the usability/organization benefit, another big advantage of this is that the Secretary role’s accountabilities could be added when relevant, in different articles; e.g. in Article 1 where it’s first defined, we could just reference that there is a Secretary role with its purpose; and then in Article 3, we could say that the Secretary role has an accountability for scheduling Tactical Meetings for the Circle; and then in Article 4, we could say that the Secretary role has an accountability for interpreting governance and the constitution to resolve conflicts of interpretation; etc.

**Comment by Aliocha-Iordanoff** [comment]
Yes, it is true that it would be more fluid and more natural to discover the definitions of these roles in the constitution as the articles call for them.

However, there is something else very useful about appendices. In reality, it is very rare for people to read the constitution starting at the beginning and going to the end of a draft. In everyday life, when they consult the constitution, it is often to go and look for a particular thing, a specific article, a detail, an answer to a question.

So I would support your idea, and also, the idea of having more extensive appendix, with the definitions of all the terms defined by the constitution. Like a glossary. Because it won't be easy for everyone to remember where the roles are defined.

**Comment by brianjrobertson** [comment]
@Aliocha-Iordanoff I believe GlassFrog will still serve that use-case for the core role accountabilities specifically - you'll still have those roles defined in there with all accountabilities all in one place, just a click away.  But that aside, I also like the idea of a glossary - not as part of the official constitution in github, but as a supporting document with lots of handy definitions all in one place.

**Comment by SamirSaidani** [comment]
@brianjrobertson not everyone is using GlassFrog, the constitution should be designed in a software-independent mindset in my opinion. I think both are relevant: inlining and keeping the Appendix as it is, it's definitely useful as Aliocha mentioned.

**Comment by brianjrobertson** [comment]
Looks like implementing this change gracefully will require moving the Facilitator role definition into Article 1, so I'm doing that as well...
