### ISSUE TITLE
Putting back the ‘de Minimis’ rule

### ISSUE THREAD

**Issue by nicksosborne** [holacracyone/Holacracy-Constitution#412]
When a linked role is multi-filled and then linked into multiple circles with a Role Focus for each person for each of their respective circles, this means that each of the people who is filling that role become full circle members in each of the circles the role is linked into- and this is how it shows up in Glass Frog. 

This is a problem as it then skews the circle membership, when really only the person with the focus for a circle should be showing up as a full circle member. This is currently happening with a client and they are requesting that only the person with the focus of their circle shows up as a circle member, and not the others. 

I think that putting back the ‘de Minimis’ rule in the constitution would solve this- so this is a request for this.

**Comment by brianjrobertson** [comment]
This isn't a case I'd consider as an argument for putting back the de minimis rule, because it's purely a limitation in the software tool.  From a constitutional standpoint, in v5, if a Focus is used, each Focus assignment is treated like a totally different role; that means for role linking, each one individually should be linkable separately, as if different roles, and you shouldn't even be able to link all of focus assignments into another circle (unless you individually invited each focus to do so).  GlassFrog has an epic on the roadmap to support this; basically, to treat each focus assignment as a totally separate role in virtually all ways outside of governance, but as a single role for governance purposes only.

**Comment by nicksosborne** [comment]
Ah- good point! I haven't fully understood yet how each Role Focus should be treated like an entirely separate role -1.4.1. 

My mistake, thanks for clarifying!

In that case Brian, when creating Linked Role with multiple Foci assignments, until Glass Frog is updated to support this, the Circle Lead should just create a separate role for each Focus assignment right, and then link each of the roles separately right?

**Comment by brianjrobertson** [comment]
That's definitely one possible workaround, yes... although I'd probably have the Secretary do it vs. Circle Lead, given their domain on governance records, and the importance of not screwing that up and accidentally changing governance outside of the formal process.

**Comment by nicksosborne** [comment]
Ah ok thanks! The Circle Lead can do it for this current situation, since Article 5 has not yet been adopted.
