### ISSUE TITLE
Move clause regarding asynchronous proposals being escalated to a meeting?

### ISSUE THREAD

**Issue by stephaniedwelch** [holacracyone/Holacracy-Constitution#414]
Every time I read Article 5, I get the feeling the following sentence from 5.4 would have been more helpful in 5.3:

`At any point while the Circle is processing a Proposal asynchronously, any Circle Member may request the Proposal go to a Governance Meeting for real-time processing instead, and the asynchronous processing must then immediately stop.`

Perhaps as the third paragraph in 5.3, between "after which anyone who has not responded is assumed to have no Objections," and "When making Proposals or raising Objections..."?

I see that the term isn't officially defined until 5.4 so I can see why it wouldn't want to be referenced sooner. Yet, opening things up in 5.3 with "using any communication channel allowed by the Secretary" implies that many or most proposals *might* be processed without ever going to a meeting, and if someone is using this section for reference outside of a meeting, it's the time they would most need to know they have a right to interrupt and escalate the process.

**Comment by brianjrobertson** [comment]
This makes sense to me, nice catch; I'll move it.  I'm also going to slip in an allowance for a policy to modify that default treatment, because I've seen no reason not to allow per-circle experimentation with changing this rule (and the design principle I'm applying is to allow policies to modify default constitution rules unless there's a clear case where that doesn't make sense).
