### ISSUE TITLE
Secretary not Core Circle member? Objections raised by Secretary?

### ISSUE THREAD

**Issue by julianeroell** [holacracyone/Holacracy-Constitution#42]
Reading 2.3.1, I understand that a Circle's Secretary is not considered a "Core Circle Member".

Reading 3.2 and 2.3, I understand that only "Core Circle Members" are taking part in the Circle's Governance Process.  

This is surprising to me: I believed to remember situations in my Holacracy training where in Objection round, the Secretary would raise a "not valid governance output" Objection. Now, it seems, that this is not possible in this way: rather, the objection would have to be raised by a Core Circle Member, and the Facilitator might _then_ ask the Secretary to confirm (3.2.5 last paragraph).

Is this correct (that is: is this the intended behaviour)? Or shouldn't the Secretary rather also be considered a "Core Circle member" to be able to raise Objections themselves? (This seems more logical to me, but I may be overlooking something.)

**Comment by MiekeByerley** [comment]
Hi Martin, Just a question? "I believed to remember situations in my Holacracy training where in Objection round, the Secretary would raise a "not valid governance output" Objection" - Was this objection specifically raised in the capacity of "Secretary" or in the Capacity of one or more roles held by that same person? The person energising the Secretary role often (in my opinion should always)holds another role within the respective circle and therefore could raise an objection from the capacity of that role which would be deemed a Core Role. I think this is why IGI partners make it a fundamental practice to identify which role a person is speaking from and which role they are addressing within the meeting format. A Secretary Role or Facilitator Role can not raise Objections etc because of the nature of their role function, they exist to facilitate Human Relational interaction and have no Organisational Structural purposes. I guess it is a little like a Judge not being able to raise an objection in a court (that is the role of the legal participants) but may uphold it if deemed legitimate. I hope this somewhat made sense. :)

**Comment by julianeroell** [comment]
Seeing the Secretary as "facilitating Human Relational interaction" only now makes complete sense to me - thank you for putting it in this way! 

I believe I always took the Secretary's accountability of "interpreting Governance and the Constitution upon request" also as a job to somehow "represent the constitution", and thereby point out when an output is not valid. I ignored the "upon request". :) 

In my memory, it was indeed the Secretary _in that role_ who raised the objection, but my memory may be wrong. 

(I am now wondering what happens when not-valid output is produced and nobody raises an objection.)

I will close the issue here, for I feel my original question is answered and it needs no further work in the constitution text; but I am open for more comments / discussion on the point raised, and for another person to reopen the issue if they see something that does need change. Thanks again!

**Comment by brianjrobertson** [comment]
The Secretary is a Core Circle Member for the duration of any Governance Meeting, per Section 3.1.1, and they are free to raise objections if a proposal would limit their roles:
http://www.holacracy.org/constitution#art311

The Secretary is just not a Core Circle Member beyond the meetings, _unless_ they are already one due to other role assignments...
- Brian

**Comment by julianeroell** [comment]
Thank you Brian! I just came across the same section as I was going through the constitution. All clear now.
