### ISSUE TITLE
Clarification question re 4.2

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#421]
@brianjrobertson I am fine tuning the translation of constitution 5.0, and need some help there to get into some nuance, if any.

Could you tell me the reason why you use in[ article 4.2](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#42-interpretation-authority ) (first sentence)
"As a Partner, you may use your reasonable judgment to interpret **this Constitution and anything under its authority**"

Instead of what you used in 4.2.1 (first sentence)
"As a Partner, your interpretation of **this Constitution and the Organization's Governance** may sometimes conflict with another Partner's"

Further, the fact two different ways being used create some confusion, at least for me.

What would be missing in case we use the second way as in 4.2.1 ?
Are you thinking of the Relationship Agreements ? Something else ?
In such case, I would recommend changing the wording in 4.2.1 in order to bring coherence with the other articles within 4.2
If nothing is missing, I would opt for **this Constitution and the Organization's Governance** it may be a bit clearer to get as a new constitution reader.

Thanks for response

**Comment by brianjrobertson** [comment]
@bernardmariechiquet The reason it's written that way in §4.2 is because it's not just Governance that this clause is meant to apply to, but also Relational Agreements, and Next-Actions and Projects, and priorities and Strategies, and everything else referenced in the Constitution that's not actually part of the definition of "Governance".  But in §4.2.1, the intent is to limit the power of a binding Secretary interpretation to just Governance, and not to Relational Agreements or other constructs.

**Comment by bernardmariechiquet** [comment]
Thanks! Got it @brianjrobertson

**Comment by SamirSaidani** [comment]
Interesting. What if there is a conflict of interpretation for Relational Agreement? It makes sense IMO to provide some default process to handle this kind of highly likely situation, given that a third party might "enforce Relational Agreements during a meeting or a process, as long as they don't conflict with anything defined in this Constitution". Makes a lot of room for conflict of interpretation...

**Comment by brianjrobertson** [comment]
@SamirSaidani That was intentionally left out; if there's a conflict of interpretation of a Relational Agreement, forcing someone to conform to a Secretary's interpretation seems off - it gives the organization power over the individuals in a way that I think could violate their sovereignty.  We also have no evidence yet that it's useful or needed - it might be that just renegotiating the agreement and updating the language between the parties involved in the conflict works just fine (in fact my guess is that it will, because that's typically the healthy approach already in private life and many organizations when people have conflicting interpretations of agreements).

**Comment by bernardmariechiquet** [comment]
@SamirSaidani Thank you for this issue. I had thought about that too, in addition to the arguments given by @brianjrobertson, I remember in such a situation, a partner may terminate the Relational Agreement. So there's always that exit door.

**Comment by SamirSaidani** [comment]
> 
> 
> @SamirSaidani [...] just renegotiating the agreement and updating the language between the parties involved in the conflict works just fine (in fact my guess is that it will, because that's typically the healthy approach already in private life and many organizations when people have conflicting interpretations of agreements).

My guess is that it won't always work fine, because the healthy approach is not the typical one... Actually, I have some evidences in my experience to support this guess. I think this process should at least be facilitate by a mediation process, like the communication & restoration process or something alike. Lack of mediation process might hurt the organization.

**Comment by bernardmariechiquet** [comment]
@SamirSaidani In most of the companies I accompany, such mediation processes and mediator roles are effectively set up. This is nothing new with the adoption of Holacracy, as these processes and roles could most often exist in conventional organizations. These are roles that are necessary to meet social needs.
