### ISSUE TITLE
Clarification Question re Article 1.3.4

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#424]
Hi @brianjrobertson 
In [Article 1.3.4](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#134-linking-into-circles ) third paragraph
**..., unless a Policy within or acting upon the Role's Super-Circle says otherwise.** 

Could you explain why you chose "Super-Circle" and not "Circle" ?

Thank you in advance for your answer

**Comment by brianjrobertson** [comment]
Let's say there's a Circle A, which includes a Sub-Circle B, and B created Role R.  Circle B is the Super-Circle of Role R; it'd be easy to think that the Super-Circle of R is referring to Circle A, but it's not - in v5.0 constructs, Role R's Super-Circle is Circle B, not Circle A.  The reason that clause uses Super-Circle instead of just Circle is because if Role R is linked into another Circle elsewhere, say Circle C, then it's important that clause is only referring to the Circle that "owns" Role R (Circle B in this case) and not to Circle C that also holds Role R because it was linked in; if the clause just said "Circle", it would mean that Circle C could create a policy that limited Role R's ability to unlink from it, which I believe would cause all sorts of potential issues.  Does that answer the question?

**Comment by bernardmariechiquet** [comment]
Yes it does answer my question @brianjrobertson , thanks.

However, I would have recommended to use the same construction as in the previous paragraph, i.e. to use the formulation "Source circle" instead of "Super-Circle" even if the two expressions fit.

In second paragraph: "The authority to add or change assignments into the Role stays with its **source Circle**. The Circle a Role links into is not considered its Super-Circle, and nor is the Role's inner Circle considered its Sub-Circle."

The fact of using 2 different constructions in two contiguous paragraphs can hinder the best understanding.
And so in the French translation that I am finishing, I intend to put the phrase "source Circle" in both places. 

This would give :
"A Circle may unlink a Role by removing the Policy that invited it to link, or by another mechanism defined in that Policy. A Role may also opt to remove itself from a Circle it linked into, unless a Policy within or acting upon the Role's **source Circle** says otherwise. Once unlinked from a Circle, any Governance added to the Role by that Circle is automatically removed."

Would you see any counter-indication to this?

**Comment by brianjrobertson** [comment]
This makes sense to me, I like the change.
