### ISSUE TITLE
Clarification question : why 4.2 & 4.3 are restricted to Partners only?

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#427]
@brianjrobertson According to [article 1.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#11-role-definition) "Whoever fills a Role is a "Role Lead" for that Role." my interpretation is that a non-Partner may fill a Role and becomes a Role Lead for that Role.
In case article 4 being adopted, distributed authority applied to any Role Lead even filled by a non-Partners, right?
So I wonder why the authorities described in articles 4.2 and 4.3 are explicitly reserved for Partners - which is not for beginning of article 4 - preamble and article 4.1.
Can you shed some light on this one?

**Comment by brianjrobertson** [comment]
@bernardmariechiquet Let me explain with an example: Imagine you have an external part-time contractor with only a light connection to the company, like say an outsourced bookkeeper or graphic designer.  It would be really useful for clarity's sake if you could assign them to a role, so everyone can see the basic accountabilities they can expect of them.  But if assigning them to a role conveyed all the duties in Article 2 (i.e. if those were all duties of all Role Leads), then you'd actually have to get their agreement to enact all those duties before you could assign them to a role, or you're creating a weird constitutional contradiction (i.e. the constitution says all Role Leads have these duties, but actually only some do and some really don't).  And if you try to avoid that problem by actually getting them to agree to all of those duties, then that makes the relationship and contract required much, much heavier - and you may not actually want such a deep relationship or such a complex contract with your outsourced bookkeeper or graphic designer (or even if you ideally do, you may not want to pay for the extra cost of them doing all those duties).  And if you do want them to agree to those duties, you can still ask them to and make that part of their contract; this doesn't prevent it, it just defaults to not requiring it.

On the other hand, when it comes to the authorities of filling a role in Article 4, the above isn't a problem at all - granting someone authority does not require getting their agreement, because they aren't signing up for any expectations; they can simply choose not to use any authority you offer them that they don't want to use.  And it wouldn't make much sense to even assign someone to a role in the first place if you didn't want to grant them the powers of leading the role - that's the whole point of a role assignment.  And if you want to constrain that power to lead a role for a contractor-filled role, you can simply do that with a policy anyway - thus the baseline of granting anyone assigned to a role the power to lead it makes sense, but requiring they agree to all the general duties does not.
