### ISSUE TITLE
Clarification question: proposal always valid to reflect reality

### ISSUE THREAD

**Issue by LouisChiquet** [holacracyone/Holacracy-Constitution#428]
In 4.1 article 3.2.2 we had “_Finally, a Proposal is always valid regardless of the preceding criteria if it is made solely to help evolve the Circle’s Governance to more clearly reflect activity that is already happening, or to trigger a new election for any Elected Role._”.
However in 5.0 article 5.3.1, I only find the criterias, but no longer that “exception” (over the fact that basically a proposal is always valid if it's for putting reality in governance) if I'm not mistaken? May you clarify why it was done?

**Comment by brianjrobertson** [comment]
It got cut because I've never seen a case where it was actually an important rule - I don't believe there's ever a reason why it's important to have that exception in there for the otherwise-required proposal threshold.  At the same time, I have seen cases where it hurt, by either allowing people to get caught-up doing documentation for documentation's sake or org design from mind, or by making it too easy for someone to dodge the proposal test questions by claiming they're just capturing reality, when they're actually trying to subtly change something.  So, because of all that, I cut it.

**Comment by bernardmariechiquet** [comment]
Thanks Louis, I hadn't even noticed.
And I must admit that Brian's arguments are very convincing.
