### ISSUE TITLE
Remove Rep Link metrics accountability

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#65]
The accountability on Rep Links to report on metrics doesn't make sense; I added it in a prior version based on a purely theoretical idea (whoops), and it's been very weird in practice - it gives the rep link an operational responsibility in the broader circle, which the broader circle lead link needs to count on, and this has been very weird in practice and seems incongruent with the rest of the role.  And note the Lead Link's responsibility to report on metrics is already covered by [§4.1.1(d)](http://www.holacracy.org/constitution#art411), so this accountability seems purely unnecessary.

**Comment by julianeroell** [comment]
I tried to find this in the constitution, and noticed that it wasn't there: turns out it's only in Appendix A (Definition of Core Roles). 

(Note to self to get working on it, or to other collaborators to find it there and propose a fix.)

(And yes, this is clearly a bug. We noticed the weirdness too, but couldn't articulate it well or find a workaround.)

**Comment by bernardmariechiquet** [comment]
This accountabiltiy is very useful when a Lead Link is not attending a tactical meeting.

**Comment by bernardmariechiquet** [comment]
And to add on my last piece, reporting metrics for a Rep Link would help him embodying its purpose in the super-circle (which is the purpose of the sub-circle) as metrics is much about measuring the manifestation of the purpose.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet:  I've seen that too, but it still seems like it adds more problems than it resolves, and introduces an inconsistency in the Rep Link role that's just not worth that small benefit.  Besides, to the extent it would support Rep Link's purpose, it shouldn't be needed as an accountability anyway - Rep Link could just choose to do it...

**Comment by dienkwik** [comment]
Hmmm... I'm already so used to this by now, that it does not feel weird to me :)

However, now that you mentioned it, it does feel a little weird, because Rep Link's purpose is to resolve tension in the super circle for the sub circle and reporting metrics just by default does not resolve tensions for the subcircle.

One case where this make may make sense perhaps would be that the metrics is being reported by the rep link due to a concern from the subcircle that the Lead Link is not reporting metrics truthfully ?

Anyway, @brianjrobertson, is this the inconsistencies or weirdness that you are feeling ?

**Comment by brianjrobertson** [comment]
That's part of it, yes...

**Comment by oliviercp** [comment]
Process clarifying question: @brianjrobertson when you post a bug here and seem to have a straight-forward solution to it, what are you looking for? General reactions? Or are you just listing it here for the record?

**Comment by oliviercp** [comment]
(reaction: I'm all for removing this accountability from the Rep Link, I have definitely experienced that weirdness)

**Comment by brianjrobertson** [comment]
Just listing it for transparency, although comments/reactions are welcomed (as is somebody else submitting a fix for it).

**Comment by dandouglass** [comment]
Reaction: "Defining" and "assigning" metrics (Lead Link) is different from "reporting" and "providing" (Rep Link) visibility on them. I propose this Role continues to energize transparency on metrics and health of the Circle to the Super-Circle...but in a way that counterbalances the Lead's reporting role and sources (primarily external) Tensions into to the Super-Circle for processing.

**Comment by brianjrobertson** [comment]
Not sure what you're saying @dandouglass...

**Comment by dandouglass** [comment]
@brianjrobertson - I'm new to Holacracy but I understand the Rep Link is a necessary tension-sensing mechanism to remove constraints and provide visibility into circle health for broader circle + lead link. Question - This is still a critical right? 

I understand the metrics redundancy "bug" in a tactical meeting but what about the Rep reporting on "manifestation of purpose" (@bernardmariechiquet) or tensions to be processed for subcircle (@dienkwik)? Could you clarify your proposal for this accountabilty in the absence of metrics?

**Comment by brianjrobertson** [comment]
Ah, gotcha; the proposal is to remove the accountability on rep link that references metrics entirely.

**Comment by cassus** [comment]
@brianjrobertson Does it help if I create a pull request about this?
Is there something missing before you'd adopt this change to `master`?

**Comment by brianjrobertson** [comment]
That would be great, go for it @cassus!

**Comment by gvandegrift** [comment]
Timely update to the constitution.  We had recently observed in our Tactical Meetings that Lead Links were leaning on Rep Links to report metrics.  We were getting ready to tell them that it is their responsibility--not the Rep Link's.  Then I discovered that accountability on the Rep Link and figured we were wrong.

At this point (assuming this accountability is removed from the constitution appendix), would it be reasonable for the Rep Link to decline reporting on metrics for his/her Circle at the Super-Circle Tactical Meeting if he/she doesn't feel it is necessary to his/her Purpose?

Happy to take my question to the CoP if it isn't appropriate here.

**Comment by brianjrobertson** [comment]
@gvandegrift:  That would certainly be reasonable once a new constitution version ships, and your organization upgrades to it.  Right now this isn't even an alpha release yet, let alone a published new version of the constitution - doing anything based on it would be a Really Bad Idea!

**Comment by rubzie** [comment]
Late to the party, but I’d like to share our (Springest, adopted Holacracy 5 years ago, now with 50 people) perspective. We’ve always viewed the Rep Link (RL) role as crucial to a certain information parity, i.e. the removal of the classical manager-funnel, by interpreting the accountabilities as a counter weight to the Lead Link (LL). By the way, this discussion surfaced because I wondered why reporting on projects was not an explicit accountability from the RL (thanks Joris Leker). The same goes for requesting projects from the super-circle members: we usually go through RL (or direct of course).

I understand the tension with a role’s accountability to report metrics / projects, to be conflicting with RL doing the same on behalf of the circle. But you can solve this in other ways too, eg. by making Rep Link more accountable and Lead Link less. To contextualize my reaction: the comments here feel like everyone is defaulting back to “Lead Link is a manager” for let’s say 66% instead of 33%. The other 33% being role holders themselves accountable, the first 33% being the strategy + role assignments, and the last being the reporting about sub-circle metrics, projects and tensions (this is just a way for us to explain the differences very roughly).

As for this accountability to be “weird and incongruent”: we find it fits the purpose quite well. Metrics and projects are the best way to surface tension, to channel out what’s happening in the sub-circle. And again, incongruence has two sides and I wonder why we’d default to this side and not to the other :slightly_smiling_face: 
In practice, it would mean that role holders talk to LLs a lot more about project updates and metric clarifications, possibly seeking approval for them which brings us back to a manager-like aura on the LL.

A LL 
>counting on an operational responsibility

from the Rep Link in the super circle actually sounds very good to us too. It relieves the Lead Link from being a funnel of information, potentially even hiding information from the super-circle.

For us, “Rep” means “representing” and if a Lead Link presents metrics and projects, then what does the representing still mean? We often explain RL vs LL with arrows by explaining something like: 
>the RL represents the circle upwards, the LL represents the super circle downwards, yes this is very hierarchical but it’s balanced.

Yes, being a RL is really hard for a newly elected circle member, we found. For LLs it's easier to share metrics and projects, because LLs are in that role much longer, are often more senior (not by default, but in practice), are more involved in other circles so have more context, etc. 

We think this is part of becoming a mature self-managed organisation. We have literally this week done our first dedicated internal RL training and have thought of several solutions (longer periods before new elections, RL certification before being eligible, better automation of reporting from roles to RL to super-circle), but not of simply letting the LL do all the representing.

We’re all very curious to hear your thoughts, but of course do agree that there’s something to be made explicit here. If this would’ve been a governance item at Springest, I’m sure there would be a lot of clarifying questions about the tension, especially on the “weird in practice” part. @brianjrobertson, can you give an example of this?

**Comment by diederickjanse** [comment]
I think this is a feature, not a bug, and it's consistent with the framing that the Lead Link represents the supercircle in the subcircle (outside-in, top-down), and the Rep Link represents the subcircle in the supercircle (inside-out, top-down).

I have actively coached on shifting the reporting on metrics and projects from the subcircle from Lead Link to Rep Link (e.g at Springest, see @rubzie's comment above) because my sense was the Lead Link was taking on too much by doing so, and became at risk of sliding down the slippery slope to being a manager in all but name. It basically upset the balance between Lead Link and Rep Link in the meetings of the supercircle, in my view.

So like Ruben, I'd love to understand the tension and 'weirdness' better because I don't see it.
