### ISSUE TITLE
Should a demand to initiate action be a valid policy?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#68]
We've had a few pitches from real-world cases to allow using policies to set an expectation of initiating action (this would be invalid in v4.1).  The primary argument is to make Holacracy easier to practice for novice practitioners - they often have trouble thinking of policies in Holacracy's definition, and will instead propose "policies" that demand a role initiate action.  One argument against this is that it obscures what a role is really accountable for by hiding it in a policy.

But I think the bigger issue with allowing this, by far, is that it would create the potential for subtly destructive expectations and inappropriate use of pressure, which Holacracy otherwise heavily protects from.  For example, using an accountability comes with a very clear constitutional definition of what that "accountability" actually lets you expect from someone, and it's not that "it will definitely be done".  But if an expectation were encoded in a policy, it doesn't come with that protection.

So, should we allow it for ease of early practice and simplicity, or keep as-is to force clarity?  If we should allow it, how can we still get the benefit of the protection described above?  Perhaps some kind of clause that covers what you can expect from a policy that demands action perhaps, to provide a parallel construct there as we have in an accountability?  Any thoughts?

**Comment by julianeroell** [comment]
First thought: allowing this would make absolutely no sense to me. If you want a role to to something, put it in an accountability. That's where it belongs. This also maintains the fundamental, realistic image that Holacracy has of organisations: humans at the center, filling roles, and then possibly fulfilling accountabilities (or not). And not: "Policies", expectations that "things will happen because they must (because it is policy)". Clear paths of action if one disagrees with how a role-holder prioritises. _Much_ clearer for me if it remains in accountabilities, and only there. 

(I'm curious about other points of view.)

**Comment by bernardmariechiquet** [comment]
Would allow this only to set expectations on Partners in the appropriate circle having the Partners Relationships Domain. This piece is a missing one in 4.1, you've to add by adding a general policy for being able to do so and by explaining that such mechanism would resemble as if a Partner would be a role filler having some accountabilities on them.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet:  Agreed that's missing, but I think it needs a whole different system/mechanism - we've got a separate exploration of that happening in parallel now...

**Comment by dienkwik** [comment]
Hmmmm, I haven't found a need to do this yet. When we started, there were proposals that required actions that we fixed in governance through "coaching timeouts". 
I suppose some policies with action requirements could have gotten through, but in this case we would simply fix it once detected.

So, I vote for not allowing this.

Having said that, perhaps allowing this through a policy labeled clearly as temporary violation of the constitution and with a definite end term may be a solution for those who need it ? 
At least it is clear that it is not supposed to be this way, and that this condition is temporary.

**Comment by deepmansingh** [comment]
@brianjrobertson: Agree with you completely.  At the same time I feel I'm missing something.  How does this "make Holacracy easier to practice for novice practitioners"?  What is the specific problem they are hoping to solve through this solution?  

Get a sense of comfort that something will get done by X date?  Be able to see the equivalent of a project plan?  Address the worry that _some others_ will use this opportunity to slack off, or work on stuff that _we_ don't believe is central to what is truly required?  Feel a sense of control in the face of the entire process being replaced with something which - right now, at least - appears completely alien?  Just get some visibility into potential work outputs over the next 2 weeks / month?  If the "boss" is going to "abdicate" his / her responsibility over setting work plans, then we'd better ensure that work doesn't stop?

Since this has come up more than once, there is clearly _some_ gap.  It would be useful to get a sense of the true felt needs, so they can be addressed: a nuance in training, FAQs, whatever, if that's all it takes.  And, if we are lucky, it could surface a true gap in Holacracy.

**Comment by MiekeByerley** [comment]
I am with those who would not allow this. As for me it contravenes a foundational intention of the  constitutions as you nicely put it:
<<is that it would create the potential for subtly destructive expectations and inappropriate use of pressure, which Holacracy otherwise heavily protects from. >>
Accountability is the appropriate space underpinned by the Metrics, also the Lead-Link role should come into play on this if it is a recursive issue and the last line of action is addressing this in the Partnership Agreements. Besides in essence there is an explicit expectation under Section 1.2 Responsibility of Role Filling

**Comment by brianjrobertson** [comment]
Thanks all!  I'm closing this question and not pursuing it further.
