### ISSUE TITLE
Rename "Individual Action" to "Individual Initiative"

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#72]
There's often some confusion with the term "Individual Action" - the word "Action" is in there, but it's not related to the concept of a "Next-Action" or really even a specific action of any sort.  So I often hear people say "I'll take an Individual Action" when they really mean "I'll take a Next-Action" (which may or may not be an out-of-role action under the rules of Individual Action)...

This has raised the question of whether to rename the term, perhaps to "Individual Heroics" or "Out-of-Role Heroics" to emphasize that this means acting out-of-role.  That has the downside of not allowing the current common turn-of-phrase that one is "taking Individual Action", although I'm sure other turns of phrase would show up instead (another candidate is "Out-of-Role Action", which wouldn't have that downside).  And of course there's the downside that changing language is always a pain in the ass and it may or may not actually stick in practice for groups that are used to the old language.

So, is it worth trying to change this term, or should we leave it as-is?  If change it, what would you change it to?

**Comment by julianeroell** [comment]
I think it is worth changing this; and "Out-of-Role Action" is my favourite.

**Comment by bernardmariechiquet** [comment]
Yep, I sense the same concern re "individual action".
"Out-of-Role Action" would be better and avoid that kind of confusion I encounter very often with clients.
Or let me suggest others "Breaking-Governance Action" "Outlaws Action" "Offside Action"

**Comment by karilen** [comment]
I agree it is confusing with Next Action sometimes...to sort out if it makes sense to even take Individual Action, one way to consider if it is of benefit to the organization versus a personally motivated thing, is to decide which role the action would serve, even if the role is GCC Lead Link, so I am not a fan of "out of role" action. I can't think of a better idea so I would probably leave it as-is for now as Individual Action...maybe further spell out the types of IA, including violating Governance or agreements to avoid more harm and you didn't even have time to communicate about this, VS acting as a role in an attempt to process a tension as a role that you don't fill.

**Comment by tensiondriven** [comment]
I personally like the term "Individual Action". I haven't personally witnessed it getting conflated with Next Action, though, so I am not sensing this tension.  Does the Constitution define the term "Individual Action"? If so, it might make sense to simply include the distinction with Next Action, and to include this distinction in training materials, and when training Holacracy coaches, so that all practitioners eventually get the distinction.

I also see a distinction between "Taking individual action" on a project, vs "Taking an individual action" on a project - As I see it, in the first case, action is used as a verb, in the second it is used as a noun (nominalization).

**Comment by dienkwik** [comment]
The term "individual action" does not immediately and intuitively convey the image of someone taking action that he/she is not supposed to take in normal condition.

"Out of role action" seems to be the closest one describing this so far.

**Comment by smichel17** [comment]
I think it's absolutely worth changing, even if everyone who's currently using holacracy keeps using the same terminology, for all the organizations just starting to use it.

The biggest mismatch for me right now is that "individual action" doesn't seem like a big deal, but in reality it's not something to be done lightly. "Out-of-role" action doesn't help too much with this. "Emergency action" goes waaaay to far in the other direction. Still coming up blank, still thinking..

**Comment by deepmansingh** [comment]
I personally like "Individual Action", because it maps well to "Taking Initiative" - which can be good or bad, depending on the circumstances, individual judgment, motivations.  If that term is getting confused with "Next Action", how about "Extra Role Action" or something like that?  This still maps well to taking initiative, and is neutral.

Both "Out of Role Action" and "Individual Heroics" have an undercurrent that seem to indicate it is always a bad thing.

**Comment by smichel17** [comment]
This part of the constitution exists because it is a good thing for people to be empowered to reach outside their normal authority, in some circumstances. That doesn't mean it's a thing to be done lightly.

I really like that word, though! What about "Individual Initiative"?

**Comment by oliviercp** [comment]
I quite like "Individual Initiative"!  I was trying to think of a
replacement word for "individual" because it's not obvious it means "out of
role", however replacing "action" by something else should solve the
confusion with Next Action, and I think "Initiative" works quite well and
is actually more accurate — often time taking Individual Action is more
than just one action.

At the time, it doesn't introduce an awkward expression like "Out of role"
would IMO. The easier we can keep the language the better.

 "Individual Initiative" got my vote :)

**Comment by deepmansingh** [comment]
Yup - "Individual Initiative" feels solid.

**Comment by lynoure** [comment]
To me "individual initiative" sounds like something one would expect everyone to have, all the time, within all their roles and "Out of role action" is clearer.

**Comment by smichel17** [comment]
What about "Out of role initiative" or something along those lines?

**Comment by lynoure** [comment]
Comment: For me "out of role initiative" is more descriptive than the current "individual action", though I've been many cases where "initiative" means just starting something and not solving anything. Anyway, no objection to that one. :)

**Comment by tylerdanke** [comment]
One problem that i have with "out of role" is that sometimes it is "inside
my role" but against current governance policies.

What can I do to best serve you right now?

Tyler Danke
purelypoultry.com/ | 920-732-6537 | tyler@purelypoultry.com

**Comment by brianjrobertson** [comment]
I don't want to go with "out of role" anything, partly for the reasons @tylerdanke suggests (it is sometimes in-role... in fact it's always in _some_ role, and maybe even your own), and partly because it's just too long and clunky.  My current intention is to go with "Individual Initiative", as it's better than the current phrase yet still close enough to make the transition easy.  Though I'd welcome better ideas to help distinguish it as something more exceptional than ordinary in-role initiative, if anyone has any...  "Extra Initiative" maybe...?  "Exceptional Initiative...?"  They don't quite have the ring that "Individual Initiative" does; I think I like that best so far...

**Comment by bernardmariechiquet** [comment]
On Brian's comment looking for something more exceptional, I'am not sure we want only exceptional Individual Action. There are, in my experience at least 2 kind of Individual Action (and may be more). Those which break the rules (and to Tyler point could be one taken in one of my roles but constrained by a Policy/Domain), and those which do not break any rule but are just creative tension inspired when tuning into the purpose of the Org./a Circle. I am not sure we want the latter being exceptional - in some organizations (like iGi or Teal Org. referred in Laloux's book), they are welcome given people are fully filling their current roles.

When reading 4.3, one can feel that acting out of one's roles is kinda _bad/only to do by exception_ - though I would recommend to rewrite this section in order to differentiate more at least these two kind of actions - I guess by doing so, may be we'll be able to let emerge two different concepts with two different names.

I also think we should make the connection within section 1.3, so that reader may have a more global view of their authority to act at first - (expanding the _Ferrari concept_) - this would reduce a tension I sense very often with clients who get at the first place the idea they should only focus on their roles even if they were doing other activities before Holacracy adoption that have not been encoded in the initial structure (which is an usual pattern I see) and some other cases.

May be extending 1.3 to all authority to act from the beginning, may allow to focus more/evolve the concept of Individual Action and then IA could become/be reduced to "Acting out of Authority" with a lower scope than today and we want that being more exceptional.

**Comment by brianjrobertson** [comment]
That's very helpful Bernard Marie, thanks!  I'll look into this as an option when I start working on #137.

**Comment by bernardmariechiquet** [comment]
Yes, it makes a lot of sense to integrate that in making the golden rules clear.

**Comment by Roflcopterpaul** [comment]
"Individual Deed" might be a good choice as well for the following reasons:
1) Having "Individual" in whatever choice you go with means it will likely be an easy transition from Individual Action to Individual Deed.
2) Deed has roughly the same meaning as action. It is something being done, and the word itself typically has positive connotations with it, though there still can be bad deeds.
3) I love the Individual Initiative idea, but I'd agree that we want everyone to have initiative at all times, so it might be avoided purely for that reason (but I'm not opposed to going with this idea at all).

**Comment by bombino** [comment]
+1 for "Individual Heroics".  I think it has the exact connotation we are going for:  that it is still a good thing, but not something that should be getting done on a regular basis.

**Comment by bstillwagon-mylo** [comment]
I like the term "Individual Exception".  It implies that the work being done is an exception to the work expected of any roles the person is filling and should be captured in governance if it continues to happen.

**Comment by brianjrobertson** [comment]
Okay, down to two options; please give me a thumbs-up reaction on whichever of the following two posts you like better to replace "Individual Action"...

**Comment by brianjrobertson** [comment]
"Individual Heroics"

**Comment by brianjrobertson** [comment]
"Individual Initiative"

**Comment by dawizsimpson** [comment]
Thumbs up for "Individual Initiative"

**Comment by Roflcopterpaul** [comment]
I can't leave reactions, but I vote for "Individual Initiative".

**Comment by bernardmariechiquet** [comment]
I vote for "Individual Initiative".

**Comment by karilen** [comment]
Exceptional heroics. I like individual heroics because it feels kind of raw and real and hits the point that this behavior is not sustainable. I like individual initiative because often there isn't a role, or someone is out or over loaded, or else a rule needs to be broken and all this requires initiative and may support people also taking individual action more, in a more mature way instead of just not my accountability and confused about IA v Next actions.

**Comment by LouisChiquet** [comment]
To rejoin Bernard Marie's upper comment, I suspect it would be better to say something as “Needed Action/Needed Initiative” or something very catchy like this, as effectively, it's not negative or exceptional (because can simply be things you take out of your roles rather than violating a domain) as I often use this term in order to explain it to people, so when you're doing one you think it's needed, as yes “_it is sometimes in-role... in fact it's always in some role, and maybe even your own_”. After I have no real opinion, just sharing.

**Comment by brianjrobertson** [comment]
"Individual Initiative" is my leading contender, but it's really long, both in number of syllables to say, and length of words (which affects GlassFrog drop-down menus and label text).  So, how about "Extra Initiative"?  It fits descriptively; I sense some risk that it's interpreted positively and thus encourages it (where I would prefer a term that is naturally more neutral), but I think that's a pretty minor issue.  What do you think, thumbs-up or thumbs-down on "Extra Initiative" instead of "Individual Initiative"?

**Comment by oliviercp** [comment]
@brianjrobertson I'm lukewarm on "Extra Initiative", not enough for a thumbs down but not being a fan of it for the reason you mentioned. You say the risk of the incentive towards it is minor, and I'm not convinced it's that minor. One perspective though is that if you make the change, then we will get some real-life data on whether it incentivizes the wrong behavior, vs not getting any. I do like the simpler expression, "Individual Initiative" is a mouthful

**Comment by tensiondriven** [comment]
"Outside Initiative"?  As in, outside of governance?  This has the opposite connotation of "Extra", which might be desirable.  In terms of character length when rendered, "Outside Initiative" is the same length as "Individual Action":
![image](https://user-images.githubusercontent.com/73313/45198198-2a196000-b21a-11e8-86c0-dbdf287e41e5.png)

**Comment by LouisChiquet** [comment]
Individual actions can be common, and in fact I'd like it to have a name which “communise” it, to make it understand that it's for the service of the purpose and if it makes sense for the company, then just go ahead. So “Extra Initiative” wants to make it sounds like, extra, which isn't my feeling.

I like the idea of @tensiondriven, but would maybe change “outside” by “out-role”? After my English isn't good enough to define if there's already some meaning around this. So I'd go for Individual Initiative too, as I imagine people catching the meaning of what it means more easily and explaining the two words it's composed of much easier to catch.

**Comment by brianjrobertson** [comment]
Hmm, interesting.  Okay, give me a thumbs-up reaction to this post if you prefer "Out-of-Role Initiative" over "Individual Initiative"; thumbs down if you prefer "Individual Initiative".

**Comment by rebeccabrover** [comment]
@brianjrobertson In my experience, IA (or what might become II) is often in the service of some role, just not by the current role-filler so it could, in theory, still be deemed in a role.
On a wording note, out-of-role initiative requires two dashes and four words which could get clunky and hard to explain and translate in languages other than English. I imagine explaining it to training participants and think it will take at least 10 minutes just to make sure all members have the phrase right at all. Individual initiative gets the point across and rolls off the tongue more easily. Learning the language is already a tough part of adoption. Any way to keep things simpler is useful.

**Comment by chrcowan** [comment]
Just want to bring transparency to the fact that I've read this thread, thought about, researched some options, and still don't have a strong read on things. :(

**Comment by MiekeByerley** [comment]
Hmm, I have been reading this string and trying to get a feel for what is being grappled with. I have a suggestion, instead of "Individual" or "Out-of-Role" why not simply state is it as "Personal", so a "Personal Initiative" or even , more in line with  "to make it understand that it's for the service of the purpose and if it makes sense for the company, then just go ahead." and also Brian's **Sensor** analogy  "Personal Response". The term **Personal** automatically denotes, out-side of Role jurisdiction, but also indicates possitive intent, "Individual" is often extremely unfavourabley associated with the terms "Individualism"or "Individualistic".

**Comment by chrcowan** [comment]
@MiekeByerley: I see where you're coming from on this, but "personal" isn't really accurate either because Individual Action is still something in service to the organization's purpose (e.g. inventing a new product outside of a pre-existing role) not something I'm doing in service of me personally (e.g. trying to increase the number of vacation days I have). Not saying you don't know that, but just highlighting that "personal" could easily get misunderstood.

Of course, there is a lot of grey area in-between, like if I wanted to work on developing a new skill which would help me energize the organization's work, but that's kinda the point; the term "individual action," or whatever replaces it should hopefully make it easier to make the nuanced distinction: "work-outside-of-a-currently-defined-role, but-COULD-BE-a-defined-role-because-it's-still-in-service-to-the-organization," versus work that is 1) already in a defined role, or 2) is something I'm doing for myself personally. 

I don't sense the same tension with "Individual action," but maybe "organizational action," or "purpose action," or "contributive action,"....I don't know. It's a tough one.

**Comment by MiekeByerley** [comment]
Interesting @chrcowan and I can understand your tention, I think this is actually a language preference based on the understanding of the 2 terms **Individual**, and **Personal**. For myself and I know many others we shrink from the term Individual because it denotes "seperation, isolation, unaccosiated" and is the complete oposite of Collective (perceived as negative). Personal does not have this connotation, the term incorporates the understanding of relationship and connectedness, it holds both Individual and collective perspective simultaniously. So for me the Individual Action is never perceived as, in service to OTHER but rather always to the individual doing the action (Individualism), where as Personal Action is one taken as an individual in context of other (Personalism). 

I am not sure how you would overcome this other than looking at the Constitutions general demographics, their language paradigm and then the intent of the Article itself. Most people are institutionalised in the Individualism Paradigm so by using that term you are reinforcing the associated behaviours, if the intent is to guide them out of Individualistic tendencies and towards a Systemic Systems Paradigm then it is better to avoid terms that automate default behaviour. 

A really good litmus test is whether someone coming from the collectism paradigm Reacts strongly to the language :)

**Comment by brianjrobertson** [comment]
One other idea just surfaced internally in H1:  How about "Provisional Authority" instead of "Individual Initiative"?  e.g., in context:  "As a Partner of the Organization, in some cases you are authorized to take **_"Provisional Authority"_** and act outside of the normal authority of your Roles, or even to break the rules of this Constitution.  When you exercise Provisional Authority, you must...  You may only use Provisional Authority if the following are true... etc."

The definition of provisional seems appropriate for this:  “providing or serving for the time being only; existing only until permanently or properly replaced; temporary”

So, what do you think?  Should we switch from Individual Initiative to Provisional Authority?  Please react thumbs-up for yes, thumbs-down for no.

**Comment by Nick-Osborne** [comment]
I wonder if Provisional Authority, while perhaps being more technically accurate, might be one more piece of Holacracy jargon, whereas as least Individual Initiative is more generally used

**Comment by MiekeByerley** [comment]
What about **"Provisional Initiative"** @brianjrobertson ?

**Comment by ericdgraham** [comment]
I like individual initiative and makes sense to me. A lot of syllables though. Doesn’t quite roll off the tongue. 

I also liked: personal initiative (sounds the most intuitive, but easy to confuse the role/personal boundary)

Another option: Special initiative (I think people could react to special though)

I think interim communicates the point nicely. Here are two options:
interim initiative
interim authority

So final vote would be:
individual initiative

OR one of these two:
interim initiative
interim authority (I like this one best of the two)

**Comment by brianjrobertson** [comment]
@ocompagne Care to share your argument for "Provisional Authority" over "Individual Initiative", before I close the issue and dismiss the idea?  And, related, do you prefer that or @ericdgraham's suggestion of "Interim Authority"?

**Comment by rebeccabrover** [comment]
@brianjrobertson I read through the entire thread and the one thing surfacing for me is the notion that all of these contenders are still a mouthful and sound like jargon to some degree (likely unavoidable but certainly something to consider). When I tune into the grounded goal of lowering the bar to successful Holacracy practice and adoption, the phrase coming to my mind is _Gap Action_ because that's what it is. It's action taken or series of actions taken likely due to a gap in governance, a potential gap in energy, insight or availability of a current role-filler or even a gap in safety that requires immediate action to guard an organization from harm. A _Gap Action_, unlike an Individual Action, Provisional Authority or Individual Initiative, could also be taken by more than one person if needed (useful if I understand some of the new role-filling options in v.5) and (in my opinion) a natural human reaction to a gap is to fill it - in this case perhaps with new governance or further interaction with a current role-filler.
_Gap Action_ rolls of the tongue well (and quickly) in English and I think translates to relatively short words in most Germanic and Romantic languages which is also something to consider. I also did a quick search for the phrase to see if it has prior connotation and the only thing I could find was a reference to a WHO mental health program I don't think would cause confusion - https://www.who.int/mental_health/mhgap/en/ (although that might be funny).
Pitch to consider _Gap Action_.

**Comment by LouisChiquet** [comment]
I quite like the reasons pushed by @rebeccabrover !
And on the translation, at least in French, can find words in two/three syllables (which is shorter then the current term and still very short) for “gap”.

**Comment by chrcowan** [comment]
@rebeccabrover Oh! I really like "gap action!" If a change is needed at all, then I think it should be in the direction of clarifying what the term _does_ or _how/when to use it_ rather than what it _is_. If that makes sense. And "gap action" is more like a functional definition, which I like.

**Comment by brianjrobertson** [comment]
That is pretty cool, but it doesn't actually resolve the original tension, which is with the word "action", not "individual" - that often confuses people, because we're re-using the word "action" but with a totally different meaning than "next-action" elsewhere in the constitution.  e.g., using this language, you might take on a project as a gap action, or take gap action to make a decision in another role.  To solve the original tension here, we need to replace the word "action" with something else.  "Gap Initiative", "Gap Filling", "Gap Act" (probably too close), etc... but none of those really speak to me.  "Gap Effort" maybe?  Other ideas for Gap Something?

**Comment by rebeccabrover** [comment]
@brianjrobertson I understand better now, thanks!
Gap Effort resonates with me. It's simpler and (in my opinion) more intuitive than Gap Initiative in terms of language and jargon, still conveys the meaning I intended with Gap Action and removes the confusion surfaced with your original tension. Ship it!

**Comment by brianjrobertson** [comment]
Okay, so, what do you all think: react thumbs-up if you think we should go with "Gap Effort", or thumbs-down to keep "Individual Initiative".

**Comment by brianjrobertson** [comment]
Thanks everyone!  I'm going to keep Individual Initiative for this, given how that flows better and makes more sense in normal language to someone unfamiliar with Holacracy language and rules (e.g. "I'm going to take individual initiative and make this thing happen.").
