### ISSUE TITLE
Add more powers that kick-in during a Process Breakdown

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#76]
The current special powers granted during a Process Breakdown were only designed to facilitate restoration in the event of a failed governance meeting.  As a partner in a Holacracy-powered company, I'd like more powers to kick-in during a Process Breakdown to allow graceful restoration from other observed causes of a breakdown, such as from someone continually ignoring policies or a whole circle just not doing governance, so that we can use the Process Breakdown rules in that case and find a smoother path to resolution (or so the threat of it stops the out-of-process behavior before it becomes a Process Breakdown in the first place).

**Comment by Roflcopterpaul** [comment]
This is something we talk about pretty often, because Process Breakdown doesn't really solve anything other than failed Governance practice itself. I think a solution is simply to have the Facilitator of the Super-Circle also gains all the same authorities a Lead Link normally has by default. This does two things:

1) Process Breakdown could also resolve many other issues, almost all of which are ones requiring coaching and/or Role Removal.

2) By giving the authority as well INSTEAD of simply taking over as LL, it means the normal LL can still attend meetings of the Circle and the Super-Circle (if the only Role they hold is LL). It also ensures the Super-Circle Facilitator would still have all the authorities needed even if a Circle has delegated those, put Policies in place to change how they work, etc.
