### ISSUE TITLE
Add mechanism for setting partner agreements

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#77]
As a partner or a role-filler, I'd like an effective and simple mechanism to define agreements I'd like from partners, including a way to make some agreements required for partnership, so that I can more easily process tensions that are beyond the scope of organizational governance to resolve, and which require partner-to-partner or partner-to-organization agreements to effectively handle.

**Comment by cassus** [comment]
:+1:

**Comment by LouisChiquet** [comment]
Do you have some concrete examples to help (of agreements you'd like for instance)?

**Comment by brianjrobertson** [comment]
Some partner-level agreements we have in HolacracyOne:

- I will prioritize attending the organization's official partner retreats in-person, even over competing personal preferences or events (except emergencies). This agreement does not apply to personal events that were on my calendar and committed to before I was invited to an overlapping partner retreat, however in those cases I agree to do my best to find a balance that maximizes the greatest overall good for everyone involved.
- I will travel as-needed for my roles, up to _____.
- I will use a personal credit or debit card to cover reimbursable expenses required to serve as a productive Partner of the organization or to support specific Roles I fill, and I will manage my available cash or credit to provide a sufficient buffer for these expenses.
- I agree to prioritize my attention however is needed to get a GTD-style Weekly Review done every week in most weeks, and to miss no more than one week in a row in any case short of major personal or cripple-the-company emergencies.
- When planning to take time off from work and I can reasonably expect that others may be impacted by my absence, then I agree to notify all relevant partners in advance.
- I will pre-process my own "charge" about a partnership issue before engaging other partners about it.
- I will use the tribal mediator to facilitate a difficult feedback conversation upon request of another partner.
- I will set a context for "pushing"/offering feedback, and if not a good time, not share the feedback then.

**Comment by brianjrobertson** [comment]
Hi Folks - I'd really love some more eyes on [this change](https://github.com/holacracyone/Holacracy-Constitution/commit/a4e75d43e328deb55c9acc593abb1911ed90d998): Does it make sense? Could it be simpler? Anything I'm missing? Any concerns or concerning scenarios you can think of?

**Comment by margauxchiquet** [comment]
For me, what is missing is how you can make a working agreement. Is it a policy? Is it a note published? Do it have the same weight as governance and if you break it it becomes a broken rule? I am not clear about this weight and place of this in the whole.

**Comment by chourie2** [comment]
Hi,

I really like the proposal, as someone one who really want to challenge myself on my behavior, theses Working Agreements offers me a way to clarify some goals for me and for others who might be able to rely on thanks to them! Really nice and it really make sense to me 👍 

Like @margauxchiquet I'm curious about the definition of theses Working Agreements. It's doesn't seems to be governance because it look like something anyone can add on himself as a Partner and not as a Role / Circle. Should the constitution clearly explain that it's not Governance if it's the right way of seeing it? Same question in the other case. And if so, I'm probably missing a point here!

I'm also not sure about the consequence of breaking such agreement. But if I'm right by seeing it as "Not Governance", I think that the only result might be that it may raise Tension to others Partners who relies on the disrespected agreements ? If so, I don't see any concern on that matter.

I also think that, to be usefull it needs to be published, just like governance, and even if it's not governance. Every Partner should be able to know the working agreements of others Partners, right? And if so, maybe it also need to be said in the constitution ?

@margauxchiquet, what do you think about a new section "Working Agreements" on the Partner page (your profil in glassfrog for example), on which you can only see Roles filled by the Partners and eventually tags I think currently? This new section would work almost exactly the same way the Note section work for a Role / Circle (I just don't think there is a need for a title for each Working Agreements).

**Comment by chourie2** [comment]
Hey, it’s me again!

Shower thoughts  :
Why call it « Working » Agreements if it include Partners to Partners agreements? IMO, these category of agreements could be (or systematically is?) in the human relation space, outside of the actual work, but still relevant for the organization.

Maybe something like Personnal, Individual or Partner Agreements might more reflect that you make the agreement as a Person / an Individual / a Partner, and whitout looking to determine the recipient which could be your Organization, Roles, other Partners or even yourself (let’s be crazy here!), if it make sense for you!

**Comment by klaas1979** [comment]
I got a question:

> Working Agreements are for shaping Partner behaviors that underpin Role-based work, **and may not define expectations only relevant when a Partner is already energizing a specific Role**, nor expectations around how a Partner will prioritize across different Roles.

What is the interpretation of the 'may not define' part? Example:
Is it possible to define working hours for call center roles with a working agreement or not? The office hours are only relevant to a single role of the person.

**Comment by brianjrobertson** [comment]
Yes, that's possible - that's about defining an expectation of when someone will energize the role, not defining an expectation relevant when they're already energizing the role.

**Comment by brianjrobertson** [comment]
I was just reviewing all the feedback above - thanks folks!  I'm reopening this issue just to explore better names than "Working Agreement", per @chourie2's point.  Any ideas?  I'm not a fan of Personal or Individual; "Partner Agreement" or "Partnership Agreement" could work, although I'm not sure it's better or less confusing.  Any thoughts about that one, or any alternate ideas?

**Comment by LouisChiquet** [comment]
I quite like “Partner's Agreement”, will need to put some pedagogy to make understand that it's not for “ruling Humans” as they also have to give their consent, as the French laws are rather strict on expected behaviours (they need to be defined in Rule Book or job description legally speaking), but I believe it's the “easiest” for people to integrate. Knowing that “Partner” is generally replaced by a term of the company to designated all the individuals employed by the company (for instance Nonpareil), this generic but very specific term being also used in Governance, would make sense in my opinion.

**Comment by julianeroell** [comment]
"Partner Agreement" speaks better to me than "Working Agreement". A "working agreement" IMO could also be between between Roles, whereas a "Partner Agreement" is clearly between Partners.

**Comment by brianjrobertson** [comment]
Hmm, the intent is that these agreements are sometimes between a Partner and the org (via a Role)...

**Comment by LouisChiquet** [comment]
Those would be weird, knowing that relation between a partner and the company needs to be legally clarified through Rule Book or job description in France (Labour laws are rather strict), and would potentially create confusion in HR (because of negotiations the Partners can have with the HR). But what you said wasn't my interpretation of 2.5. So maybe I should bring another issue on this if there is one, so we keep on the name in this issue.

**Comment by chrcowan** [comment]
@brianjrobertson Random options that pop into my head...

Expectations Agreement
Relational Agreement
Partnering Agreement
Collaboration Agreement
Coworker/Coworking Agreement
Association Agreement
Alliance Agreement 
Partnership Protocol
Partnership Charter
Behavioral Agreement
Praxis Agreement
Partnership Praxis
Partnership Guidelines
Relational Rules

**Comment by oliviercp** [comment]
@brianjrobertson As I'm reflecting on the terminology, the main difficulty I encounter is in trying to name a construct that encompasses two distinct types of agreements. As you mentioned in the original post, there can be partner-to-partner or partner-to-organization agreements. I wonder if it would be simpler to differentiate the two and give them different names, e.g. Working Agreement and Partner Agreement?

(I looked at the section of the dev version of the constitution on that, and you have two paragraphs distinguishing the two types of agreements already)

**Comment by brianjrobertson** [comment]
I originally considered "behavioral agreement", and there's a lot I like about that.  And I still like Working Agreement.  But the more I think about it, the more "partnership agreement" seems confusing to me.  And note these are not just agreements between partners, but also agreements like "I'll show up to work by 9am" or "I'll wear a uniform to work" or whatever.  So, I think I'm leaning towards either Behavioral Agreement, to reinforce that those are agreements about behaviors specifically, or Working Agreement, to avoid the slight negative/punitive connotation that behavioral agreement has for some people.

I'm not sure there's any value in differentiating the two @ocompagne, because the actual structure is the same - the definition is the same.  It's just a matter of whether you're agreeing to hold to specific behaviors because the company asked or because another partner asked.

**Comment by brianjrobertson** [comment]
Any thoughts between Behavioral Agreement vs. Working Agreement?  Vote thumbs-up to switch to Behavioral Agreement, or thumbs-down if you think Working Agreement is better.

**Comment by oliviercp** [comment]
In that case I favor "Behavioral Agreement" because it's more accurate, and I value accuracy over the potential negative connotation for the sake of making Holacracy easier to understand. Some agreements can be partner-to-partner and very relational in a way that "working" agreement would be inaccurate IMO (or at least would be a stretch).

**Comment by chrcowan** [comment]
I also like behavioral agreement over working agreement.

**Comment by brianjrobertson** [comment]
The argument for Working Agreement over Behavioral Agreement was [captured here](https://github.com/holacracyone/Holacracy-Constitution/issues/90#issuecomment-194939417) by @ebabinet; does that sway you @ocompagne or @chrcowan, or do you still think Behavioral Agreement is better?

**Comment by chrcowan** [comment]
No, his argument doesn’t sway me.

**Comment by oliviercp** [comment]
I'm sensitive to Eric's argument but all things considered, I still prefer Behavioral Agreement for its added clarity. I wish there was a better option though

**Comment by MiekeByerley** [comment]
Would the Term of  Colleague Letter of Understanding (CLOU) address what
you are trying to address? I know that MorningStar  uses this as do many
other Self-Managing companies. Otherwise it might be a thought to connect
with encode.org in my opinion.


Please feel free to reach out and connect, or schedule some time here:* MeetMe
<https://beta.doodle.com/mieke_byerley>*

Mieke Byerley OFS
*Human Centric Organization*

*LinkedIn Profile <https://www.linkedin.com/in/miekebyerley/>*

**Comment by ericdgraham** [comment]
I like Working Agreement best. Behavioral agreement sounds like something you'd sign before entering parole. Too strict sounding. Working Agreement sounds more professional and collegial; adult to adult. IMO.

**Comment by brianjrobertson** [comment]
Man, I'm really torn on this one.  I'd love any additional perspectives or arguments anyone has, if there are any out there that aren't already covered above.  Anyone?

(@MiekeByerley, no, CLOU won't work - see the context of how it's used in the current draft version; we need something lightweight, and ideally some adjective before "agreement" to denote a certain type of agreement.)

**Comment by ebabinet** [comment]
I still prefer Working Agreements over Behavioral Agreements because of the
negative connotations of Behavioral Agreements, however I quite like
"Partner Agreements". Based on the current description, these are
agreements between Partners about how they "fulfill their general functions
as Partners" or interact with each other outside of role based work, but
still as Partners.

Brian gave examples of agreements that are not between Partners such as "I'll
show up to work by 9am" or "I'll wear a uniform to work", however, I'd
argue that you are still making that agreement as a Partner and with the
other Partners, even if the behavior does not involve other Partners.

**Comment by matthiask** [comment]
One comment regarding "behavioral agreement". I'm not a native speaker but "good work" (working agreement) and "good partnership" (partner agreement) sound positive but "good behavior" just doesn't. The latter does not sound like a symmetrical relationship to me, more like a parent-child relationship and that's not a good connotation in this context.

**Comment by brianjrobertson** [comment]
Okay, time for another poll:  How about Partner Agreement vs. Working Agreement?  Vote thumbs-up for switching to Partner Agreement, thumbs-down for sticking with Working Agreement.

**Comment by brianjrobertson** [comment]
Okay, I'm going with Partner Agreement for this one; thanks everyone!
