### ISSUE TITLE
Allow violating policies to trigger Process Breakdown

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#82]
People sometimes willfully violate policies (i.e. violations outside those allowed by Individual Action or unintentional/accidental ones), and there's nothing constitutionally that resists this.  Of course, you can always create processes/policies to remove/fire someone who does so, or define another consequence; however, I wonder if there should be something more directly in the constitution to take this from "app" to "core functionality"?

For example, willful violation of a policy (or a pattern of that) could more clearly count as a process breakdown, and the person impacted by the violation could be allowed to trigger it - that would create a major disincentive for doing so (few people want to be the cause of a "Process Breakdown" of their circle).  If more is needed, a person impacted by the willful violation could even have the right to demand the Lead Link replace the role-filler... or something.

Thoughts/reactions?

**Comment by dienkwik** [comment]
I think this would be really helpful if a default mechanism is already defined in the constitution,  This can be changed via a policy if needed, but it's there if no policy regarding violation has been created.

The idea that violation of the constitution is just another type of process breakdown with the default process breakdown mechanism kicking in sounds good and simple. However, I like the explicit expectation as well that before triggering process breakdown that other "softer" actions have been taken. This is similar to Morning Star's conflict resolution which starts with the impacted role giving feedback and reminding the violating role of the condition, and then perhaps escalating it to the Lead Link, and eventually triggering process breakdown if all other options have failed to produce result.

**Comment by Roflcopterpaul** [comment]
Similar to the above comment, I think Process Breakdown could work if 1) there are more powers granted in Process Breakdown that would allow a resolution (I provided some suggestions in the thread on that topic), and 2) there are some prerequisites to prevent from this being abused. I think a simple solution might be to give the Secretary the authority to declare Process Breakdown IF they feel rules are being broken (such as Policies being violated). Few extra thoughts on this:

1) As a Secretary, they should be able to interpret if the Policy/Domain is actually being violated based on the wording of it and what has happened. If it is not being violated, they publish why so people know what they can do in advance, or those who own the Policy/Domain can amend it to make it more specific.

2) Additionally, if it is ANY Secretary who is able to make a ruling on the interpretation (the Secretary of the Circle where the Policy/Domain is being violated, or any Super-Circle Secretary that could potentially overrule the decision), this solves many other concerns, such as:
- The Secretary of a Circle can call Process Breakdown on their own Circle if nobody else is listening to them when it is mentioned.
- If I own a Domain, or I am most affected by a certain Policy, and someone in another Circle is breaking it, I can go to the Secretary that is over both of our Circles to make a decision we both must adhere to.

**Comment by brianjrobertson** [comment]
Curious if anyone else has any thoughts to offer on this?  I'm currently thinking maybe we can solve this by expanding Process Breakdown, with some constraints and additional powers per comments above, with perhaps just a minor mention of violating policies (i.e. that's just one example/case of operating outside the rules of the game)...

**Comment by karilen** [comment]
You could require as part of the policy that a consequence be included. Or build in the restorative action or some process for engaging whoever violated the policy. Since often it is because people don't know or for good reasons then requiring a consequence or a pathway for dealing with violations forces people to think of what really needs to be constrained per policies.

**Comment by LouisChiquet** [comment]
I do not see violations out of the IA or accidents? Because in the company where everybody at minimum wish to play the game of Holacracy, there are no such issues, there is just eventually the case of the person refusing to respect such Constitution and Governance rules because of issues generally independent of the Holacracy system, which is -at least in France- legally like if you disobeyed an order from your hierarchy, the hierarchy authority being now the Constitution, and so it's solved legally if it's regular, is that such case? In which case, because of the many different cultures of companies, along with various legal systems, I'd believe that it might be better to not include this in the Constitution. And maybe I'm totally mistaken, a concrete example would help thanks! I know it's not really helping, but just wondering in which cases this would be necessary.

**Comment by brianjrobertson** [comment]
I've reviewed this further, and I believe this was already effectively resolved in a prior update to the dev version; the current text already allows a Facilitator or Secretary to declare a process breakdown from a pattern of Policy violations, via this:

> The Facilitator or Secretary of a Circle may declare a Process Breakdown within that Circle or one of its Sub-Circles upon discovering a pattern of behavior or outputs that conflicts with the rules of this Constitution.

I don't believe that more is needed here, so I'm closing this issue as resolved.
