### ISSUE TITLE
Change term for "Objection"?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#86]
Here's a suggestion I got recently and have seen a few times now:

> replace "objection" with "integration request"... objection has a negative connotation and a "me vs. you" feeling to it, whereas "integration request" has a "we" feeling to it...

From a flow perspective, it seems potentially clunky to say "integration request", and a bit odd to define "a reason that the proposal causes harm" as a "request"...

But I'm posting it here anyway for thoughts, as I do see value in a language shift here and I'd love to collect some more perspectives on this.  Do you think the value of this change is greater than those downsides?  Any alternate ideas?

**Comment by bernardmariechiquet** [comment]
Interesting... I'm so used to the Objection term. You post allows me to reflect on that too, cool. In case of a change, I would suggest "reason for integration" or "argument to integrate" or simply "integration item". For me "integration request" is to related to human "I want to integrate"

**Comment by tylerdanke** [comment]
Integration opportunity? for short integration opp or IO. I am aware of the Input output similarity and honestly I kind of like it. You put the initial proposal and the integration opportunity in as inputs and the output is a better proposal.

**Comment by deepmansingh** [comment]
How about "OMDB"?  Like in "Over My Dead Body" or, more precisely, "Over My _Role's_ Dead Body"?  ;o)  

But seriously ... if the term "Objection" carries very severe negative connotations which are insurmountable then we should consider a language shift.  But whatever we do in the end, IMO it would also be important to keep the following in mind:
1.  Conflict in Holacracy is a GOOD and necessary thing.  We need people to speak up - going against our conditioning for most of us - because each role's robustness and clarity depends on our doing so in service of the Role.  Sure, there'll be some discomfort in the beginning - there always is when we are changing deeply ingrained habits - and it is necessary.  My gut feel is this message gets diluted when we water down the language.
2.  Let's not become overly bland with our language.  I don't know about you guys, but I think Political Correctness has been overdone in recent times.  The change we are introducing takes energy and passion, and I would use all means at our disposal to not leak that unnecessarily. If it means taking terms like "Objection" and hijacking them and redefining them in context for our purposes, I would do it.  

Or, we could amp it up one level and go with a term like "OMDB", which is so clearly meant to be a fun, tongue-in-cheek variant of "Objection", that we actually side-step both the issues above!  (Not advocating for the term specifically - just opening up the conversation for more creative inputs.)

Thoughts?

**Comment by julianeroell** [comment]
I think "Objection" is clear and useful in this place. It is easily understood, even by non-experienced practitioners. It has an established meaning in many communities, compatible with the use in Holacracy. 
Creating a new word would make Holacracy less accessible. 

Also, I favor "going ahead" with proposals, and only stopping them when there is an "objection": An "integration request" could also work by having the initial proposal pass, and then adding a new proposal (with the person who has the "request" as the proposer). In my view, this is much clearer than making what is now "Objection Phase" more vague.

IMO "Integration Requests" come as comments in reaction phase: The proposer can then pick them up in Amend & Clarify. It seems strange to then have _another_ phase where "requests" can be made. A possibly change could be to rename "reaction round" to something else, and invite for "integration requests" there, rather than for "reactions".  At the end of the process, "Objection or no Objection?" is sharp, clear and helpful.

**Comment by Roflcopterpaul** [comment]
I am not a fan of it. Any language change is just going to require everyone to relearn the basic lingo, which can often take a long time, and can further complicate an already complicated process.

This also falls in line with tons of situations like this I have seen over the years in various types of work. Eventually, people want the verbiage changed because it has a negative connotation, but I believe the most important piece is not the word itself, but what we teach people that word means. While words like "Tension" and "Objection" make it hard to initially adapt, once people really learn what that means, there is rarely an issue. If we use a negative word and they learn it is a positive thing, it will become a positive word, and vice-versa.

**Comment by mpruce6** [comment]
I've found it useful just to frame objections and most holacracy words that have a negative connotations as a deliberate vocabulary change.  Not be offensive, we point out the differences and point to the parts of the word definitions that make sense.
We have a pretty fun sarcastic culture that sometimes the formality of it helps us focus on what's important so whatever word change would be considered should still be relatively forceful in my modest opinion.
If anything i'd recommend the challenge round as to whether a proposal causes harm or moves us backwards, since you still test a "challenge" constitutionally and challenge vs. and objection may lead to a more collaborative space for people to integrate. Just a thought.

**Comment by oliviercp** [comment]
I don't remember if I was the one suggesting "integration request", but although I'm not quite happy with it, I like the direction it's going toward. 

As a coach implementing Holacracy with new groups, I'm probably biased and sensitive to the _initial impact_ of the language. However if I pay attention to my own experience as a practitioner, I can still feel some resistance to the term Objection — it evokes a confrontational and divisive stance for me, even if I know it's not the case. I'd love to have another term that doesn't require me to make a rational effort to go pass that felt sense. My experience working with others is that I'm not the only one getting that experience. 

To make a broader (and admittedly more shaky) point, I also wonder how much personality-type preferences are at play here. Using the agency vs. communion polarity (or individualistic vs. group-oriented polarity), I suppose the term Objection appeals more to agency-oriented people, and my hypothesis is that it's true of Holacracy as a whole too. If it's true, then it would make sense for this preference to be reflected in the people attracted to Holacracy — especially those who coach it and/or participate in this forum :) It's definitely true for me, so I just want to call out a possible collective bias that I'd like for us to pay particular attention to. The value of shifting the language around Objections might be greater than many of us here initially sense.

Unfortunately I don't have a good alternate idea. Among what's been shared so far, Bernard-Marie's "reason for integration" gets the closest to the meaning I think the term should convey, but I don't like that it's 3 words instead of one. I'll post here if some ideas come to me later on.

**Comment by deepmansingh** [comment]
Hmm ... good point.  In the spirit of initiating a second brainstorm, why not simply call it a "tension"?  The Constitution says:

_Before a Proposal is adopted, all Core Circle Members must have the opportunity to raise Tensions about adopting the Proposal. Each Tension so raised is considered an “Objection” if it meets the criteria defined in this section, and the person who raised it becomes the “Objector”._

So, Proposer presents a Proposal.  "Sensor" raises/feels/senses/presents a "Tension".

Feel neutral enough?  Doesn't appear to encroach on other uses of the terminology "Tension" ... thoughts?

**Comment by oliviercp** [comment]
I like how you're thinking about it @deepmansingh. I don't think it works because Tension has a broader meaning than what Objection is conveying. An Objection is a procedural step that results from sensing a very specific type of Tension: only those that are about a decrease in the circle's capacity to express its purpose. 

A Tension could be a ground for a valid Objection or not, depending on the specific Tension (e.g. a Tension about a proposal purely because you would like to improve it is not a valid Objection). So it would be confusing to use the same term for two different constructs.

**Comment by deepmansingh** [comment]
I see your point @ocompagne.  So, I Iooked up synonyms, and within the current frame, **demurral** popped up as a softer possibility.  I guess the disadvantage would be that it's not a very common term, and hence less accessible.

You know, the way it IS currently framed, I think the procedural step itself is biased more towards agency than communion.  Communion seems to be more about collectively improving things, rather than allowing agents to proceed as long as they are doing no harm.

Last thing I tried was substituting the word Objection in your own Demurral **;o)** to see if it helps further the brainstorming effort:

_I don't think it works because Tension has a broader meaning than what Objection/Demurral/Integration Request/OMDB is conveying. An Objection/Demurral/Integration Request/OMDB is a procedural step that results from sensing a very specific type of Tension: only those that are about a decrease in the circle's capacity to express its purpose._

_A Tension could be a ground for a valid Objection/Demurral/Integration Request/OMDB or not, depending on the specific Tension (e.g. a Tension about a proposal purely because you would like to improve it is not a valid Objection/Demurral/Integration Request/OMDB). So it would be confusing to use the same term for two different constructs._

Does that open up any additional thoughts?

**Comment by brianjrobertson** [comment]
Definitionally, I think demurral is worse than objection - it implies disagreement (where objection implies a reason for disagreement, which is closer), and it has a more personal connotation - a "personal disapproval" vs. a reasoned challenge.

And I don't think "Integration Request" works practically - e.g. what do you actually say in the meeting when you have one or don't have one (if not "objection" or "no objection"), and what do we call the person who raises one (if not "the objector"), and what do we call the actual tension they express that will be created and cause harm (if not "the objection")?  I don't see good answers for those with "integration request", without even getting into the issue of it being two words and thus unlikely to actually stick even if we did change it.

So, if anyone has more ideas keep them coming... but I think objection is currently the best option I've seen, despite the known issues with it.

**Comment by brianjrobertson** [comment]
@mpruce6's suggestion of "Challenge" could work, but not sure it's solving the issue behind "Objection"...

**Comment by deepmansingh** [comment]
@ocompagne Your tension surrounding the agency vs. communion polarity (or individualistic vs. group-oriented polarity) has been brewing at the back of my mind, and some interesting thoughts have arisen.  Here they are ...

Clearly, the intention is that we want to ensure that no Proposal "would actually move the Circle backwards in its current capacity".  That's the WHAT we are aiming for.  The HOW, today, is couched in agency language.  I would imagine that there is no reason that the HOW can't be practiced using a communion polarity.  If, that is, some ways can be found to not move the overall effectiveness of Holacracy backwards!  :o)

Clearly, the pyramidal organizational structures have been very expensive in terms of squelching autonomy (an "agency" attribute), and one of the great contributions of Holacracy has been its liberation.  Also, even the act of reflecting on the "communion" pole immediately conjures up images of the dreaded "consensus" practices as practiced in many regular organizations, which often end up impacting effectiveness even more than "predict and control"!  

_I guess what I'm saying is, we may have some invisible prejudices in what we look at and what we don't, based entirely on our reaction to what has been the dominant paradigm over the last century or so. And, in fact, our preferred cultures._  

Further, in that regard, we may also want to be alert to _other_ people and organizational needs that the old paradigms ended up satisfying, which Holacracy is inadvertently missing because of our (necessary) focus on the incredible flaws we are fixing - aspects that have been so persuasively captured in the presentations that Brian has made in his talks.  And, this is _especially_ important, as we bear in the back of our minds what may be required as we move 1) across Cultures and 2) beyond Early Adopter stages. 

Haven't had the time to process this yet, so I've gone ahead and attached an article entitled "**SCARF® in 2012: updating the social neuroscience of collaborating with others**" which I happened to come across, and which you guys might (or might not) find interesting / useful to browse through.

@brianjrobertson Finally, just reflecting a little further on the **WHAT** vs. the **HOW**, I'm wondering if the **Constitution** itself needs to be two documents (at least):  One which lays out the WHAT and the other(s) which lay out possible ways (HOW) to arrive at the WHAT.  A simple example here is that the Constitution lays out a very specific HOW for a Governance Meeting.  Looks like HolacracyOne has found a much better off-line "HOW" to obtain the the Governance function's WHAT outputs, without having to use the Constitution's prescribed HOW.  Even some of the discussion threads here are now trying to find solutions to "HOW" centered concerns along the lines of how "regular" does a "regular Governance Meeting" need to be.  The other issue (from my detached, beginner's point of view) is it feels like complexity is getting added to the Constitution - which I'm sure is really useful stuff for organizations well-practiced in Holacracy, but may be daunting for others who haven't yet started down the path.

BTW, when I go into reflective mode like this, I tend to address only the Work / Purpose, and offer up ideas to engage with - consider, build on, reject outright! - and typically ignore how they may land personally for anyone!  Hope that works, and please do let me know if you'd like me to engage differently!

[09_SCARF_in_2012_US.pdf](https://github.com/holacracyone/Holacracy-Constitution/files/174817/09_SCARF_in_2012_US.pdf)

**Comment by brianjrobertson** [comment]
@deepmansingh Appreciate that contribution and the spirit in which you offer it!  I don't have time to engage more fully in this dialog at the moment, but I appreciate reading your reflections nonetheless...

**Comment by deepmansingh** [comment]
@brianjrobertson Thanks!

**Comment by SamHasler** [comment]
how about:
- unaddressed tensions
- overlooked tensions
- unaccounted for tensions

**Comment by KoenVeltman** [comment]
@deepmansingh have a read at this post where we discuss exactly the idea you have on the constitution as 2 "documents" https://github.com/holacracyone/Holacracy-Constitution/issues/89

**Comment by topherhunt** [comment]
Total outsider and non-practitioner here so take this with grains of salt, but I had a couple thoughts when reading through all this:
- The term should be part of common English so it doesn't feel like yet more jargon for people to get used to.
- The term must be light on the tongue so constant use feels natural. The multi-word phrases suggested above, seem to capture the spirit you're looking for, but they're a mouthful and I worry that this would encourage people to try shortening them or avoid using the term.

What would be drawbacks of using one of the following words?
- Concern (at the risk of falling into the PC trap that @deepmansingh points out, it’s less charged than "objection"; it implies a thing to be resolved, rather than opposition or resistance)
- Obstacle (suggests an objective real-world thing to be removed, rather than a personal reaction, and is similarly less emotion-laden)

**Comment by MiekeByerley** [comment]
Hmm, coming from the Improvement Sector we used to use the acronym term
"OFI" which stood for "Opportunity for Improvement" you could change it
slightly by making it mean "Opportunity for Integration" if you really
wanted to. So you would simply state you would like to raise an OFI in
response to a Proposal.

**Comment by lmmathurin** [comment]
The outcome of a valid Objection is triggering the Integration Process.  

So if we want to focus more on the outcome, which is desirable for the org.  Integration Request seems more appropriate.

We can still test is the Integration Request is valid without changing the validation process as defined in the Constitution.  

Like I said earlier the objective, ultimately the WHY we raise an valid Objection seems more close to me to the semantic of Integration

For semantics
Integrating definition :
1.
to bring together or incorporate (parts) into a whole.
2.
to make up, combine, or complete to produce a whole or a larger unit, as parts do.

Objection definition:
a reason or argument offered in disagreement, opposition, refusal, or disapproval.
2.
the act of objecting, opposing, or disputing:
His ideas were open to serious objection.

**Comment by bernardmariechiquet** [comment]
@lmmathurin Thanks for your contribution, I do like it a lot. My only concern is that *integration request* feels like too long to prononce when facilitating, I would prefer only one word.

**Comment by brianjrobertson** [comment]
Just re-read all of this and reflected further, and I think it's critical that the term used be a single word that's reasonably common english (not a phrase or a made-up word/acronym); if we can't find a better one-word common term, then I'm sticking with Objection.  Given that basic criteria, I think @topherhunt's two suggestions are worth considering further: "Concern" or "Obstacle".  Any thoughts on either of those, or opinions on if either is substantially better than "objection"?

**Comment by topherhunt** [comment]
+1 for "obstacle" because "concern" feels a bit wishy-washy. To me "obstacle" suggests something tangible that's out in the world, whereas "concern" sounds more personal, subjective, and could easily be mistaken as a euphemism for "dislike". Also notice that you *have* an objection or a concern, whereas you *see* an obstacle.

**Comment by bernardmariechiquet** [comment]
I like the idea of "concern" for two reasons. One, this word is already used into the process card for testing "Is your concern a reason the proposal causes harm, or...", it works quite well so it seems quite a natural one to use. Second, this "concern" word would lower the bar for getting Objections raised, this will ease people getting through habit number 6 - Encourage Objections, which is a key one for a practice to stick. "Concern" by itself is not discouraging as "Objection" does. I would then also rename "Objection Round" by "Decision Round" - "Concern Round" would be too weird and there is more more reason to go fishing for objection as there would be no more negative connotation.

**Comment by cassus** [comment]
+1 for "Encourage Objections" from @bernardmariechiquet 

I understand we test objections because we already treat them like concerns:
There are _concerns_ (which are wishy-washy and it's fine, we want to encourage people trying to raise more objections) and after checking them they can become _valid concerns_ and we only integrate _valid concerns_. I like this language it feels more easy to use, inviting.

**Decision Round** sounds a bit discouraging for raising objections. eg. _"We were already in decision round so I didn't want to raise any concerns."_
**Concern Round** sounds strange but I think it avoids this trap. Maybe we can come up with something better.

**Comment by lmmathurin** [comment]
Since the outcome of a valid objection is an integration process. I was
suggesting two words..."Integration Request"....but I can understand the
point of Brian of trying having one word.
So, why not just "Request".

At the end, when you have an Objection....in fact you are *requesting *to
modify the proposed governance.

It sounds good to me at least :-)

Request(s) round
We can test if the request is valid or not.



2017-07-27 4:32 GMT-04:00 Adam Banko <notifications@github.com>:

**Comment by brianjrobertson** [comment]
I'm already using "concern" in the dev version of the constitution (and on the process cards) to describe what is raised that might or might not be a valid objection (in lieu of v4.1 calling that a "tension", which was overloaded and confusing).  But I want a separate word for that, and "concern" seems perfect for it, so I can't use that to replace "Objection".  So, I could just keep using "Objection" (but still using "concern" for what you raise, and then you test to see if the concern is really an Objection to this specific Proposal that must be integrated before adopting it).  Or, I could go with "Obstacle", so you raise a concern, and then test it to see if it's an Obstacle to the Proposal that must be integrated before adopting it.  I'm not sure if that really helps us much though, and I need a pretty overwhelming case to justify a wording change to something this core that works well-enough.  Anyone want to offer a pitch for why there's a pretty overwhelming case to make that change?

**Comment by mpruce6** [comment]
The only pitch I'd have for the change is with practitioners, even the more advanced ones I have in my organization, that the term objection leads to the feeling of "Holacracy Lawyering" where individuals feel like objection itself is the start of an argument not an obstacle.  There is a different energy to, "hey this gets in the way of my work."- an obstacle.  and Objection- "I find what you're proposing objectionable-insert whatever emotional baggage comes with "objectionable"   With a system that is trying to be clear and work focused the more that can be clarified to help the people and their feelings interfacing with it sort out what is and isn't optimally processed in the system the better off it will be.
However, one option could be is leave objection and have an app approach where users could use a process like IDM to come up with a culturally relevant term and modify their own constitutions to use it.  With the diversity that exists in the Holacracy community I could see objection and its translations working better in some places better than others. Maybe some kind of shared meaning clause/app.  
Role: Context meaning navigator
Purpose: Defining holacracy terms clearly in our  orgs context
Accountabilities: etc.
Policy:
Whatever process the role uses to get to shared meanings in context.

**Comment by LouisChiquet** [comment]
There are lots of negative definitions effectively of “_objection_”, but I actually very much like this Holacracy Lawyering, as it's a game, and just like a court:
“_Law : an act of formally objecting to something during a trial._
_—used as an interjection by lawyers during trials when they think something is not fair or proper_”
But I understand it can't be integrated easily in English, particularly because of American Law/Common Right culture (as for French speakers it's “_Empêchement, obstacle, difficulté qui s'oppose à la réalisation de quelque chose_” which fits perfectly in my opinion).

May think of “_anomaly_”, “_an anomalous person or thing; one that is abnormal or does not fit in_”, which would fit well as the facilitator needs to take an impartial and curious stance trying to understand the anomaly bit like a scientist.

**Comment by denniswittrock** [comment]
My sense is that asking for "concerns" instead of "objections" would help lower the bar for people to raise their issues with an existing proposal. I would use it as a tweak of language in the context of practice.

In a second step, you would help the person with a "concern" to find out whether their concern is 
"a concern that needs to be integrated" vs.  
"a concern that does not need to be integrated" (because it does not constitute a valid objection according to the rules of the constitution). 

Using this language in practice would probably lessen the discomfort around raising an "objection" and unearth more concerns - even if one should find out that many of those "don't need to be integrated" (which itself is a softer way of saying "invalid").

I am not sure that it is necessary to modify the constitution to call it a "concern-round". It is probably better/ enough to modify the meeting cards and teach this language-tweak and way of framing the objection round to new facilitators. 

Either way - I will experiment with that and let you know once I have more data from practice...

**Comment by julianeroell** [comment]
>My sense is that asking for "concerns" instead of "objections" would help lower the bar for people to raise their issues with an existing proposal. 

That is certainly true, but why would you want to "lower the bar" for people to "raise their issues with an existing proposal"? 

In my view, the function of the governance process is to allow _the agenda item holder_ to effectively process their tension into meaningful output, while protecting the organisation from harm. For this, it is unnecessary to encourage people who are _not_ the agenda item holder to "raise issues": They can (and should!) raise any issue they want as their own agenda items! 
This should be both more efficient and more effective in processing tensions into meaningful outputs.

**Comment by denniswittrock** [comment]
Hi Martina,
>> My sense is that asking for "concerns" instead of "objections" would help lower the bar for people to raise their issues with an existing proposal.

>That is certainly true, but why would you want to "lower the bar" for people to "raise their issues with an existing proposal"?

I follow the recommendation of **encouraging objections** in order to examine them. By framing them as "concerns" for the potential objector, it would lower the bar for them to bring them up in the first place. Only then we can examine the proposal for harm. Otherwise precious information may get lost for the organization.

Here's the counterexample: on the other end of the spectrum you might ask for objection or  no-objection this way: 
_"Only say 'objection' if you have an objection that meets all 4 criteria of being valid according to the Holacracy constititution? Really? Really, really? Prove it!"_ 
This way you would be sure to kick out valid objections even more efficiently (which we don't want). 

Instead lower the bar by asking if there is "ANYthing wrong with the proposal in ANY way" - a.k.a. if there is any CONCERN they might be having with it - even if only vaguely. At this stage it is simply a way in that allows investigation of a potentially valid objection. If people are uncertain, wether they have an objection or not we want to be as inviting as possible to help them find out, instead of them discarding it internally for fear of not being able to pass all criterias perfectly. 

That's the my whole thinking behind "concerns" instead of "objection"

**Comment by julianeroell** [comment]
>Instead lower the bar by asking if there is "ANYthing wrong with the proposal in ANY way" - a.k.a. if there is any CONCERN they might be having with it - even if only vaguely. At this stage it is simply a way in that allows investigation of a potentially valid objection.

That seems incredibly inefficient to me.

> If people are uncertain, wether they have an objection or not we want to be as inviting as possible to help them find out,(...)

... which is why we always encourage people to bring their tensions into the agenda. Holding their own agenda point, they can very efficiently and effectively turn their tension, concern, improvement into a meaningful output.

**Comment by brianjrobertson** [comment]
Last call for input on this; the only possible change I'm still entertaining from this thread is a change of "Objection" to "Obstacle".  Give me a thumbs-up reaction if you think that change is worth making, or a thumbs-down if you think sticking with Objection is best.  Comments welcomed as well.

**Comment by lmmathurin** [comment]
Thumbs up

Le ven. 22 juin 2018 23 h 34, brianjrobertson <notifications@github.com> a
écrit :

**Comment by jorisleker** [comment]
Thumbs up. Aligns nicely with *impediment* as used in agile/scrum.

**Comment by LouisChiquet** [comment]
Thumbs down, as in my interpretation, not every objection is an obstacle.
“_A thing that blocks one's way or prevents or hinders progress._” definition from Oxford Dictionary. So you're planning to say Obstacle Round? And not every objection is blocking, or preventing, or hinders progress, but it's also for going beyond, clarifying something, and obstacle really give this sensation of against or “something to overcome”, while objection as I previously said “as it's a game, and just like a court:
“_Law : an act of formally objecting to something during a trial.
—used as an interjection by lawyers during trials when they think something is not fair or proper_””.

**Comment by margauxchiquet** [comment]
Hi Brian,

Thumbs down because if my understanding is correct “obstacle” (in french “obstacle”) is something that opposes to the movement. In this case if would be considered as an opposition to the proposal, something that goes against instead of building on top of.
I guess this is not the meaning of an objection so I'd like to keep it this way if you don't consider a more positive change like “need for integration” or “tension related to the proposal” or something.

**Comment by brianjrobertson** [comment]
Thanks all, appreciate the thought-partnership on this one.  Considering all perspectives shared, I'm sticking with Objection and closing the thread.
