### ISSUE TITLE
Better enable "executive assistants"

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#91]
As an executive who benefited from the services of an Executive Assistant prior to Holacracy, I'd like to be able to allow an EA role to act in my other roles, almost as if a surrogate role-filler in certain ways and for certain decisions, so that we have a better means of mapping that work into Holacracy beyond just "create a role for it", which doesn't really fit the reality of how EA's often operate.

**Comment by brianjrobertson** [comment]
Would love any thoughts/ideas on a simple rule that would achieve the goal here without too much weirdness/complexity...

**Comment by tylerdanke** [comment]
I have been pondering this myself quite regularly and have not came to any
satisfactory simple answers.

Tyler Danke
Tyler@purelypoultry.com
920-359-0554
https://www.purelypoultry.com/

**Comment by deepmansingh** [comment]
Ooh, interesting.  Caveat:  Beginner's mind speaking ...

The way I understand Holacracy from my first pass of reading / research of it from the outside, theoretical level, the following precepts appear to hold true:
1.  Given the reality on the ground at any point in time, the Governance processes are used to incrementally refine the purpose, accountabilities and domains belonging to any given Role.  These are deliberately kept distinct from the Person energizing the Role.
2.  A Person energizes many Roles, and on a best efforts basis, using his / her own judgement, and aligning with strategies / priorities that flow down from the parent circle (and supercircles?), uses his / her time and resources to express the energized Roles' Purposes, and executes on the accountabilities.  However much can be achieved within these constraints is considered sufficient, because, you can only cut your coat according to your cloth.
3.  You need a larger coat!  Hence, multiple people can energize the same Roles; typically, when this is done, a separate "focus" is assigned for the Person to honour while energizing the Role.

Now, let's consider the "EA" JOB from the parallel world, and how it can translate into the Holacracy world.

The way I've always understood the EA Job is that it extends the capabilities of the PERSON to do their Job.  Part of the paradigm is the accountability remains with the Boss, as do the honour, rewards and brickbats, while the doing of pieces of the work is delegated to the EA.

So, speaking from purely the Purist viewpoint, I don't see why an EA Role would ever be required in Holacracy.  Since the intention in Holacracy is always to define and energize Roles, two thoughts suggest themselves:
1.  Have multiple people energizing the specific Roles that have exceeded the resources of the Person currently energizing the Roles.
2.  Or, break the Roles into multiple Roles, carefully designed, so that another Person can energize one of the spun off Roles.

In Holacracy, I would imagine, the EA Job would thus have been translated into the required underlying Roles, which can be handled my one or more people.  Exactly in line with how the rest of the work has been redefined in the Holacracy world.

Like I said - this from a Purist 101 perspective.  And, I see no reason why it shouldn't be approached this way.  That said, as new paradigms adjust to existing cultures and realities, sensible temporary adjustments do have to be made for the eventual, larger Good.

Cheers,
Mandeep
deepmansingh@gmail.com
http://www.linkedin.com/in/deepmansingh
202-431-9858

**Comment by brianjrobertson** [comment]
As of the change just submitted, this can now easily be done by assigning someone to a Role as a Role Supporter.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Could you develop and/or send a link to Role Supporter?
